### ISSUE TITLE
Enhancement: Use Makfile.local instead of makefile.local

### ISSUE THREAD

**Issue by lcn2** [ioccc-src/mkiocccentry#1033]
### Is there an existing issue for this?

- [X] I have searched for existing issues and did not find anything like this

### Describe the enhancement

The file, `Makefile.local` should be used instead of `makefile.local`.``

### Relevant images, screenshots or other files

n/a

### Relevant links

n/a

### Anything else?

Post **CODE FREEZE** and post-IOCCC28.

All comments and work of this issue to be delayed until after the IOCCC judges's post-IOCCC28 vacation.

**Comment by xexyl** [comment]
Happy to do this .. if you want .. later on. Or you can if you want to introduce your concept you suggested in the other issue, which seems very different from what we had here (and certainly different from my original idea which did prove very useful).

**Comment by lcn2** [comment]
p.s. Use `-include Makefile.local`

**Comment by xexyl** [comment]
> p.s. Use `-include Makefile.local`

Will do. This will require a few changes to warn about its use. Can look at your full concept as well. 

But not today. Obviously I mean over there. Perhaps with your additional ideas it will be better. 

Have to leave. Good day and good luck!

**Comment by lcn2** [comment]
We believe we have addressed all of the current questions that still need answering at this time. If we've missed something or something else needs to be clarified, please ask again.

**Comment by xexyl** [comment]
This one is done except for in `jparse` as that has to be done 'over there' first by re-adding it and then fixing the test scripts to move the Makefiles temporarily. But I already brought up a potential problem with that. That has to be figured out too and that will require some testing.
