### ISSUE TITLE
[Bug] grammatical error in mkiocccentry(1)

### ISSUE THREAD

**Issue by lcn2** [ioccc-src/mkiocccentry#1036]
### Is there an existing issue for this?

- [X] I have searched for existing issues and did not find anything like this

### Describe the bug

The code prints:

```
You title must be between 1 and 32 ASCII characters long.
```

### What you expect

The code prints:

```
Your title must be between 1 and 32 ASCII characters long.
```

### Environment

- OS: yes
- Device: certainly
- Compiler: obviously

### bug_report.sh output

n/a

### Anything else?

Bug was reported by Eliot Lear while testing mkiocccentry(1).

This is a **LOW PRIORITY BUG**.   We are simply documenting this for action after IOCCC28.

**Comment by xexyl** [comment]
I'm surprised that slipped through actually. I guess from all the other things that were going on.

I"m happy to fix that when it's time.

**Comment by lcn2** [comment]
We believe we have addressed all of the current questions that still need answering at this time. If we've missed something or something else needs to be clarified, please ask again.

**Comment by xexyl** [comment]
Do you wish me to fix this along with the other issues? I'll not ask this in another issue (besides the one I just did of course) so as to save you time.

**Comment by lcn2** [comment]
> Do you wish me to fix this along with the other issues? I'll not ask this in another issue (besides the one I just did of course) so as to save you time.

Yes please.

**Comment by xexyl** [comment]
> > Do you wish me to fix this along with the other issues? I'll not ask this in another issue (besides the one I just did of course) so as to save you time.
> 
> Yes please.

This one is done.. unfortunately you'll see a commit and it being reverted. I have no way to do that otherwise without bring in the jstrdecode -h bug (though as said in jparse it's fixed but it also has the validating of JSON first).

I'll look at the other issues and see if I can get them in too. In a little bit I have to go afk a while but I hope to do more when back.
