### ISSUE TITLE
[Bug] txzchk needs to verify that filenames are not longer than 100 chars, in accordance to rule 17

### ISSUE THREAD

**Issue by xexyl** [ioccc-src/mkiocccentry#1044]
### Is there an existing issue for this?

- [X] I have searched for existing issues and did not find anything like this

### Describe the bug

It seems that an additional detail was added to the rules after the tool was written: filenames in submissions may not be longer than 100 chars. None of the tools: `txzchk`, `mkiocccentry` and `chkentry` have this check in place.

### What you expect

These tools should reject filenames that are longer than 100 characters.

### Environment

What is...
- OS: Life.
- Device: Universe
- Compiler: Everything version 42.

### bug_report.sh output

n/a

### Anything else?

Please assign this one to me. I can take care of it in a day or two probably. It should be a pretty simple fix. The only reason to open an issue, I believe, is to discuss any finer details.

**Comment by lcn2** [comment]
# TOP PRIORITY

This needs to be resolved in early January as people looking into submitting to the IOCCC are looking at this repo NOW. We need to push out a version 2.2 of those repo that includes resolving this issue in early January,

This is why this is a top priority.

**Comment by xexyl** [comment]
> # TOP PRIORITY
> This needs to be resolved in early January as people looking into submitting to the IOCCC are looking at this repo NOW. We need to push out a version 2.2 of those repo that includes resolving this issue in early January,
> 
> This is why this is a top priority.

This one will take only a couple minutes if that .. might be able to do today but have to go afk a bit first. Then will depend on some things.

**Comment by xexyl** [comment]
I just fixed this .. however I need to update the version and also come up with some way to test it. That has to wait until later. Also since it might be better to make a new function for the other tools it might be that I do that first before a commit and then just fix them all in one go.

Anyway I better go now. Back probably tomorrow. Possibly today but unlikely.

**Comment by xexyl** [comment]
`txzchk` for rule 17 should be fixed: all that is needed now is to add a new test tarball listing to check that it works out okay! That should be easy enough to do .. just need to copy one and then add a filename that is over 99 in length! Then a make clobber all ; ./test_ioccc/txzchk_test.sh should verify it.

**Comment by xexyl** [comment]
`txzchk` update works!

I now have to add the .err file and then update the version ... will then work on the other test ones. Well chkentry has to have a function call too. However I have to go in under a minute so I just will update the version of txzchk and then update the version in the JSON files ... will be gone a bit of time but when back I'll continue my work here!

**Comment by xexyl** [comment]
`txzchk` is done! I will be afk a while now .. when back I'll finish the other two and then do a pull request.

**Comment by xexyl** [comment]
Okay I'm back .. will look at fixing chkentry. I am very tired and a bit sleepy so might take a bit of time. I also have to come up with a way to test it and same with mkiocccentry (which should be okay and because of that I might try that first .. but it will require a new function in the test script I think).
