### ISSUE TITLE
[Bug] mkiocccentry needs to verify that filenames are not longer than 100 chars, in accordance to rule 17

### ISSUE THREAD

**Issue by xexyl** [ioccc-src/mkiocccentry#1045]
### Is there an existing issue for this?

- [X] I have searched for existing issues and did not find anything like this

### Describe the bug

It seems that an additional detail was added to the rules after the tool was written: filenames in submissions may not be longer than 100 chars. None of the tools: txzchk, mkiocccentry and chkentry have this check in place.

### What you expect

These tools should reject filenames that are longer than 100 characters.

### Environment

- OS: no
- Device: thing
- Compiler: found

### bug_report.sh output

n/a

### Anything else?

In this case it's more complicated than txzchk. Some functions check for 0 length filenames and others do not check anything at all. I believe this should still be a relatively easy fix it just means more places have to be updated.

Please assign this to me unless you wish to take care of it.

**Comment by lcn2** [comment]
# TOP PRIORITY

This needs to be resolved in early January as people looking into submitting to the IOCCC are looking at this repo NOW. We need to push out a version 2.2 of those repo that includes resolving this issue in early January,

This is why this is a top priority.

**Comment by xexyl** [comment]
> # TOP PRIORITY
> This needs to be resolved in early January as people looking into submitting to the IOCCC are looking at this repo NOW. We need to push out a version 2.2 of those repo that includes resolving this issue in early January,
> 
> This is why this is a top priority.

I'll look at this tomorrow I think.

**Comment by xexyl** [comment]
Okay tomorrow it is ... about to shut down for the day and go do other things. I'll start out by adding the new function deep in the code of chkentry and then it should be easy for the other tools.

**Comment by xexyl** [comment]
This (rule 17 for mkiocccentry) **SHOULD** be complete! I want to figure out a way to test this however. Also I'm going to wait on the other two tools to make i a single pull request and I'll have to leave soonish for a bit.

Since this is done it does mean that in soup/entry_util.c there is a new function that tests the string arg for length > 0 && < MAX_FILENAME_LEN (which is defined in soup/limit_ioccc.h as 99).

So two steps are completed so far ... I'm only here atm as I have a cat on my bed (well actually I'd be back by now but not as far along here). 

The temp-test-ioccc repo clone should be done by now so in a bit I can look at the README.md file so you can mark that repo as read-only. But since I'm in the middle of this issue and since it's probably more important I'm going to work on this: again until I have to go afk .. then I probably will resume this one and finish it before moving back to that other repo.

**Comment by xexyl** [comment]
The test works for this update now!

Now I have to add checks in chkentry for the filename length ...
