### ISSUE TITLE
[Bug] chkentry needs to verify that filenames are not longer than 100 chars, in accordance to rule 17

### ISSUE THREAD

**Issue by xexyl** [ioccc-src/mkiocccentry#1046]
### Is there an existing issue for this?

- [X] I have searched for existing issues and did not find anything like this

### Describe the bug

It seems that an additional detail was added to the rules after the tool was written: filenames in submissions may not be longer than 100 chars. None of the tools: txzchk, mkiocccentry and chkentry have this check in place.

### What you expect

These tools should reject filenames that are longer than 100 characters.

### Environment

- OS: nein
- Device: nein
- Compiler: 99

### bug_report.sh output

n/a

### Anything else?

This one will be more complicated than txzchk and mkiocccentry as the checks are deeper in the code. However once the function (which should be easy to do) is added the other tools can make use of it. Then it's a matter of finding the right place to add the function call.

Please assign this to me. I can look at this tomorrow or the next day probably.

**Comment by lcn2** [comment]
# TOP PRIORITY

This needs to be resolved in early January as people looking into submitting to the IOCCC are looking at this repo NOW. We need to push out a version 2.2 of those repo that includes resolving this issue in early January,

This is why this is a top priority.

**Comment by xexyl** [comment]
> # TOP PRIORITY
> This needs to be resolved in early January as people looking into submitting to the IOCCC are looking at this repo NOW. We need to push out a version 2.2 of those repo that includes resolving this issue in early January,
> 
> This is why this is a top priority.

I'll look at this tomorrow.

**Comment by xexyl** [comment]
The function to check filename length is in! This means a new macro in soup/limit_ioccc.h is defined (MAX_FILENAME_LEN as 99). The chkentry code itself does not yet test the files. The mkiocccentry filename checks should be complete but I want a way to test it first before I commit. I'm not sure about this ... it might require an update to the mkiocccentry_test.sh script.

The next tool to be updated for this is the txzchk one. That should be easy. In fact yesterday I put in the change and then remembered I need to write a function for the checks. So I can just change the checks to the new function. Of course for a test I can add a new bad test file with a file length > 99 and then it should fail. That easily tests this one .. the other two tools might be more problematic to test: however since it uses the same function it might be okay (though it still would be good if I could integrate it into the test .. I think for chkentry it should be easier though maybe not).

I'll have to go afk in about half an hour. When back I'll be able to continue here and then when done I can look at the temp-test-ioccc README.md file so. you can put it in read-only mode! Once that is merged and all is okay I can delete that fork again and then I can fork winner and then work on grammar etc. Also I'll look at the issue you opened first.

Hope you're sleeping well!
