### ISSUE TITLE
Enhancement: Add a wrapper around mkiocccentry calls to system() and popen() to handle a wider set of args

### ISSUE THREAD

**Issue by lcn2** [ioccc-src/mkiocccentry#11]
Add a function that convert a shell string used by mkiocccentry calls to system() and popen() to handle arguments, such as filenames, that have characters such as spaces, *'s and/or have leading -'s.

**Comment by ilyakurdyukov** [comment]
I posted a code example on how to do this [here](https://gist.github.com/ilyakurdyukov/db5e81b87a7be5ac38813104c111799f). You can use any part of it as you wish.

List of characters I'm escaping (in a C string):
```c
const char *esc = "'\t\n\r !\"#$&()*;<=>?[\\]^`{|}~"
```

**Comment by lcn2** [comment]
After applying pull request #14 we intend to revise/refactor and apply comments / adjust as needed.

Then after successful testing, we will close this request.

**Comment by lcn2** [comment]
We will pause before entering in system test and documentation for the use of cmdprintf() concept, @ilyakurdyukov

Comments, suggestions and pull requests are welcome: especially during this pause.

Once we resume and complete the system test and documentation, we will close this request.

**Comment by ilyakurdyukov** [comment]
Now about using '--' so that filenames starting with '-' are not taken as options:

Can I assume that tar/cp/ls on any systems should know "end of options" symbol ("--") ?

**Comment by ilyakurdyukov** [comment]
Oh, it seems tar doesn't support '--', but I can put ./ at the beginning of the names that start with '-'.

**Comment by ilyakurdyukov** [comment]
`./mkiocccentry -- "--123 456" <...>`

Works just fine, but the instructions that mkioccccentry prints also need fixing:

```
Now that we have formed the compressed tarball file, you
can remove the entry directory we have formed by executing:

    rm -rf --123 456/test-1

If you are curious, you may examine the newly created compressed tarball
by running the following command:

    /bin/tar -Jtvf --123 456/entry.test.1.1642654750.txz
```

**Comment by ilyakurdyukov** [comment]
Fixed in the next pull request. I think it's fine now?

**Comment by lcn2** [comment]
Looks good, @ilyakurdyukov .. many thanks again for your help, pull requests and reviews!
