### ISSUE TITLE
Replace http with https

### ISSUE THREAD

**Issue by vog** [ioccc-src/mkiocccentry#12]
This issue is not about mkiocccentry, but about the "ioccc-src" organization itself.

The organization link shows the outdated:

* http://www.ioccc.org

which should be:

* https://www.ioccc.org

Perhaps there are other places within the GitHub settings and/or README and other plaintext files in the repositories where this should be updated as well.

**Comment by lcn2** [comment]
Fixed, @vog .. Thank you!
