### ISSUE TITLE
shellcheck fails under CentOS 7 for iocccsize-test.sh and mkiocccentry-test.sh

### ISSUE THREAD

**Issue by xexyl** [ioccc-src/mkiocccentry#153]
I'm letting you work this out because the iocccsize tool is special in that way and also I'm not even sure exactly what the expected output of the script should be so trying to fix it would be a problem.

**Describe the bug**

This is what you get under CentOS 7. Version info first:

```
ShellCheck - shell script analysis tool
version: 0.3.8
```

```shell
shellcheck: iocccsize-test.sh: hGetContents: invalid argument (invalid byte sequence)
```

Yes...it's incredibly helpful and in fact as helpful as watching dry paint dry but I tracked it down to this:

```shell
printf 'char str[] = "èéø";\r\n' >test-iocccsize/utf8.c
test_size utf8.c "12 21 1"
```

**To Reproduce**

Run `shellcheck` directly on `iocccsize-test.sh` under CentOS or run `make shellcheck` under CentOS (7).

**Expected behavio(u)r**

I think you know what should happen :)

In two commits today I fixed two scripts for shellcheck.

BTW apparently this was a bug that in shellcheck in 2015 (or a library that shellcheck uses? Not sure) but it's not been fixed or it's been fixed and either reintroduced or it wasn't completely fixed (or it's a related problem). Alternatively it's because CentOS 7 might not have a more recent update though 2015 seems a bit far behind to me: not sure.

**Comment by xexyl** [comment]
Oh as for possible solutions: some suggested `iconv`; others suggested specifying certain values for `LC_ALL` but I don't know what the right choice but maybe these will be of use to you. I'll be happy to test it and if you want to upload the script here for me to test first I'm happy to do that.

**Comment by xexyl** [comment]
Now that I think on it though there's something strange...

I could have sworn that `make shellcheck` passed before. I'm not sure when this might have changed or if I didn't actually run it but thinking on it I might have. Seems like I did as I vaguely recall fixing some scripts even by checking it under CentOS 7.

**Comment by xexyl** [comment]
Just noticed it happens for `mkiocccentry-test.sh` as well: of course because of the non-ASCII characters.

**Comment by lcn2** [comment]
> BTW apparently this was a bug that in shellcheck in 2015 (or a library that shellcheck uses? Not sure) but it's not been fixed or it's been fixed and either reintroduced or it wasn't completely fixed (or it's a related problem). Alternatively it's because CentOS 7 might not have a more recent update though 2015 seems a bit far behind to me: not sure.

We will work to see if we can eliminate this issue. 

Eventuality we will have to sunset Centos 7: but not anytime soon. I think we me mentioned 2024 in the Makefile: does that day still seem reasonable?

**Comment by xexyl** [comment]
> > BTW apparently this was a bug that in shellcheck in 2015 (or a library that shellcheck uses? Not sure) but it's not been fixed or it's been fixed and either reintroduced or it wasn't completely fixed (or it's a related problem). Alternatively it's because CentOS 7 might not have a more recent update though 2015 seems a bit far behind to me: not sure.
> 
> We will work to see if we can eliminate this issue.
> 
> Eventuality we will have to sunset Centos 7: but not anytime soon. I think we me mentioned 2024 in the Makefile: does that day still seem reasonable?

CentOS 7 reaches EOL in 2024 and yes that’s what you have in the Makefile possibly because I told you that.

**Comment by lcn2** [comment]
**QUESTION** @xexyl:

If you paste the offending line into [shellcheck online](https://www.shellcheck.net), does it report an error?

You mentioned that you identified the offending line(s).  We are sure you indicated somewhere in a previous post what file(s) and lines(s) (I'm in a remote coffee shop so it is hard for me to search) .. It would be nice if you could reply to this comment in order to consolidate that info if possible.

**Comment by xexyl** [comment]
> **QUESTION** @xexyl:
> 
> If you paste the offending line into [shellcheck online](https://www.shellcheck.net), does it report an error?
> 
> You mentioned that you identified the offending line(s). We are sure you indicated somewhere in a previous post what file(s) and lines(s) (I'm in a remote coffee shop so it is hard for me to search) .. It would be nice if you could reply to this comment in order to consolidate that info if possible.

I wish I hadn’t opened the email because it seems that under Safari on iOS the lines were merged. I am happy to do this but it will have to wait until I am at the laptop. That being said I will quote it in another comment so that it’s easy to find. 

I didn’t do it for the mkiocccentry test script but it’s of course from the characters that aren’t in the allowed set. Hold on and I will quote the one I did specifically identify. 

I will then be going to sleep shortly after.

**Comment by xexyl** [comment]
This is what triggered it:

> ```shell
> printf 'char str[] = "èéø";\r\n' >test-iocccsize/utf8.c
> test_size utf8.c "12 21 1"
> ```

**Comment by xexyl** [comment]
Just managed to do after all. No issues on the website.

**Comment by lcn2** [comment]
> Just managed to do after all. No issues on the website. 

Sorry, we don't understand.

Are you referring to the `make shellcheck` problem?  If so, are you indicating that we do not need to create a workaround for this problem?

**Comment by xexyl** [comment]
> > Just managed to do after all. No issues on the website.
> 
> Sorry, we don't fully understand, @xexyl.
> 
> Are you referring to the `make shellcheck` problem? If so, are you indicating that we do not need to create a workaround for the line that triggered it?

I'm sorry for the confusion: I meant the website does not have any problems; CentOS does so a workaround would still be needed for `make shellcheck` to work.

**Comment by xexyl** [comment]
FYI: CentOS 7 reaches EOL on 30 June 2024. After that there will be no updates given. Thus I think that towards June 2024 we shouldn't have to worry much more about the system. It might be nice to keep the current fixes in though: I leave that up to you.

**Comment by lcn2** [comment]
Perhaps commit 01fd2f0999a473ff21bc760fd23c62fa448cb84c is a suitable workaround for shellcheck issue, @xexyl ?

If so, please close this issue.

**Comment by xexyl** [comment]
> Perhaps commit [01fd2f0](https://github.com/ioccc-src/mkiocccentry/commit/01fd2f0999a473ff21bc760fd23c62fa448cb84c) is a suitable workaround for shellcheck issue, @xexyl ?
> 
> If so, please close this issue.

Booting up the laptop in a few minutes and I will check. Now please go get some sleep my friend and sleep well!

**Comment by xexyl** [comment]
> Perhaps commit [01fd2f0](https://github.com/ioccc-src/mkiocccentry/commit/01fd2f0999a473ff21bc760fd23c62fa448cb84c) is a suitable workaround for shellcheck issue, @xexyl ?
> 
> If so, please close this issue.

It solves it for `iocccsize-test.sh` but it does not for `mkiocccentry-test.sh` so I'm keeping this open.

**Comment by lcn2** [comment]
Sorry (tm Canada :) ) we forgot about the `mkiocccentry-test.sh` issue.

Perhaps commit 7cf4dcab8ca2020bd5621d2d33e6e603c505cfbb is a suitable workaround for shellcheck issue, @xexyl ?

If so, please close this issue.

**Comment by xexyl** [comment]
Closing as it works. Thanks!

**Comment by lcn2** [comment]
Yea 🥳

**Comment by xexyl** [comment]
> Yea 🥳

Yes. I also like the idea of commit ac4d268bc0. It's interesting that you would bring that up though because I actually thought of fatal versus non-fatal this morning (prior to doing a `git pull`) specifically because of some systems are behind.

Right now I'm the only one working on the parser (well you are too but you know what I mean) but what if someone were to want to work on it down the road and they don't have updated versions of bison and flex? `make prep` would have failed but a while back `make parser` was changed to just used the default files. This is good because someone else who is not working on the parser can then use the rule to prepare for a git commit. However this means that the `jparse.l` and `jparse.y` files could be inconsistent with the C and header files (except for `jparse.h` which is not generated by the tools) if they happened to update the `jparse.l` or `jparse.y` files.

My thinking is that this is not actually an issue but I'm bringing it up anyway just in case.

Hope you're having a nice sleep my friend! I hope to read the comments you wrote in the past couple days in a bit but depends on when my eyes want to focus more: I'm more alert than my eyes are.

**Comment by xexyl** [comment]
> Hope you're having a nice sleep my friend! I hope to read the comments you wrote in the past couple days in a bit but depends on when my eyes want to focus more: I'm more alert than my eyes are.

It's not looking good on this front for the day. I'm feeling quite off today but maybe I'll feel a bit better later on. Going to have a short lie down I think.

**Comment by lcn2** [comment]
Hope you feel better soon, @xexyl

**Comment by xexyl** [comment]
> Hope you feel better soon, @xexyl

Thank you very much! Hope you have a nice day as well!

**Comment by xexyl** [comment]
> > Hope you feel better soon, @xexyl
> 
> Thank you very much! Hope you have a nice day as well!

EDIT: I'll probably be better in a couple days or so. Just need to recover after the long weekend (good but long).

**Comment by xexyl** [comment]
> > Right now I'm the only one working on the parser (well you are too but you know what I mean) but what if someone were to want to work on it down the road and they don't have updated versions of bison and flex? make prep would have failed but a while back make parser was changed to just used the default files. This is good because someone else who is not working on the parser can then use the rule to prepare for a git commit. However this means that the jparse.l and jparse.y files could be inconsistent with the C and header files (except for jparse.h which is not generated by the tools) if they happened to update the jparse.l or jparse.y files.
> > My thinking is that this is not actually an issue but I'm bringing it up anyway just in case.
> 
> Should `make parser` be changed back to fail if `bison` and/or `flex` are not able to form a proper set of C code @xexyl?

I'm not sure: doesn't it also help so that a person without the right versions can also compile the code? If so it can't fail. On the other hand it's possible that it might be allowed to fail in `make prep` though that wouldn't prevent the case where someone forgets to run `make prep` prior to commit.


> 
> It is one thing to not have exit code sequenced, or if there is an lint-like issue with shell code, or if picky dislikes some C code. If it quite another if the `jparse.y` and/or `jparse.l` files cannot be used to update C code.

Right. And that's a possible problem. I don't know. Maybe an additional rule needs to be introduced and used instead or in conjunction with `make parser`?

> The `make prep` is NOT a rule that the average repo user needs to use. It is for the purpose of preparing a release. So while it might be OK to not have an up-to-date `shellcheck`, it is quote another to have a back-rev `bison` and/or `flex` and invoke the `make prep` rule.

Yes and I'm not sure what to do. I know GitHub does not allow hooks but is there a way to make it so someone who updates the parser/lexer files have to run `make prep` successfully (or at least `make parser`)?

Perhaps more rules need to be introduced: I don't really know what the right choice is but I believe that prior to making it not fail it would not copy the backup files. If that's the case that would be a problem for the average user I think?

**Comment by lcn2** [comment]
What if `make prep` were to also run `bfok.sh` and WARN (but not exits) if `bison` and/or `flex` are NOT OK?  The warning could explain that the `jparse.y` and/or `jparse.l` files could be out of sync, and thus one is unable to properly prepare for a release.

We could add a `make release` rule, that does the job of `make prep` BUT could fail immediately stop if one of the sub-makes failed.

OK, `make release` would not push something to GitHub.  But you get the idea. :-)

If we did this, then we would need to reverse a previous patch and allow `make picky`, `make seqcexit` and `make shellcheck` to exit non-zero on a failure.

So `make prep` would ignore non-zero exits from the invocations of make (i.e., sub-makes), and the new `make release` would abort on the first sub-make non-zero exit?

**Comment by xexyl** [comment]
> What if `make prep` were to also run `bfok.sh` and WARN (but not exits) if `bison` and/or `flex` are NOT OK? The warning could explain that the `jparse.y` and/or `jparse.l` files could be out of sync, and thus one is unable to properly prepare for a release.
> 
> We could add a `make release` rule, that does the job of `make prep` BUT could fail immediately stop if one of the sub-makes failed.

That sounds like a good name.

> 
> OK, `make release` would not push something to GitHub. But you get the idea. :-)
> 

Of course.

> If we did this, then we would need to reverse a previous patch and allow `make picky`, `make seqcexit` and `make shellcheck` to exit non-zero on a failure.
> 

Why not make only `make parser` part be a fatal error? Because as you say the others aren't strictly needed for a commit and what happens if another problem occurs under say CentOS like this issue was about? Okay CentOS would fail with the proper bison/flex versions but you get the idea.


> So `make prep` would ignore non-zero exits from the invocations of make (i.e., sub-makes), and the new `make release` would abort on the first sub-make non-zero exit?

Ah..so maybe `make release` would be like `make prep` but errors are fatal? But what should `make prep` be used for then?

**Comment by xexyl** [comment]
FYI: I'm going afk now. Will see about replying to things later on. Have a good morning and day!

**Comment by lcn2** [comment]
> > What if `make prep` were to also run `bfok.sh` and WARN (but not exits) if `bison` and/or `flex` are NOT OK? The warning could explain that the `jparse.y` and/or `jparse.l` files could be out of sync, and thus one is unable to properly prepare for a release.
> 
> > 
> 
> > We could add a `make release` rule, that does the job of `make prep` BUT could fail immediately stop if one of the sub-makes failed.
> 
> 
> 
> That sounds like a good name.
> 
> 
> 
> > 
> 
> > OK, `make release` would not push something to GitHub. But you get the idea. :-)
> 
> > 
> 
> 
> 
> Of course.
> 
> 
> 
> > If we did this, then we would need to reverse a previous patch and allow `make picky`, `make seqcexit` and `make shellcheck` to exit non-zero on a failure.
> 
> > 
> 
> 
> 
> Why not make only `make parser` part be a fatal error? Because as you say the others aren't strictly needed for a commit and what happens if another problem occurs under say CentOS like this issue was about? Okay CentOS would fail with the proper bison/flex versions but you get the idea.
> 
> 
> 
> 
> 
> > So `make prep` would ignore non-zero exits from the invocations of make (i.e., sub-makes), and the new `make release` would abort on the first sub-make non-zero exit?
> 
> 
> 
> Ah..so maybe `make release` would be like `make prep` but errors are fatal? But what should `make prep` be used for then?
> 
> 
> 
> 

Yes, `make release` would run thru the same actions as `make prep` but errors would be fatal.

**Comment by xexyl** [comment]
> > Ah..so maybe `make release` would be like `make prep` but errors are fatal? But what should `make prep` be used for then?
> 
> Yes, `make release` would run thru the same actions as `make prep` but errors would be fatal.

Sounds good. But what would the purpose of `make prep` be then?

**Comment by lcn2** [comment]
> 
> 
> > > Ah..so maybe `make release` would be like `make prep` but errors are fatal? But what should `make prep` be used for then?
> 
> > 
> 
> > Yes, `make release` would run thru the same actions as `make prep` but errors would be fatal.
> 
> 
> 
> Sounds good. But what would the purpose of `make prep` be then?
> 
> 

The `make prep`, on systems that are not fully up to date, will perform the same actions of `make release` on a best effort basis AND report back on issues/warning for that given system without aborting on the first sign of trouble.

One could try `make prep` on any system and see what it does.  One would only run `make release` on an up to date system that is capable of pushing a release.

BTW: Both `make prep` and `make release` would run a shell script (that does the work that `make prep` does now), but the later would run the shell script with a flag that would abort on the first error.

**Comment by xexyl** [comment]
> > > > Ah..so maybe `make release` would be like `make prep` but errors are fatal? But what should `make prep` be used for then?
> > 
> > 
> > > 
> > 
> > 
> > > Yes, `make release` would run thru the same actions as `make prep` but errors would be fatal.
> > 
> > 
> > Sounds good. But what would the purpose of `make prep` be then?
> 
> The `make prep`, on systems that are not fully up to date, will perform the same actions of `make release` on a best effort basis AND report back on issues/warning for that given system without aborting on the first sign of trouble.
> 
> One could try `make prep` on any system and see what it does. One would only run `make release` on an up to date system that is capable of pushing a release.
> 
> BTW: Both `make prep` and `make release` would run a shell script (that does the work that `make prep` does now), but the later would run the shell script with a flag that would abort on the first error.

And on that note I actually had the thought earlier of changing the make prep rule to write the warnings to a log file and at the end it would tell the user to check that (if there are any problems). This is because the output of the entire rule is quite long. Maybe the new script should have this instead?

**Comment by lcn2** [comment]
> > > > > Ah..so maybe `make release` would be like `make prep` but errors are fatal? But what should `make prep` be used for then?
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Yes, `make release` would run thru the same actions as `make prep` but errors would be fatal.
> 
> > > 
> 
> > > 
> 
> > > Sounds good. But what would the purpose of `make prep` be then?
> 
> > 
> 
> > The `make prep`, on systems that are not fully up to date, will perform the same actions of `make release` on a best effort basis AND report back on issues/warning for that given system without aborting on the first sign of trouble.
> 
> > 
> 
> > One could try `make prep` on any system and see what it does. One would only run `make release` on an up to date system that is capable of pushing a release.
> 
> > 
> 
> > BTW: Both `make prep` and `make release` would run a shell script (that does the work that `make prep` does now), but the later would run the shell script with a flag that would abort on the first error.
> 
> 
> 
> And on that note I actually had the thought earlier of changing the make prep rule to write the warnings to a log file and at the end it would tell the user to check that (if there are any problems). This is because the output of the entire rule is quite long. Maybe the new script should have this instead?

Yes.

**Comment by xexyl** [comment]
> > > > > > Ah..so maybe `make release` would be like `make prep` but errors are fatal? But what should `make prep` be used for then?
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > Yes, `make release` would run thru the same actions as `make prep` but errors would be fatal.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Sounds good. But what would the purpose of `make prep` be then?
> > 
> > 
> > > 
> > 
> > 
> > > The `make prep`, on systems that are not fully up to date, will perform the same actions of `make release` on a best effort basis AND report back on issues/warning for that given system without aborting on the first sign of trouble.
> > 
> > 
> > > 
> > 
> > 
> > > One could try `make prep` on any system and see what it does. One would only run `make release` on an up to date system that is capable of pushing a release.
> > 
> > 
> > > 
> > 
> > 
> > > BTW: Both `make prep` and `make release` would run a shell script (that does the work that `make prep` does now), but the later would run the shell script with a flag that would abort on the first error.
> > 
> > 
> > And on that note I actually had the thought earlier of changing the make prep rule to write the warnings to a log file and at the end it would tell the user to check that (if there are any problems). This is because the output of the entire rule is quite long. Maybe the new script should have this instead?
> 
> Yes.

Good I mentioned it then - though I imagine you would have thought of it as well.

**Comment by lcn2** [comment]
> > > > > Ah..so maybe `make release` would be like `make prep` but errors are fatal? But what should `make prep` be used for then?
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > Yes, `make release` would run thru the same actions as `make prep` but errors would be fatal.
> > > 
> > > 
> > > Sounds good. But what would the purpose of `make prep` be then?
> > 
> > 
> > The `make prep`, on systems that are not fully up to date, will perform the same actions of `make release` on a best effort basis AND report back on issues/warning for that given system without aborting on the first sign of trouble.
> > One could try `make prep` on any system and see what it does. One would only run `make release` on an up to date system that is capable of pushing a release.
> > BTW: Both `make prep` and `make release` would run a shell script (that does the work that `make prep` does now), but the later would run the shell script with a flag that would abort on the first error.
> 
> And on that note I actually had the thought earlier of changing the make prep rule to write the warnings to a log file and at the end it would tell the user to check that (if there are any problems). This is because the output of the entire rule is quite long. Maybe the new script should have this instead?

With commit e833b9f14fb63f6e1b8fd62838fe5a3f6b1ff4d9, the `make prep` is performed by a new script called `prep.sh`.  The  `make release` was named `make build`:

```
    Added prep.sh and make build

    The prep.sh tool performs the actions make prep did previously:

        usage: ./prep.sh [-h] [-v level] [-V] [-e] [-m make] [-M Makefile]

            -h              print help and exit 5
            -v level        flag ignored
            -V              print version and exit 5

            -e                  exit in 1st make action error (def: exit only at end)
            -m make     make command (def: make)
            -M Makefile         path to Makefile (def: ./Makefile)

        Exit codes:
            0    All is OK for both bison and flex
            1    -h and help string printed or -V and version string printed
            2        command line error
            3        Makefile not a readable file that exists
            4        Internal function error
            >=10 some make action exited non-zero

    The make prep will perform all of the actions.
    If some step failed along the way, exit non-zero at the end.

    The make build will also attempt to perform all of the actions.
    If a step fails, exit immediately

    Both make prep and make build will also write their output
    (stdout and stderr) to build.log, which may be examined later.

    The make clobber rule removes build.log.
```

**Comment by xexyl** [comment]
> > > > > > Ah..so maybe `make release` would be like `make prep` but errors are fatal? But what should `make prep` be used for then?
> > > > 
> > > > 
> > > > > 
> > > > 
> > > > 
> > > > > Yes, `make release` would run thru the same actions as `make prep` but errors would be fatal.
> > > > 
> > > > 
> > > > Sounds good. But what would the purpose of `make prep` be then?
> > > 
> > > 
> > > The `make prep`, on systems that are not fully up to date, will perform the same actions of `make release` on a best effort basis AND report back on issues/warning for that given system without aborting on the first sign of trouble.
> > > One could try `make prep` on any system and see what it does. One would only run `make release` on an up to date system that is capable of pushing a release.
> > > BTW: Both `make prep` and `make release` would run a shell script (that does the work that `make prep` does now), but the later would run the shell script with a flag that would abort on the first error.
> > 
> > 
> > And on that note I actually had the thought earlier of changing the make prep rule to write the warnings to a log file and at the end it would tell the user to check that (if there are any problems). This is because the output of the entire rule is quite long. Maybe the new script should have this instead?
> 
> With commit [e833b9f](https://github.com/ioccc-src/mkiocccentry/commit/e833b9f14fb63f6e1b8fd62838fe5a3f6b1ff4d9), the `make prep` is performed by a new script called `prep.sh`. The `make release` was named `make build`:
> 
> ```
>     Added prep.sh and make build
> 
>     The prep.sh tool performs the actions make prep did previously:
> 
>         usage: ./prep.sh [-h] [-v level] [-V] [-e] [-m make] [-M Makefile]
> 
>             -h              print help and exit 5
>             -v level        flag ignored
>             -V              print version and exit 5
> 
>             -e                  exit in 1st make action error (def: exit only at end)
>             -m make     make command (def: make)
>             -M Makefile         path to Makefile (def: ./Makefile)
> 
>         Exit codes:
>             0    All is OK for both bison and flex
>             1    -h and help string printed or -V and version string printed
>             2        command line error
>             3        Makefile not a readable file that exists
>             4        Internal function error
>             >=10 some make action exited non-zero
> 
>     The make prep will perform all of the actions.
>     If some step failed along the way, exit non-zero at the end.
> 
>     The make build will also attempt to perform all of the actions.
>     If a step fails, exit immediately
> 
>     Both make prep and make build will also write their output
>     (stdout and stderr) to build.log, which may be examined later.
> 
>     The make clobber rule removes build.log.
> ```

Sounds good. But one possible thing to consider: could  `make build` be thought of as just a helpful way to do normal compilation rather than prepare the files for a new release?

I don’t know if I am the best person to ask this as I know that in this case it’s me initially taking it more literally but it might still be something to ponder even if nothing is changed. Or I guess it could be given both names?

It’s very possible that when I am st the laptop again I will have some thoughts or questions but this is all I can think of right now. 

I am going to get ready to sleep now. Have a great night my friend! I will hopefully have more to say tomorrow and maybe I can work out the string regex but we shall see. Good night!
