### ISSUE TITLE
No new forks allowed?

### ISSUE THREAD

**Issue by xexyl** [ioccc-src/mkiocccentry#160]
See screenshot. Not sure if this was a mistake or something else going on but:

![Screenshot 2022-04-16 at 06 26 11](https://user-images.githubusercontent.com/53008573/163676746-ba12ed64-e08b-43bf-8fd5-271338ff9f77.jpg)

**Comment by lcn2** [comment]
It is **NOT** our intention to prevent forking.   We will look into the settings for this repo.

We thought you already had a fork of this repo: are you trying to create another fork and does GitHub limit the number of forks per account?

**Comment by xexyl** [comment]
> It is **NOT** our intention to prevent forking. We will look into the settings for this repo.
> 
> We thought you already had a fork of this repo: are you trying to create another fork and does GitHub limit the number of forks per account?

Quickly:

Right. I do have a fork of course but in the past when I clicked on forks it took me to my fork. Now it doesn’t. 

Perhaps they just changed how it looks? I don’t know but figured I would let you know just in case. 

Going again. More tomorrow!

**Comment by lcn2** [comment]
This repo is public, and thus this repo should allow forking:

```
This repository is currently public.
```

We don't see anything on our side that would prevent someone from forking.

**Comment by xexyl** [comment]
> This repo is public, and thus this repo should allow forking:
> 
> ```
> This repository is currently public.
> ```
> 
> We don't see anything on our side that would prevent someone from forking.

Must be that they changed how it looks. Strange. 

From the email preview on the phone I like what you wrote in the other threads but I will appreciate them more after sleep. 

Have a great night! I am closing this issue as it seems all is good. Good night my friend!

**Comment by lcn2** [comment]
Likewise @xexyl

**Comment by xexyl** [comment]
Since I had that conflict and since it appeared like the merge would not work right (maybe it would: I've not had to do conflict merges much in the past and it was a long time ago since I had and it was with repos that I share with only one other person) I decided to delete my fork and re-fork it so I can report that they just changed their interface.

In fact the fork option looks different as well: you can rename your copy of the repo and I don't recall that in the past though maybe it was there and I didn't notice it when wanting to quickly get the fork done. Anyway all is good! Thanks for looking into it.
