### ISSUE TITLE
bug: gcc version 8.3.0 reports an odd warning - null destination pointer

### ISSUE THREAD

**Issue by lcn2** [ioccc-src/mkiocccentry#19]
On gcc version 8.3.0 under Debian 10 (buster), we see the following odd warning:

```
mkiocccentry.c: In function ‘main’:
mkiocccentry.c:3883:8: warning: null destination pointer [-Wformat-truncation=]
  ret = snprintf(dest, dest_len, "%s/%s", entry_dir, base);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

The call to snprintf() and its args inside check_extra_data_files() function in mkiocccentry.c looks fine at first glance.

While we know we can "silence" this warning by adding -Wno-format-truncation to ${CFLAGS} (or remove -Wall), we DO NOT want do that.  If there has to be a fix, we would rather modify the mkiocccentry.c source.

The warning points to the front of the snprintf() function.  The snprintf() returns an int, which is assigned to ret: also an int.  Where is the null destination pointer?  Or is this a gcc bug?

Comments and pull requests welcome.

**Comment by ilyakurdyukov** [comment]
"dest" is the destination pointer, for some reason GCC think it is null. In this example it's definitely zero, but for mkiocccentry GCC is wrong.

```c
#include <stdlib.h>
#include <stdio.h>

void test(char *dest) {
	if (!dest) snprintf(dest, 4, "abc");
}
```

```
source>: In function 'test':
<source>:5:13: warning: null destination pointer [-Wformat-truncation=]
  if (!dest) snprintf(dest, 4, "abc");
             ^~~~~~~~~~~~~~~~~~~~~~~~
```

I'm assuming it's because of fallthrough from the errp():
```c
	if (dest == NULL) {
	    errp(147, __func__, "malloc #0 of %ld bytes failed", dest_len + 1);
	    /*NOTREACHED*/
	}
	ret = snprintf(dest, dest_len, "%s/%s", entry_dir, base);
```
If you put `return;` after errp(), then this warning might be silenced.

**Comment by lcn2** [comment]
Thanks @ilyakurdyukov fixed the warning.

It seems that gcc does not process /*NOTREACHED*/ comments,
so as you suggested I added a return;

**Comment by ilyakurdyukov** [comment]
I've never heard of `/*NOTREACHED*/`, but `__GNUC__` compilers must support `__builtin_unreachable();` which marks the path as unreachable.

**Comment by lcn2** [comment]
See issue #20
