### ISSUE TITLE
Dead code and enabling -Wextra

### ISSUE THREAD

**Issue by vog** [ioccc-src/mkiocccentry#2]
I propose to enable "-Wextra" in the Makefile.

Among others, this will reveal several places of dead code that can be safely removed, such as (produced by GCC 8.3.0):

```
mkiocccentry.c:5774:14: warning: comparison of unsigned expression < 0 is always false [-Wtype-limits]
      if (len < 0) {
              ^
```

Moreover, this will hint to unused parameters, such as (produced by GCC 8.3.0), see #6:

```
mkiocccentry.c:5071:57: warning: unused parameter ‘entry_num’ [-Wunused-parameter]
 get_author_info(struct info *infop, char *ioccc_id, int entry_num, struct author **author_set_p)
                                                     ~~~~^~~~~~~~~
```

**Comment by vog** [comment]
See also #4 and #5 which fix some more warnings.

**Comment by lcn2** [comment]
Thank you for the excellent suggestion of adding -Wextra, @vog !

The ae9cfef commit (https://github.com/ioccc-src/mkiocccentry/commit/ae9cfefe4420a4b5f0308d275ba9cf1acfb05e09) addresses this issue.
