### ISSUE TITLE
Bug: Zero length JSON documents should not allowed 

### ISSUE THREAD

**Issue by lcn2** [ioccc-src/mkiocccentry#206]
**Describe the bug**
The JSON parser appears to allow for an empty JSON document

**To Reproduce**
1. ./jparse -J1 -s ""

**Expected behavior**
The parser declares the JSON document to be invalid

**Screenshots**
```sh
./jparse -J1 -s ""
JSON DEBUG[1]: Calling parse_json_block(""):
Warning: parse_json_block: passed empty string
```

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: safari
 - Version: 12.3.1

**Additional context**
While the parser generates a warning, it should declare the document to be in error.

**Comment by xexyl** [comment]
This was done for the present in case it was desired to test more than one at the command line. I can make it an error though no problem.

**Comment by xexyl** [comment]
> This was done for the present in case it was desired to test more than one at the command line. I can make it an error though no problem.

NULL string was also a warning btw and there were others. It was temporary. I'll fix it now and push it with the other pull request and then I'll go do other things again.

**Comment by xexyl** [comment]
Now you get:

```sh
$ ./jparse -s ''
JSON DEBUG[1]: Calling parse_json_block(""):
FATAL[38]: parse_json_block: passed empty string
```

Does that work? If not I'll do more tomorrow.

**Comment by lcn2** [comment]
With commit f7f60f72af1c7d7c34bda20b377d8bff9c343d73

    Removed empty JSON document from grammar

    See https://github.com/ioccc-src/mkiocccentry/issues/206

    A careful reading of:

        https://www.ecma-international.org/wp-content/uploads/ECMA-404_2nd_edition_december_2017.pdf

    shows that empty JSON documents are not valid.

This bug appears to be resolved.

**Comment by xexyl** [comment]
> With commit [f7f60f7](https://github.com/ioccc-src/mkiocccentry/commit/f7f60f72af1c7d7c34bda20b377d8bff9c343d73)
> 
> ```
> Removed empty JSON document from grammar
> 
> See https://github.com/ioccc-src/mkiocccentry/issues/206
> 
> A careful reading of:
> 
>     https://www.ecma-international.org/wp-content/uploads/ECMA-404_2nd_edition_december_2017.pdf
> 
> shows that empty JSON documents are not valid.
> ```
> 
> This bug appears to be resolved.

Ah. You removed the empty part. There was a reason I added that that I cannot recall (I think it was recommended but I don't remember the details) but if it works it works - though my fix also makes it an error anyway so it never gets to that point.

**Comment by xexyl** [comment]
Unrelated I hope tomorrow to look into the discussion from yesterday more - about the scanning of bytes. Might look at other things too but unfortunately I'm done here for the day. Might be able to reply to some things though.
