### ISSUE TITLE
Bug: CHANGES.md is out of date

### ISSUE THREAD

**Issue by lcn2** [ioccc-src/mkiocccentry#207]
**Describe the bug**
The CHANGES.md needs to be updated to describe some of the more recent changes

**To Reproduce**
1. cat CHANGES.md

**Expected behavior**
A few of the more recent major changes should be listed.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: macOS
 - OS distribution: Apple
 - OS Version: 12.3.1
 - Compiler: n/a

**Additional context**
Perhaps it is time to call the current state "Release 0.2"?

Please put the NEW release notes ABOVE the previous release notes.

**Comment by xexyl** [comment]
I've not done this because I don't really know what to say. Also since the parser isn't done it didn't seem to be the right time.

If you think it's time to change it to 0.2 then I think it's time. I don't have any real thoughts on it.

What do you think should be added? I don't know. Maybe some of the conversion functions for json? Again I don't know.

**Comment by lcn2** [comment]
> I've not done this because I don't really know what to say. Also since the parser isn't done it didn't seem to be the right time.
> 
> If you think it's time to change it to 0.2 then I think it's time. I don't have any real thoughts on it.
> 
> What do you think should be added? I don't know. Maybe some of the conversion functions for json? Again I don't know.

The `CHANGES.md` could talk about the `./jparse` command, even it is it a work in progress.

There are a number of new executables since release 1.0.

The new man pages could be added.

**Comment by xexyl** [comment]
> > I've not done this because I don't really know what to say. Also since the parser isn't done it didn't seem to be the right time.
> > If you think it's time to change it to 0.2 then I think it's time. I don't have any real thoughts on it.
> > What do you think should be added? I don't know. Maybe some of the conversion functions for json? Again I don't know.
> 
> The `CHANGES.md` could talk about the `./jparse` command, even it is it a work in progress.
> 
> There are a number of new executables since release 1.0.
> 
> The new man pages could be added.

Okay I can do this. What release do you want me to say it is? 0.2 as you said? It might not happen until tomorrow though but I can do this anyway.

**Comment by lcn2** [comment]
> > > I've not done this because I don't really know what to say. Also since the parser isn't done it didn't seem to be the right time.
> > > If you think it's time to change it to 0.2 then I think it's time. I don't have any real thoughts on it.
> > > What do you think should be added? I don't know. Maybe some of the conversion functions for json? Again I don't know.
> > 
> > 
> > The `CHANGES.md` could talk about the `./jparse` command, even it is it a work in progress.
> > There are a number of new executables since release 1.0.
> > The new man pages could be added.
> 
> Okay I can do this. What release do you want me to say it is? 0.2 as you said? It might not happen until tomorrow though but I can do this anyway.

Thanks in advance @xexyl.

As long as the version number is > 0.1 and < 1.0, that would be fine.

Re recommend, as a general practice, to put the newer change versions on top / above the older change versions, BTW.

**Comment by xexyl** [comment]
> > > > I've not done this because I don't really know what to say. Also since the parser isn't done it didn't seem to be the right time.
> > > > If you think it's time to change it to 0.2 then I think it's time. I don't have any real thoughts on it.
> > > > What do you think should be added? I don't know. Maybe some of the conversion functions for json? Again I don't know.
> > > 
> > > 
> > > The `CHANGES.md` could talk about the `./jparse` command, even it is it a work in progress.
> > > There are a number of new executables since release 1.0.
> > > The new man pages could be added.
> > 
> > 
> > Okay I can do this. What release do you want me to say it is? 0.2 as you said? It might not happen until tomorrow though but I can do this anyway.
> 
> Thanks in advance @xexyl.
> 

Sure. 
> As long as the version number is > 0.1 and < 1.0, that would be fine.
> 

Okay. 
> Re recommend, as a general practice, to put the newer change versions on top / above the older change versions, BTW.

That’s what I would do yes. 

Going again. Might be able to reply to other comments later. Good day!

**Comment by xexyl** [comment]
Just fixed this.

I'm going to reply to another issue and then I'm having a lie down. No idea if I'll get anything else in today I'm afraid. I hope to but it's not looking good so far.

**Comment by lcn2** [comment]
Thanks @xexyl

**Comment by xexyl** [comment]
Welcome. I'm running the macOS update and then off until tomorrow. Good day!
