### ISSUE TITLE
Bug: jstrdecode objects to NUL bytes

### ISSUE THREAD

**Issue by lcn2** [ioccc-src/mkiocccentry#209]
**Describe the bug**
The jstrdecode tool exits non-zero when it fines a NUL byte.

**To Reproduce**
Steps to reproduce the behavior (adjust steps as needed):
0. echo -n '"NULXbyte"' | tr 'X' '\0' | hd
1. echo -n '"NULXbyte"' | tr 'X' '\0' | ./jstrencode
2. echo -n '"NULXbyte"' | tr 'X' '\0' | ./jstrencode | ./jstrdecode -n
3. echo -n '"NULXbyte"' | tr 'X' '\0' | ./jstrencode | ./jstrdecode -n 2>/dev/null | hd

**Expected behavior**
The jstrdecode should decode the JSON \"NUL\u0000byte\" string.

Step 2 should not exit non-zero.

Step 3 should output the same as step 0.

**Output**
$ echo -n '"NULXbyte"' | tr 'X' '\0' | ./jstrencode | ./jstrdecode
Warning: json_decode: found non-\-escaped char: 0x0a
Warning: jstrdecode_stdin: error while encoding stdin buffer

zsh: done       echo -n '"NULXbyte"' | tr 'X' '\0' | ./jstrencode |
zsh: exit 1     ./jstrdecode

**Environment (please complete the following information, or write n/a where not appliable):**
 - OS: macOS
 - OS distribution: Apple
 - OS Version: 12.31.1
 - Compiler: n/a
 - Compiler version: n/a
 - Bison version: n/a
 - Flex verson: n/a
 - Shell: zsh
 - Airspeed Velocity of an Unladen Swallow: 42

**Additional context**
While jstrdecode might warn about NUL bytes, it should not exit non-zero when it finds one.

**Comment by xexyl** [comment]
> Airspeed Velocity of an Unladen Swallow: 42

This is really funny. 

I will let you work on this one. Perhaps the functions that do this will be useful for the NUL bytes being allowed in json strings and maybe the regex doesn’t have to be updated? I was in a rush when I wrote that comment in the other issue. 

Maybe this with the scan bytes function is all that is needed? I guess we shall see. 

More from me tomorrow. If nothing else I can get to the changelog one. Let’s just hope I remember to do it!

Enjoy the rest of your day!

**Comment by lcn2** [comment]
> > Airspeed Velocity of an Unladen Swallow: 42
> 
> This is really funny.

We were working on the bug report template, trying to improve it ...

> BTW: That is why you saw several bug reports .. testing the template for other to eventually use.

... there is a balance between not asking for important information and asking for too much.

At one point, it became a bit too much, even though we could see cases where each question might be needed.

### OT:

We regret not answering:

* Airspeed Velocity of an Unladen Swallow: 1 yotta planck lengths per atto fortnight

Which happens to be close to the maximum [swallow speed](https://medium.com/human-nature-group/what-is-the-air-speed-velocity-of-an-unladen-swallow-4c17087bbf33) to within 1 part in 20.

See: [this tweet](https://twitter.com/landonnoll/status/1526323598951997441?s=20&t=IuL8XDs9iERQkhpDOkOc3w). :-)

**Comment by xexyl** [comment]
> > > Airspeed Velocity of an Unladen Swallow: 42
> > 
> > 
> > This is really funny.
> 
> We were working on the bug report template, trying to improve it ...
> 
> > BTW: That is why you saw several bug reports .. testing the template for other to eventually use.
> 

Ah. I wondered about this. Thank you for clarifying that. 

> ... there is a balance between not asking for important information and asking for too much.
> 

That’s very true. It can overwhelm the average user. But I think it’s fair to say that for the IOCCC most are not average and most probably know how to report bugs. Even so though there are bound to be some who might become overwhelmed or who don’t know how to do this. 

When I have reported issues I know what is relevant and what is not so I have indeed left out some information that is entirely irrelevant. But for the average user it’s good to have this. 

> At one point, it became a bit too much, even though we could see cases where each question might be needed.
> 

When did this happen here? Or you’re explaining how this has happened to you in one of your jobs in programming in your fascinating history?

> ### OT:
> We regret not answering:
> 
> * Airspeed Velocity of an Unladen Swallow: 1 yotta planck lengths per atto fortnight
> 
> Which happens to be close to the maximum [swallow speed](https://medium.com/human-nature-group/what-is-the-air-speed-velocity-of-an-unladen-swallow-4c17087bbf33) to within 1 part in 20.
> 

Ah. Well for me it was all a joke. I also immediately thought of (because of 42) H2G2. I figured you were not serious. I mean it’s clearly not important to the issue here!

> See: [this tweet](https://twitter.com/landonnoll/status/1526323598951997441?s=20&t=IuL8XDs9iERQkhpDOkOc3w). :-)

Interesting. Right now I have notifications for Twitter disabled as I noticed I have been rather irritable and I don’t want to react rashly or harshly to anyone (and I am sure that I actually have). I will enable them eventually. I suspect a large part of this is due to waking up so early every day for so long now. It’s really brutal. 

I will be going to sleep in maybe an hour or so. Hope you have a great night!

Ih btw: did you manage to see the Moon last night? I hope so! I was asleep so I unfortunately missed it. Anyway good night! You should hear more from me tomorrow in some form or another.

**Comment by lcn2** [comment]
###OT:

The moon 🌙 rose behind the [Mt Baker Volcano](https://en.wikipedia.org/wiki/Mount_Baker?wprov=sfti1) 🌋, which usually sets the record for the most snow ❄️ in a year 📅 and hold the world record for most snow in a year (29m). Which is to say that it is usually cloud ☁️ covered and thus even if it has been clear 🌌, the moon 🌝 would likely not had been until after the moon had risen up past the time of the total lunar eclipse. 

We could have moved, sure, but the rest of the clouds ⛅️ and rain would have said no, otherwise.

**Comment by xexyl** [comment]
> ###OT:
> 
> The moon 🌙 rose behind the [Mt Baker Volcano](https://en.wikipedia.org/wiki/Mount_Baker?wprov=sfti1) 🌋, which usually sets the record for the most snow ❄️ in a year 📅 and hold the world record for most snow in a year (29m). Which is to say that it is usually cloud ☁️ covered and thus even if it has been clear 🌌, the moon 🌝 would likely not had been until after the moon had risen up past the time of the total lunar eclipse.
> 
> We could have moved, sure, but the rest of the clouds ⛅️ and rain would have said no, otherwise.

I am really sorry to hear that you couldn’t see the total lunar eclipse. That’s a real shame. 

Maybe next time. 

Hope you’re having a nice sleep my friend! I will in a bit (I hope) start working on the repo and I will almost certainly start out with the changelog. 

The other things I hope to at least look at but we shall see.

**Comment by xexyl** [comment]
This is at the phone mind you: but I might address this one too depending on how it looks. Without looking at the actual code I think I know the solution here. 

I hope to be at the laptop soon. 

Hilarious aside: when I wrote ‘I hope to be at the laptop’ it actually suggested ‘hospital’. I would not have included the ‘the’ but even so it’s rather funny and ridiculous and perplexing that it would think that I would want to be in hospital!

**Comment by lcn2** [comment]
The original bug report was on error in that it did not make use of the `-n` option.  While this produced an error:

```sh
$ echo -n '"NULXbyte"' | tr 'X' '\0' | ./jstrencode | ./jstrdecode
Warning: json_decode: found non-\-escaped char: 0x0a
Warning: jstrdecode_stream: error while encoding stdin buffer

zsh: done       echo -n '"NULXbyte"' | tr 'X' '\0' | ./jstrencode |
zsh: exit 1     ./jstrdecode
```

> NOTE: The clue was that the non-\-escaped char was `0x0a` which is `\n`.

This does not:

```sh
$ echo -n '"NULXbyte"' | tr 'X' '\0' | ./jstrencode -n | ./jstrdecode -n
"NULbyte"%
```

Nevertheless some issues were discovered with `jstrencode` and `jsredecode` that needed to be fixed.

This has been completed with commit ce79116930aea8bdfce3eabee1610cae88e0a146

    Improve JSON encoding and decoding code

    The json_encode() and json_encode_str() functions now take
    an additional argument to indicate if the enclosing quotes
    should be skipped:

```c
    extern char * json_encode(char const *ptr, size_t len, size_t *retlen, bool skip_quote);
    extern char *json_encode_str(char const *str, size_t *retlen, bool skip_quote);
```

    Fixed and improved a number of comments in json.c conversion code
    to better clarify what certain conversion functions and args to
    those functions are doing.

    Added -Q flags to manage encoding quotes:

    usage: ./jstrencode [-h] [-v level] [-q] [-V] [-t] [-n] [-Q] [string ...]

            -h              print help message and exit 0
            -v level        set verbosity level: (def level: 0)
            -q              quiet mode: silence msg(), warn(), warnp() if -v 0 (def: not quiet)
            -V              print version string and exit 0
            -t              perform jencchk test on code JSON encode/decode functions
            -n              do not output newline after encode output (def: print final newline)
            -Q              ignore enclosing "'s (def: encode all bytes)

            [string ...]    encode strings on command line (def: read stdin)
                            NOTE: - means read from stdin

    jstrencode version: 0.5 2022-04-17

    usage: ./jstrdecode [-h] [-v level] [-q] [-V] [-t] [-n] [-Q] [string ...]

            -h              print help message and exit 0
            -v level        set verbosity level (def level: 0)
            -q              quiet mode: silence msg(), warn(), warnp() if -v 0 (def: not quiet)
            -V              print version string and exit 0
            -t              perform jencchk test on code JSON decode/encode functions
            -n              do not output newline after decode output
            -Q              enclose output in quotes (def: do not)

            [string ...]    decode strings on command line (def: read stdin)
                            NOTE: - means read from stdin

    jstrdecode version: 0.5 2022-04-17

    For example:

```sh
    $ echo -n '"NULXbyte"' | tr 'X' '\0' | ./jstrencode
    \"NUL\u0000byte\"

    $ echo -n '"NULXbyte"' | tr 'X' '\0' | hd
    0000000    22  4e  55  4c  00  62  79  74  65  22
    0000012

    $ echo -n '"NULXbyte"' | tr 'X' '\0' | ./jstrencode -n | ./jstrdecode -n | hd
    0000000    22  4e  55  4c  00  62  79  74  65  22
    0000012
```

    And with -Q:

```sh
    $ echo -n '"NULXbyte"' | tr 'X' '\0' | ./jstrencode -Q
    NUL\u0000byte

    $ echo -n '"NULXbyte"' | tr 'X' '\0' | ./jstrencode -n -Q | ./jstrdecode
    NULbyte

    $ echo -n '"NULXbyte"' | tr 'X' '\0' | ./jstrencode -n -Q | ./jstrdecode -n | hd
    0000000    4e  55  4c  00  62  79  74  65
    0000010

    $ echo -n '"NULXbyte"' | tr 'X' '\0' | ./jstrencode -n -Q | ./jstrdecode -Q
    "NULbyte"

    $ echo -n '"NULXbyte"' | tr 'X' '\0' | ./jstrencode -n -Q | ./jstrdecode -n -Q | hd
    0000000    22  4e  55  4c  00  62  79  74  65  22
    0000012
```

Observe that `NUL` bytes are being processed on JSON _strings_ and no errors or warning are being generated.  This is because the [ecma-404/](https://www.ecma-international.org/publications-and-standards/standards/ecma-404/) does not prohibit `NUL` bytes within JSON _strings_.

This these changes, this issue is now closed.

**Comment by xexyl** [comment]
Quickly at the phone before I get some sleep. 

> The original bug report was on error in that it did not make use of the `-n` option. While this produced an error:
> 
> ```shell
> $ echo -n '"NULXbyte"' | tr 'X' '\0' | ./jstrencode | ./jstrdecode
> Warning: json_decode: found non-\-escaped char: 0x0a
> Warning: jstrdecode_stream: error while encoding stdin buffer
> 
> zsh: done       echo -n '"NULXbyte"' | tr 'X' '\0' | ./jstrencode |
> zsh: exit 1     ./jstrdecode
> ```
> 
>  > NOTE: The clue was that the non--escaped char was `0x0a` which is `\n`.

*sigh* Yes I have seen that value for `\n` **many many times!**. But given that it also appeared to have a problem with NUL bytes I didn’t even think of that. 

But I am not sure. Perhaps I didn’t see that given that I had a really rotten night and I was awake even earlier. I am often finding myself unable to be sure that something actually happened. 

That’s what the sigh is about. 

> 
> This does not:
> 
> ```shell
> $ echo -n '"NULXbyte"' | tr 'X' '\0' | ./jstrencode -n | ./jstrdecode -n
> "NULbyte"%
> ```
> 

It must be that in my tiredness I misread this then. It might also be the way ut was worded (also due to exhaustion) and possibly conflating it with the other issue with strings not accepting NUL bytes. 

Thank you for clarifying. 

> Nevertheless some issues were discovered with `jstrencode` and `jsredecode` that needed to be fixed.
> 
> This has been completed with commit [ce79116](https://github.com/ioccc-src/mkiocccentry/commit/ce79116930aea8bdfce3eabee1610cae88e0a146)
> 
> ```
> Improve JSON encoding and decoding code
> 
> The json_encode() and json_encode_str() functions now take
> an additional argument to indicate if the enclosing quotes
> should be skipped:
> ```
> 
>  ```c
>     extern char * json_encode(char const *ptr, size_t len, size_t *retlen, bool skip_quote);
>     extern char *json_encode_str(char const *str, size_t *retlen, bool skip_quote);
> ```
> 

I wonder how this will affect the other issue. I guess I will find out tomorrow in the morning. 

>  ```
> Fixed and improved a number of comments in json.c conversion code
> to better clarify what certain conversion functions and args to
> those functions are doing.
> 
> Added -Q flags to manage encoding quotes:
> 
> usage: ./jstrencode [-h] [-v level] [-q] [-V] [-t] [-n] [-Q] [string ...]
> 
>         -h              print help message and exit 0
>         -v level        set verbosity level: (def level: 0)
>         -q              quiet mode: silence msg(), warn(), warnp() if -v 0 (def: not quiet)
>         -V              print version string and exit 0
>         -t              perform jencchk test on code JSON encode/decode functions
>         -n              do not output newline after encode output (def: print final newline)
>         -Q              ignore enclosing "'s (def: encode all bytes)
> 

This option intrigues me. I will have to play with it. 

>         [string ...]    encode strings on command line (def: read stdin)
>                         NOTE: - means read from stdin
> 
> jstrencode version: 0.5 2022-04-17
> 
> usage: ./jstrdecode [-h] [-v level] [-q] [-V] [-t] [-n] [-Q] [string ...]
> 
>         -h              print help message and exit 0
>         -v level        set verbosity level (def level: 0)
>         -q              quiet mode: silence msg(), warn(), warnp() if -v 0 (def: not quiet)
>         -V              print version string and exit 0
>         -t              perform jencchk test on code JSON decode/encode functions
>         -n              do not output newline after decode output
>         -Q              enclose output in quotes (def: do not)
> 
>         [string ...]    decode strings on command line (def: read stdin)
>                         NOTE: - means read from stdin
> 
> jstrdecode version: 0.5 2022-04-17
> 
> For example:
> ```
> 
>  ```shell
>     $ echo -n '"NULXbyte"' | tr 'X' '\0' | ./jstrencode
>     \"NUL\u0000byte\"
> 
>     $ echo -n '"NULXbyte"' | tr 'X' '\0' | hd
>     0000000    22  4e  55  4c  00  62  79  74  65  22
>     0000012
> 
>     $ echo -n '"NULXbyte"' | tr 'X' '\0' | ./jstrencode -n | ./jstrdecode -n | hd
>     0000000    22  4e  55  4c  00  62  79  74  65  22
>     0000012
> ```
> 
>  ```
> And with -Q:
> ```
> 
>  ```shell
>     $ echo -n '"NULXbyte"' | tr 'X' '\0' | ./jstrencode -Q
>     NUL\u0000byte
> 
>     $ echo -n '"NULXbyte"' | tr 'X' '\0' | ./jstrencode -n -Q | ./jstrdecode
>     NULbyte
> 
>     $ echo -n '"NULXbyte"' | tr 'X' '\0' | ./jstrencode -n -Q | ./jstrdecode -n | hd
>     0000000    4e  55  4c  00  62  79  74  65
>     0000010
> 
>     $ echo -n '"NULXbyte"' | tr 'X' '\0' | ./jstrencode -n -Q | ./jstrdecode -Q
>     "NULbyte"
> 
>     $ echo -n '"NULXbyte"' | tr 'X' '\0' | ./jstrencode -n -Q | ./jstrdecode -n -Q | hd
>     0000000    22  4e  55  4c  00  62  79  74  65  22
>     0000012
> ```
> 
> Observe that `NUL` bytes are being processed on JSON _strings_ and no errors or warning are being generated. This is because the [ecma-404/](https://www.ecma-international.org/publications-and-standards/standards/ecma-404/) does not prohibit `NUL` bytes within JSON _strings_.
> 

Right. As the other issue discusses. Well I guess you will be replying to that issue as well. 


> This these changes, this issue is now closed.

Out of curiosity did you update the man pages? If not would you like me to do it tomorrow?

Will be putting the phone down very soon as I am feeling sleepy and I could use time not being aware. 

Good night my friend!

**Comment by xexyl** [comment]
Quickly: another reason I got mixed up is the title of this issue. That’s a relief as well! Even so though I should have seen the hex `0xa` and put together it was newline. Maybe I even did. I really don’t remember now. 

And I see that you didn’t update the man pages. If you want me to update them tomorrow please let me know. 

Good night! Sleep well when you do.

**Comment by lcn2** [comment]
> Just updated the man pages for `-Q`...
> 
> 
> 
> That's all I plan on doing today I'm afraid but it's good that the other issue is resolved. I feel good about that!

Thanks for updating the man pages, @xexyl. We ran out of time after the initial commit.

**Comment by xexyl** [comment]
> > Just updated the man pages for `-Q`...
> > That's all I plan on doing today I'm afraid but it's good that the other issue is resolved. I feel good about that!
> 
> Thanks for updating the man pages, @xexyl. We ran out of time after the initial commit.

No worries. Hope you had a great sleep!
