### ISSUE TITLE
tcc: error: invalid option -- '--pedantic'

### ISSUE THREAD

**Issue by ilyakurdyukov** [ioccc-src/mkiocccentry#22]
`-pedantic` is a more standard option than `--pedantic`.

```
$ install/bin/tcc -O3 -g3 --pedantic
tcc: error: invalid option -- '--pedantic'
$ install/bin/tcc -O3 -g3 -pedantic
tcc: error: no input files
```

After changing "--pedantic" to "-pedantic", TCC successfully compiled the mkiocccentry.

**Comment by lcn2** [comment]
Thank you @ilyakurdyukov .. fixed in 0636f6b1ef4bbb13d3dfdcd04bb42c5ee3776ba4
