### ISSUE TITLE
Enhancement: Write a test suite for `txzchk`

### ISSUE THREAD

**Issue by xexyl** [ioccc-src/mkiocccentry#235]
I just wrote the following to help start this but I also have some additional thoughts to add that might be considered to make it easier to test the tool. It would require that I make some changes to the tool (and possibly `fnamchk`) but I'm okay with that (though maybe you would want to do the changes to `fnamchk`):

--

# `test_txzchk`: text files for a test suite for `txzchk`

The subdirectories in this directory have text files for a test suite for the
txzchk tool.

The `good/` subdirectory has files that `txzchk` MUST report as valid.

The `bad/` subdirectory has files that `txzchk` MUST report as invalid.

The files MUST end with the extension `.txt` and the filename MUST follow the
rules of the `fnamchk` tool.

The typical format is that which would be generated from `tar -tJvf` but
importantly these files are **NOT** tarballs: they are text files that would
have the output of the tar command. This is to make it much easier to add test
cases and it also prevents having the need to have tarballs in the repo (as well
as constructing said tarballs with invalid input that might be submitted due to
abuse).

Here's an example good file:

```
drwxr-xr-x  0 501    20          0 Jun  3 05:50 test-0/
-rw-r--r--  0 501    20       1854 Jun  3 05:50 test-0/Makefile
-rw-r--r--  0 501    20          4 Jun  3 05:50 test-0/extra2
-rw-r--r--  0 501    20          0 Jun  3 05:50 test-0/prog.c
-rw-r--r--  0 501    20       2793 Jun  3 05:50 test-0/.author.json
-rw-r--r--  0 501    20       3715 Jun  3 05:50 test-0/remarks.md
-rw-r--r--  0 501    20       1429 Jun  3 05:50 test-0/.info.json
-rw-r--r--  0 501    20          4 Jun  3 05:50 test-0/extra1
```

Let's say the file is called `entry.test-0.1654260612.txt`. We can run the
following command to test `txzchk` on it:

```sh
$ ./txzchk -T -E txt entry.test-0.1654260612.txt
```

This will report on whether or not the tarball is valid. If you want to not see
any output at all and only check the exit status one can do:

```sh
$ ./txzchk -T -E txt entry.test-0.1654260612.txt 2>&1 >/dev/null || echo invalid
```

This will not show anything as the tarball is actually valid.

**Comment by xexyl** [comment]
There are some things to consider though. I'll start out with the most important one: `fnamchk` and how `txzchk` uses it.

Not only does `txzchk` call `fnamchk` to verify that the tarball is properly named but it also uses it to retrieve what the valid directory name in the tarball is supposed to be. This means that if `fnamchk` fails we have a problem with the tarball but for testing purposes this makes it harder to set up a file because `fnamchk` also imposes other restrictions on the filename.

For example we can't even have the extension be `txz.txt` because:

```sh
$ ./txzchk -T -E txz.txt ./entry.test-0.1654260612.txz.txt 
Welcome to txzchk version: 0.10 2022-03-15

Performing sanity checks on your environment ...
... environment looks OK

Performing checks on tarball ...
ERROR[21]: main: final fourth '.' separated token filename extension: txz != txz.txt: ./entry.test-0.1654260612.txz.txt
Warning: txzchk: ./entry.test-0.1654260612.txz.txt: ./fnamchk ./entry.test-0.1654260612.txz.txt failed with exit code: 21: errno[0]: Undefined error: 0
txzchk: ./entry.test-0.1654260612.txz.txt size of 506 bytes OK
drwxr-xr-x  0 501    20          0 Jun  3 05:50 test-0/
-rw-r--r--  0 501    20       1854 Jun  3 05:50 test-0/Makefile
-rw-r--r--  0 501    20          4 Jun  3 05:50 test-0/extra2
-rw-r--r--  0 501    20          0 Jun  3 05:50 test-0/prog.c
-rw-r--r--  0 501    20       2793 Jun  3 05:50 test-0/.author.json
-rw-r--r--  0 501    20       3715 Jun  3 05:50 test-0/remarks.md
-rw-r--r--  0 501    20       1429 Jun  3 05:50 test-0/.info.json
-rw-r--r--  0 501    20          4 Jun  3 05:50 test-0/extra1
txzchk: ./entry.test-0.1654260612.txz.txt total size of files 9799 rounded up to 1024 multiple: 10240 OK
Warning: txzchk: ./entry.test-0.1654260612.txz.txt: not all files in correct directory
Warning: txzchk: ./entry.test-0.1654260612.txz.txt: found 2 issues
```

As you can see it doesn't even get the right directory name because `fnamchk` failed. What can be done about this? `txzchk` could theoretically do some extraction or maybe ignore the directory name (probably after a new flag was added to indicate that it's a test mode ... maybe `-T` itself would imply it?) but is this right? I don't know. What I do know is that it makes `txzchk` report issues because it can't get the right directory (even though the file name would suggest that the contents does have the right directory) and so reports also that not all files are in the correct directory.

What's the `undefined error: 0` from exit code 21? Looking at the output it appears that I used `warnp` but I should have used `warn` when `fnamchk` fails. That can be fixed at another time.

**Comment by xexyl** [comment]
Other errors from `fnamchk` will also cause a problem. So something has to be decided on what `txzchk` should do in the case of test mode to avoid this problem.

An important point is with the way `fnamchk` is now it's difficult to contrive many files as there aren't many possible combinations of valid filenames. What can be done about this?

These are things I did not think of when I had the idea of a test suite - though really the `-T` and `-E` options were not originally meant for automation but rather for testing new formats and issues that had to be detected by the tool.

**Comment by lcn2** [comment]
> I just wrote the following to help start this but I also have some additional thoughts to add that might be considered to make it easier to test the tool. It would require that I make some changes to the tool (and possibly `fnamchk`) but I'm okay with that (though maybe you would want to do the changes to `fnamchk`):
> 
> --
> 
> # `test_txzchk`: text files for a test suite for `txzchk`
> The subdirectories in this directory have text files for a test suite for the txzchk tool.
> 
> The `good/` subdirectory has files that `txzchk` MUST report as valid.
> 
> The `bad/` subdirectory has files that `txzchk` MUST report as invalid.
> 
> The files MUST end with the extension `.txt` and the filename MUST follow the rules of the `fnamchk` tool.
> 
> The typical format is that which would be generated from `tar -tJvf` but importantly these files are **NOT** tarballs: they are text files that would have the output of the tar command. This is to make it much easier to add test cases and it also prevents having the need to have tarballs in the repo (as well as constructing said tarballs with invalid input that might be submitted due to abuse).
> 
> Here's an example good file:
> 
> ```
> drwxr-xr-x  0 501    20          0 Jun  3 05:50 test-0/
> -rw-r--r--  0 501    20       1854 Jun  3 05:50 test-0/Makefile
> -rw-r--r--  0 501    20          4 Jun  3 05:50 test-0/extra2
> -rw-r--r--  0 501    20          0 Jun  3 05:50 test-0/prog.c
> -rw-r--r--  0 501    20       2793 Jun  3 05:50 test-0/.author.json
> -rw-r--r--  0 501    20       3715 Jun  3 05:50 test-0/remarks.md
> -rw-r--r--  0 501    20       1429 Jun  3 05:50 test-0/.info.json
> -rw-r--r--  0 501    20          4 Jun  3 05:50 test-0/extra1
> ```
> 
> Let's say the file is called `entry.test-0.1654260612.txt`. We can run the following command to test `txzchk` on it:
> 
> ```shell
> $ ./txzchk -T -E txt entry.test-0.1654260612.txt
> ```
> 
> This will report on whether or not the tarball is valid. If you want to not see any output at all and only check the exit status one can do:
> 
> ```shell
> $ ./txzchk -T -E txt entry.test-0.1654260612.txt 2>&1 >/dev/null || echo invalid
> ```
> 
> This will not show anything as the tarball is actually valid.

This looks like a good design, @xexyl

**Comment by lcn2** [comment]
The `test_txzchk` too should probably take optional `-F fnamchk` so that optional tool locations can be tested.  And then when `test_txzchk` calls `txzchk` it will do that with an explicit path.

**Comment by xexyl** [comment]
> > I just wrote the following to help start this but I also have some additional thoughts to add that might be considered to make it easier to test the tool. It would require that I make some changes to the tool (and possibly `fnamchk`) but I'm okay with that (though maybe you would want to do the changes to `fnamchk`):
> > --
> > # `test_txzchk`: text files for a test suite for `txzchk`
> > The subdirectories in this directory have text files for a test suite for the txzchk tool.
> > The `good/` subdirectory has files that `txzchk` MUST report as valid.
> > The `bad/` subdirectory has files that `txzchk` MUST report as invalid.
> > The files MUST end with the extension `.txt` and the filename MUST follow the rules of the `fnamchk` tool.
> > The typical format is that which would be generated from `tar -tJvf` but importantly these files are **NOT** tarballs: they are text files that would have the output of the tar command. This is to make it much easier to add test cases and it also prevents having the need to have tarballs in the repo (as well as constructing said tarballs with invalid input that might be submitted due to abuse).
> > Here's an example good file:
> > ```
> > drwxr-xr-x  0 501    20          0 Jun  3 05:50 test-0/
> > -rw-r--r--  0 501    20       1854 Jun  3 05:50 test-0/Makefile
> > -rw-r--r--  0 501    20          4 Jun  3 05:50 test-0/extra2
> > -rw-r--r--  0 501    20          0 Jun  3 05:50 test-0/prog.c
> > -rw-r--r--  0 501    20       2793 Jun  3 05:50 test-0/.author.json
> > -rw-r--r--  0 501    20       3715 Jun  3 05:50 test-0/remarks.md
> > -rw-r--r--  0 501    20       1429 Jun  3 05:50 test-0/.info.json
> > -rw-r--r--  0 501    20          4 Jun  3 05:50 test-0/extra1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Let's say the file is called `entry.test-0.1654260612.txt`. We can run the following command to test `txzchk` on it:
> > ```shell
> > $ ./txzchk -T -E txt entry.test-0.1654260612.txt
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This will report on whether or not the tarball is valid. If you want to not see any output at all and only check the exit status one can do:
> > ```shell
> > $ ./txzchk -T -E txt entry.test-0.1654260612.txt 2>&1 >/dev/null || echo invalid
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This will not show anything as the tarball is actually valid.
> 
> This looks like a good design, @xexyl

The question is what to do about `fnamchk` as I described it though? Not having a successful invocation of it causes issues. Maybe though you can think of a good idea to have many different files though? Perhaps it's just a matter of incremental timestamps? For example have one file as the first name and then just add a second for the second file etc.?

**Comment by lcn2** [comment]
> As you can see it doesn't even get the right directory name because fnamchk failed. What can be done about this? txzchk could theoretically do some extraction or maybe ignore the directory name (probably after a new flag was added to indicate that it's a test mode ... maybe -T itself would imply it?) but is this right? I don't know. What I do know is that it makes txzchk report issues because it can't get the right directory (even though the file name would suggest that the contents does have the right directory) and so reports also that not all files are in the correct directory.

Probably the use of `-T` should imply that use of `fnamchk` should be bypassed as there are no names to check in that case?

Perhaps having one **normal looking** **simple hello world** tarball for `test_txzchk` to check at the very beginning might not be a bad idea?  While it would require one to ship a compressed tarball inside the test suite sub-directory somewhere, one little compressed tarball would not be that bad: especially if it was a normal tarball with normal looking files.  Such a compressed tarball could be even a UUID based entry - something that could service as an example of a good submission file?

So perhaps the **1st** call that `test_txzchk` would be a **normal** looking run on a normal looking `/txzchk` run (where it in turn can call `fnamchk`) with normal compressed tarball file and without `-T`.  Then all of there other calls that `test_txzchk` calls to `txzchk` could use the `-T` option.

**Comment by lcn2** [comment]
> > > ## I just wrote the following to help start this but I also have some additional thoughts to add that might be considered to make it easier to test the tool. It would require that I make some changes to the tool (and possibly `fnamchk`) but I'm okay with that (though maybe you would want to do the changes to `fnamchk`):
> > > # `test_txzchk`: text files for a test suite for `txzchk`
> > > The subdirectories in this directory have text files for a test suite for the txzchk tool.
> > > The `good/` subdirectory has files that `txzchk` MUST report as valid.
> > > The `bad/` subdirectory has files that `txzchk` MUST report as invalid.
> > > The files MUST end with the extension `.txt` and the filename MUST follow the rules of the `fnamchk` tool.
> > > The typical format is that which would be generated from `tar -tJvf` but importantly these files are **NOT** tarballs: they are text files that would have the output of the tar command. This is to make it much easier to add test cases and it also prevents having the need to have tarballs in the repo (as well as constructing said tarballs with invalid input that might be submitted due to abuse).
> > > Here's an example good file:
> > > ```
> > > drwxr-xr-x  0 501    20          0 Jun  3 05:50 test-0/
> > > -rw-r--r--  0 501    20       1854 Jun  3 05:50 test-0/Makefile
> > > -rw-r--r--  0 501    20          4 Jun  3 05:50 test-0/extra2
> > > -rw-r--r--  0 501    20          0 Jun  3 05:50 test-0/prog.c
> > > -rw-r--r--  0 501    20       2793 Jun  3 05:50 test-0/.author.json
> > > -rw-r--r--  0 501    20       3715 Jun  3 05:50 test-0/remarks.md
> > > -rw-r--r--  0 501    20       1429 Jun  3 05:50 test-0/.info.json
> > > -rw-r--r--  0 501    20          4 Jun  3 05:50 test-0/extra1
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Let's say the file is called `entry.test-0.1654260612.txt`. We can run the following command to test `txzchk` on it:
> > > ```shell
> > > $ ./txzchk -T -E txt entry.test-0.1654260612.txt
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > This will report on whether or not the tarball is valid. If you want to not see any output at all and only check the exit status one can do:
> > > ```shell
> > > $ ./txzchk -T -E txt entry.test-0.1654260612.txt 2>&1 >/dev/null || echo invalid
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > This will not show anything as the tarball is actually valid.
> > 
> > 
> > This looks like a good design, @xexyl
> 
> The question is what to do about `fnamchk` as I described it though? Not having a successful invocation of it causes issues. Maybe though you can think of a good idea to have many different files though? Perhaps it's just a matter of incremental timestamps? For example have one file as the first name and then just add a second for the second file etc.?

See [comment 1146187020](https://github.com/ioccc-src/mkiocccentry/issues/235#issuecomment-1146187020).

**Comment by lcn2** [comment]
> > The `test_txzchk` too should probably take optional `-F fnamchk` so that optional tool locations can be tested. And then when `test_txzchk` calls `txzchk` it will do that with an explicit path.
> 
> And `-T` for `tar` too yes. Good call on `fnamchk`.
> 
> I did start a script but it wasn't working right for me. I based it on `test_json.sh` but I don't think that's the only starting point it needs. Not sure. That script is more complicated and has many other checks so it might be the wrong one to use. It does however have the good and bad checks built in which is why I chose it. Maybe it'd be better to do something new.
> 
> I really don't know.

You can use a copy of that other test code as concept and modify it to suite your purposes.

**Comment by xexyl** [comment]
> > As you can see it doesn't even get the right directory name because fnamchk failed. What can be done about this? txzchk could theoretically do some extraction or maybe ignore the directory name (probably after a new flag was added to indicate that it's a test mode ... maybe -T itself would imply it?) but is this right? I don't know. What I do know is that it makes txzchk report issues because it can't get the right directory (even though the file name would suggest that the contents does have the right directory) and so reports also that not all files are in the correct directory.
> 
> Probably the use of `-T` should imply that use of `fnamchk` should be bypassed as there are no names to check in that case?

Actually that is how it is in `txzchk`: call it an option letter for both 'test' and 'text file'. I meant to say `-t`.

> 
> Perhaps having one **normal looking** **simple hello world** tarball for `test_txzchk` to check at the very beginning might not be a bad idea? While it would require one to ship a compressed tarball inside the test suite sub-directory somewhere, one little compressed tarball would not be that bad: especially if it was a normal tarball with normal looking files. Such a compressed tarball could be even a UUID based entry - something that could service as an example of a good submission file?
> 

That sounds like a good idea yes.

> So perhaps the **1st** call that `test_txzchk` would be a **normal** looking run on a normal looking `/txzchk` run (where it in turn can call `fnamchk`) with normal compressed tarball file and without `-T`. Then all of there other calls that `test_txzchk` calls to `txzchk` could use the `-T` option.

Makes sense.

**Comment by xexyl** [comment]
> > > The `test_txzchk` too should probably take optional `-F fnamchk` so that optional tool locations can be tested. And then when `test_txzchk` calls `txzchk` it will do that with an explicit path.
> > 
> > 
> > And `-T` for `tar` too yes. Good call on `fnamchk`.
> > I did start a script but it wasn't working right for me. I based it on `test_json.sh` but I don't think that's the only starting point it needs. Not sure. That script is more complicated and has many other checks so it might be the wrong one to use. It does however have the good and bad checks built in which is why I chose it. Maybe it'd be better to do something new.
> > I really don't know.
> 
> You can use a copy of that other test code as concept and modify it to suite your purposes.

It wasn't really working for me but it might be the wrong mindset at the time. Been awake since stupid o'clock (in this case 1 or so) and so I'm easily frustrated.

**Comment by lcn2** [comment]
> > > > The `test_txzchk` too should probably take optional `-F fnamchk` so that optional tool locations can be tested. And then when `test_txzchk` calls `txzchk` it will do that with an explicit path.
> > > 
> > > 
> > > And `-T` for `tar` too yes. Good call on `fnamchk`.
> > > I did start a script but it wasn't working right for me. I based it on `test_json.sh` but I don't think that's the only starting point it needs. Not sure. That script is more complicated and has many other checks so it might be the wrong one to use. It does however have the good and bad checks built in which is why I chose it. Maybe it'd be better to do something new.
> > > I really don't know.
> > 
> > 
> > You can use a copy of that other test code as concept and modify it to suite your purposes.
> 
> It wasn't really working for me but it might be the wrong mindset at the time. Been awake since stupid o'clock (in this case 1 or so) and so I'm easily frustrated.

It sounds like you may have started writing code too soon.  Take a break / rest and let your ideas simmer on the "stove if good ideas".  Considering tossing out your first attempt, think about it some more and then try writing it.

**Comment by xexyl** [comment]
> > > > > The `test_txzchk` too should probably take optional `-F fnamchk` so that optional tool locations can be tested. And then when `test_txzchk` calls `txzchk` it will do that with an explicit path.
> > > > 
> > > > 
> > > > And `-T` for `tar` too yes. Good call on `fnamchk`.
> > > > I did start a script but it wasn't working right for me. I based it on `test_json.sh` but I don't think that's the only starting point it needs. Not sure. That script is more complicated and has many other checks so it might be the wrong one to use. It does however have the good and bad checks built in which is why I chose it. Maybe it'd be better to do something new.
> > > > I really don't know.
> > > 
> > > 
> > > You can use a copy of that other test code as concept and modify it to suite your purposes.
> > 
> > 
> > It wasn't really working for me but it might be the wrong mindset at the time. Been awake since stupid o'clock (in this case 1 or so) and so I'm easily frustrated.
> 
> It sounds like you may have started writing code too soon. Take a break / rest and let your ideas simmer on the "stove if good ideas". Considering tossing out your first attempt, think about it some more and then try writing it.

Possibly too soon. But really I wasn't writing it at all - at that point I was just modifying a copy of the other script. But yes I will worry about it another time anyway. I probably won't even consider it until after the `dbg` related things are done and (depending on the progress thereof) the json parser (and if that gets done then of course `jinfochk` and `jauthchk`). 

We'll see.

**Comment by xexyl** [comment]
Anyway I'll be doing something else the rest of the day. Good luck with the issue you have to deal with! We can discuss this one - and the others - another day.

**Comment by xexyl** [comment]
It seems I just needed more sleep and some motivation! See the commit.

Might do more with `dbg` later on .. not sure. Feel free to add test files to `test_txzchk`! Hope you're having a nice sleep and I hope you're feeling better too!

**Comment by xexyl** [comment]
Just updated the Makefile for this with commit https://github.com/ioccc-src/mkiocccentry/pull/237/commits/dd8eaef2039a458473c9e766f17c75a6d83db347:

    Update Makefile for txzchk_test.sh
    
    Added script to SH_FILES.
    
    Added TXZCHK_LOG variable with value txzchk_test.log.
    
    Make rule prep_clobber removes TXZCHK_LOG.

Something I forgot to ask: would you please add this to `ioccc_test.sh` ? Thank you!

**Comment by lcn2** [comment]
While the basis for the test suite was added with pull request #237:

TODO for this issue: Add more tar `foo.txt` listing files.

**Comment by xexyl** [comment]
> While the basis for the test suite was added with pull request #237:
> 
> TODO for this issue: Add more tar `foo.txt` listing files.

As I think I said elsewhere I should have several files to add. I believe I will have to update the timestamp but I know I have several files somewhere. I have had to fork the repo several times but I should have them in backup directories. 

I know one has a negative file size. We could also go back to the original issue where you uploaded several different tarballs. I might have those as well but they can be easily obtained and converted to text files. 

Hopefully I can do that tomorrow.

**Comment by lcn2** [comment]
> Just updated the Makefile for this with commit [dd8eaef](https://github.com/ioccc-src/mkiocccentry/commit/dd8eaef2039a458473c9e766f17c75a6d83db347):
> 
> ```
> Update Makefile for txzchk_test.sh
> 
> Added script to SH_FILES.
> 
> Added TXZCHK_LOG variable with value txzchk_test.log.
> 
> Make rule prep_clobber removes TXZCHK_LOG.
> ```
> 
> Something I forgot to ask: would you please add this to `ioccc_test.sh` ? Thank you!

See commit 9acde517ee573f8b2793e5d90981b019754ce128

    Added txzchk_test.sh to ioccc_test.sh

    Removing `txzchk_test.log` during `make clobber`.
    Also `.gitignore` ignores `txzchk_test.log`.

    Added `txzchk_test.sh` as a dependency for
    the `make test` rule.

**Comment by xexyl** [comment]
As per your request I'm closing this now. We can still add cases but the script itself works to add tests. I'll address the comments above soon.

**Comment by xexyl** [comment]
> > Just updated the Makefile for this with commit [dd8eaef](https://github.com/ioccc-src/mkiocccentry/commit/dd8eaef2039a458473c9e766f17c75a6d83db347):
> > ```
> > Update Makefile for txzchk_test.sh
> > 
> > Added script to SH_FILES.
> > 
> > Added TXZCHK_LOG variable with value txzchk_test.log.
> > 
> > Make rule prep_clobber removes TXZCHK_LOG.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Something I forgot to ask: would you please add this to `ioccc_test.sh` ? Thank you!
> 
> See commit [9acde51](https://github.com/ioccc-src/mkiocccentry/commit/9acde517ee573f8b2793e5d90981b019754ce128)
> 
> ```
> Added txzchk_test.sh to ioccc_test.sh
> 
> Removing `txzchk_test.log` during `make clobber`.
> Also `.gitignore` ignores `txzchk_test.log`.
> 
> Added `txzchk_test.sh` as a dependency for
> the `make test` rule.
> ```

Not sure if I thanked you for this but if not thank you. I think I did in the other thread but maybe not.

**Comment by lcn2** [comment]
> As per your request I'm closing this now. We can still add cases but the script itself works to add tests. I'll address the comments above soon.

Thanks @xexyl
