### ISSUE TITLE
Bug: json_test.sh always exits 0 even when EXIT_CODE is 1

### ISSUE THREAD

**Issue by xexyl** [ioccc-src/mkiocccentry#238]
**Describe the bug**

If any test fails to pass correctly then `EXIT_CODE=1`. This variable is used in the final line of the script:

```sh
exit "$EXIT_CODE"

```

But even though jauthchk tests will fail (some jinfochk tests might also but it's more complete as it stands than jauthchk) it will always return 0 which. I added some calls to `set -x` and `set +x` to show this. Since there are many files to go through I'm only including one in the output as well as the final output.

**To Reproduce**

Just run the script.

**Expected behavior**

I think we both know the answer to this :)

**Output**

After adding `set -x` here's the output of an example bad test and the final exit:

```
+ echo './json_test.sh: Warning: in run_test: FAIL: ./jauthchk -v 0 ./test_JSON/author.json/bad/author.missing-line.55.json exit code: 0 == 0'
+ tee -a ./json_test.log
./json_test.sh: Warning: in run_test: FAIL: ./jauthchk -v 0 ./test_JSON/author.json/bad/author.missing-line.55.json exit code: 0 == 0
+ echo './json_test.sh: Warning: the above mentioned test PASSED when it should have FAILED'
+ tee -a ./json_test.log
./json_test.sh: Warning: the above mentioned test PASSED when it should have FAILED
+ [[ 3 -lt 3 ]]
+ echo './json_test.sh: Warning: for more details try: ./jauthchk -v 3 -- ./test_JSON/author.json/bad/author.missing-line.55.json'
+ tee -a ./json_test.log
./json_test.sh: Warning: for more details try: ./jauthchk -v 3 -- ./test_JSON/author.json/bad/author.missing-line.55.json
+ echo
+ tee -a ./json_test.log

+ EXIT_CODE=1
+ set +x
+ [[ 3 -ge 1 ]]
+ [[ 0 -eq 0 ]]
+ echo './json_test.sh: debug[1]: all tests PASSED'
./json_test.sh: debug[1]: all tests PASSED
+ exit 0
```

I'm not sure how this happens as `EXIT_CODE` is what exit refers to and it's 1. As you can see it even compares to 0. I don't see any possible place it is set back to 0. This bug is also in the new txzchk test suite as the script is heavily based on `json_test.sh`!

**Environment (please complete the following information, or write n/a where not appliable):**

If it matters to you really: it's under the most recent macOS and bash 5.1.16(1)-release (aarch64-apple-darwin21.1.0). I don't think it's relevant though. Pretty sure it's on other systems as well. I can check later - have something else I need to do now.

Btw: I just updated the bug template as there were some typos. Pushed that. I don't know if that's what it takes to make it so that it's fixed here but in case not you might want to take a look at the changes.

**Comment by lcn2** [comment]
NOTE: "... the `txzchk_test.sh` has the same exit code issue as the `json_test.sh` script."

TODO: Fix both `txzchk_test.sh` AND `json_test.sh`.

**Comment by xexyl** [comment]
> NOTE: "... the `txzchk_test.sh` has the same exit code issue as the `json_test.sh` script."
> 
> TODO: Fix both `txzchk_test.sh` AND `json_test.sh`.

Correct. Because I based the one on the other. It's strange for sure. I'm curious what it is. I decided each time there were other things to work on so I let it be. But then I thought of it today when working on this issue.

Anyway good day! Heading off to get some food.

**Comment by lcn2** [comment]
The bug is that `EXIT_CODE` was being set in a sub-shell and so the parent shell never say the non-zero `EXIT_CODE` file.

We have a fix that is being applied to `txzchk_test.sh` and `json_test.sh`.

**Comment by xexyl** [comment]
> The bug is that `EXIT_CODE` was being set in a sub-shell and so the parent shell never say the non-zero `EXIT_CODE` file.
> 

That makes complete sense though I don’t recall seeing a sub-shell at all. Interesting. I will have to take a look tomorrow. 

> We have a fix that is being applied to `txzchk_test.sh` and `json_test.sh`.

Thank you! And with that I will be putting the phone down. I will reply to the rest of the comment in the txzchk test suite pull request I made today in the morning most likely. 

It’s time I get some sleep. Good night! I hope you are feeling better. 

Oh I just remembered that you answered my question on the other pull request that you referred to Ivan. I will look at that tomorrow. 

Good night my friend! Sleep tight when you do! Hope you’re feeling better btw?

**Comment by lcn2** [comment]
> Good night my friend! Sleep tight when you do! Hope you’re feeling better btw?

Improving .. I keep needing to remind myself of your apt joke.  Better but not at par.

Thanks for asking @xexyl

**Comment by xexyl** [comment]
> > Good night my friend! Sleep tight when you do! Hope you’re feeling better btw?
> 
> Improving .. I keep needing to remind myself of your apt joke. Better but not at par.
> 

Happy you appreciate my jokes but which one do you refer to? The imperfect one?

Good you’re doing some better!


> Thanks for asking @xexyl

Of course! I care a lot! Wishing you the best. 

Putting phone down now. Good night! More from me in the morning.

**Comment by lcn2** [comment]
The fix testing well, but we have noticed that `build.log` turns up missing after `make prep` and `make release`.   This is not a consequence of the fix, but rather some other bug.

We are going to fix the missing `build.log` because we would like to see, as part of the testing, the new diagnostics going into that file.

**Comment by lcn2** [comment]
> Happy you appreciate my jokes but which one do you refer to? The imperfect one?

Yes :)

**Comment by lcn2** [comment]
> The fix testing well, but we have noticed that `build.log` turns up missing after `make prep` and `make release`. This is not a consequence of the fix, but rather some other bug.
> 
> We are going to fix the missing `build.log` because we would like to see, as part of the testing, the new diagnostics going into that file.

Found the problem and fixed it.

**Comment by lcn2** [comment]
For some reason, the perl environment has _gone boing_, so the `seqcexit` tool cannot execute.  That's a system problem on my end, but it is also blocking my ability to successfully run `make release`.

**Comment by lcn2** [comment]
It turns out that `prep.sh` has a similar issue.

**Comment by lcn2** [comment]
This issue (and related **yak shaves** 🤓) have been fixed by commit b1bad1770aa065dfa1632091ab40292c4a64e9a2

    Fixed issue #238

    Issue #238:

        Bug: json_test.sh always exits 0 even when EXIT_CODE is 1

    that also impacted `txzchk_test.sh` has been fixed.

    The problem was that `EXIT_CODE` was being set in a sub-shell
    and so the parent shell never saw the non-zero `EXIT_CODE` value.

    While there are may work-a-rounds for this issue, we chose
    to use a temporary file to hold sub-shell exit codes.
    The parent shell creates the temporary exit code file,
    the sub-shell writes a numeric value into that same
    temporary exit code file, so that in the end, the parent
    shell can inspect the temporary exit code file and
    exit accordingly.

    Some level of care is taken in using temporary exit code files.
    A mktemp template filename is used that includes a common prefix.
    The value in the temporary exit code file must be an integer
    in the range [0,255].  The final EXIT_CODE, if 0, is replaced
    by the validated exit code read from the temporary exit code file.
    In the unlikely event where the temporary exit code file contains 0,
    the final EXIT_CODE is not changed.

    Continuing the **Yak Shave**, use of the `mktemp` command was
    improved in other shell scripts that use it, namely `run_bison.sh`
    and `run_flex.sh`.  They too use a mktemp template filename.

    Temporary files created by `json_test.sh` and `txzchk_test.sh`
    are of the form: `.exit_code.__script_basename__.XXXXXXXXXX*`
    and the temporary files created by `run_bison.sh` are of the
    form `.sorry.bison.XXXXXXXXXX` and temporary files created by
    ``run_flex.sh` are of the form `.sorry.flex.XXXXXXXXXX`.

    All temporary exit code files are cleaned up by the `make prep_clobber`
    rule.  They are also ignored in the `.gitignore` file.

    Fixed a problem where the `build.log` file was being
    removed during the `make prep` and `make release` rules.

    A non-zero exit of `prep.sh` during `make prep` and `make release`
    will be reported by the Makefile.  In particular, if `prep.sh`
    exited non-zero, then a Warning is issued by the make file.  In the
    case of `make prep`, the make command will not exit.  In the case
    of `make release`, the make command exit non-zero (abort) after
    printing information such as the `prep.sh` exit code and a message
    about above details were saved in the build.log file.

**Comment by xexyl** [comment]
> This issue (and related **yak shaves** 🤓) have been fixed by commit [b1bad17](https://github.com/ioccc-src/mkiocccentry/commit/b1bad1770aa065dfa1632091ab40292c4a64e9a2)
> 
> ```
> Fixed issue #238
> 
> Issue #238:
> 
>     Bug: json_test.sh always exits 0 even when EXIT_CODE is 1
> 
> that also impacted `txzchk_test.sh` has been fixed.
> 
> The problem was that `EXIT_CODE` was being set in a sub-shell
> and so the parent shell never saw the non-zero `EXIT_CODE` value.
> 
> While there are may work-a-rounds for this issue, we chose
> to use a temporary file to hold sub-shell exit codes.
> The parent shell creates the temporary exit code file,
> the sub-shell writes a numeric value into that same
> temporary exit code file, so that in the end, the parent
> shell can inspect the temporary exit code file and
> exit accordingly.
> 
> Some level of care is taken in using temporary exit code files.
> A mktemp template filename is used that includes a common prefix.
> The value in the temporary exit code file must be an integer
> in the range [0,255].  The final EXIT_CODE, if 0, is replaced
> by the validated exit code read from the temporary exit code file.
> In the unlikely event where the temporary exit code file contains 0,
> the final EXIT_CODE is not changed.
> 
> Continuing the **Yak Shave**, use of the `mktemp` command was
> improved in other shell scripts that use it, namely `run_bison.sh`
> and `run_flex.sh`.  They too use a mktemp template filename.
> 
> Temporary files created by `json_test.sh` and `txzchk_test.sh`
> are of the form: `.exit_code.__script_basename__.XXXXXXXXXX*`
> and the temporary files created by `run_bison.sh` are of the
> form `.sorry.bison.XXXXXXXXXX` and temporary files created by
> ``run_flex.sh` are of the form `.sorry.flex.XXXXXXXXXX`.
> 
> All temporary exit code files are cleaned up by the `make prep_clobber`
> rule.  They are also ignored in the `.gitignore` file.
> 
> Fixed a problem where the `build.log` file was being
> removed during the `make prep` and `make release` rules.
> 
> A non-zero exit of `prep.sh` during `make prep` and `make release`
> will be reported by the Makefile.  In particular, if `prep.sh`
> exited non-zero, then a Warning is issued by the make file.  In the
> case of `make prep`, the make command will not exit.  In the case
> of `make release`, the make command exit non-zero (abort) after
> printing information such as the `prep.sh` exit code and a message
> about above details were saved in the build.log file.
> ```

As for this I"m not sure it works right. That or there's a bug with the `txzchk_test.sh` script. But I don't think that's it. Check this:

```sh
$ ./txzchk_test.sh -D3
[...]
Performing checks on tarball ...
test-7
txzchk: ./test_txzchk/bad/entry.test-7.9876543210.txt size of 577 bytes OK
debug[3]: txzchk: ./test_txzchk/bad/entry.test-7.9876543210.txt size in bytes: 577
debug[3]: adding line drwxr-xr-x  0 501    20          0 Feb  6 01:44 test-7/ to lines list
drwxr-xr-x  0 501    20          0 Feb  6 01:44 test-7/
debug[3]: adding line -rw-r--r--  0 501    20        896 Feb  6 00:56 test-7/Makefile to lines list
-rw-r--r--  0 501    20        896 Feb  6 00:56 test-7/Makefile
debug[3]: adding line -rw-r--r--  0 501    20          4 Feb  6 00:56 test-7/extra2 to lines list
-rw-r--r--  0 501    20          4 Feb  6 00:56 test-7/extra2
debug[3]: adding line -rw-r--r--  0 501    20          0 Feb  6 00:56 test-7/prog.c to lines list
-rw-r--r--  0 501    20          0 Feb  6 00:56 test-7/prog.c
debug[3]: adding line -rw-r--r--  0 501    20        720 Feb  6 00:56 test-7/.author.json to lines list
-rw-r--r--  0 501    20        720 Feb  6 00:56 test-7/.author.json
debug[3]: adding line -rw-r--r--  0 501    20        358 Feb  6 00:56 test-7/remarks.md to lines list
-rw-r--r--  0 501    20        358 Feb  6 00:56 test-7/remarks.md
debug[3]: adding line -rw-r--r--  0 501    20       1231 Feb  6 00:56 test-7/.info.json to lines list
-rw-r--r--  0 501    20       1231 Feb  6 00:56 test-7/.info.json
debug[3]: adding line -rw-r--r--  0 501    20          4 Feb  6 00:56 test-7/extra1 to lines list
-rw-r--r--  0 501    20          4 Feb  6 00:56 test-7/extra1
debug[3]: adding line -rw-r--r--  0 501    20         49 Feb  6 02:07 ../../../../etc/passwd to lines list
-rw-r--r--  0 501    20         49 Feb  6 02:07 ../../../../etc/passwd
Warning: txzchk: ./test_txzchk/bad/entry.test-7.9876543210.txt: found file with .. in the path: ../../../../etc/passwd
Warning: txzchk: ./test_txzchk/bad/entry.test-7.9876543210.txt: found incorrect directory in filename ../../../../etc/passwd
debug[3]: adding filename ../../../../etc/passwd (basename passwd) to list of files
debug[3]: adding filename test-7/extra1 (basename extra1) to list of files
debug[3]: adding filename test-7/.info.json (basename .info.json) to list of files
debug[3]: adding filename test-7/remarks.md (basename remarks.md) to list of files
debug[3]: adding filename test-7/.author.json (basename .author.json) to list of files
debug[3]: adding filename test-7/prog.c (basename prog.c) to list of files
debug[3]: adding filename test-7/extra2 (basename extra2) to list of files
debug[3]: adding filename test-7/Makefile (basename Makefile) to list of files
debug[3]: adding filename test-7/ (basename test-7) to list of files
txzchk: ./test_txzchk/bad/entry.test-7.9876543210.txt total size of files 3262 rounded up to 1024 multiple: 4096 OK
Warning: txzchk: ./test_txzchk/bad/entry.test-7.9876543210.txt: found directory change in filename ../../../../etc/passwd
Warning: txzchk: ./test_txzchk/bad/entry.test-7.9876543210.txt: not all files in correct directory
Warning: txzchk: ./test_txzchk/bad/entry.test-7.9876543210.txt: found 4 issues
[...]
```

But look at the exit value:

```sh
$ echo $?
0
```

And if I pass `-v 1` to the script I see:

```sh
./txzchk_test.sh: debug[1]: top level EXIT_CODE: 0
./txzchk_test.sh: debug[1]: all tests PASSED
```

But as you can see `txzchk` does find issues with that tarball.

I'll be adding new test cases soon though including that one I just pasted above.

**Comment by xexyl** [comment]
Just added those bad test files but not yet published them. I'll do a pull request later. I have (I think) more I can add but I want to reply to the other comments and also hope to work on the debug documentation a bit (if not a while). I possibly will take a break after comments and before documentation but we shall see.

Hope you're having a nice sleep my friend!

**Comment by xexyl** [comment]
> The fix testing well, but we have noticed that `build.log` turns up missing after `make prep` and `make release`. This is not a consequence of the fix, but rather some other bug.
> 
> We are going to fix the missing `build.log` because we would like to see, as part of the testing, the new diagnostics going into that file.

My immediate thought was the `make prep_clobber` rule since it did indeed remove that log file (at least from memory). It seems you fixed this though? Was that it?

**Comment by xexyl** [comment]
> > Happy you appreciate my jokes but which one do you refer to? The imperfect one?
> 
> Yes :)

:)

Well I'm happy it helped you out and gave you a laugh. It's funny how it came about though. Yes there was the obviously nonsense reasoning behind it but I also at the time rather did see myself as a nobody. I don't know but I did for many many years. So as I said it was originally:


> Nobody is perfect. I am nobody. Therefore I am perfect.

But of course that was an invalid syllogism (I guess many are) as well as taking the piss out of the idea of human perfection (there is absolutely no such thing and those who think they are perfect are the least perfect). It was just fun and funny but there was probably some self deprecating humour in there as well.

Anyway yes we're all imperfect but those who embrace it and make use of this have a huge strength over those who do not. If someone does something that hurts another person or is wrong in some way they should (if they're genuinely sorry) apologise and make amends. If they're not genuinely sorry they shouldn't. Unfortunately there are many apologies that are clearly bogus. Classic examples:

> I'm sorry the way I worded it hurt you.

> I'm sorry you took it that way.

And even more bogus, perhaps, is this:

![277408345_934800930564099_9060854638511901845_n](https://user-images.githubusercontent.com/53008573/172046640-36c8c4c1-c1f0-4eb6-9263-5b7c61e928d3.jpg)

But that one is at least very funny!

Anyway happy I could help you - in any way I can! Hope you're having a nice sleep and I hope you feel all better when you wake up!

**Comment by xexyl** [comment]
> 
> ### UPDATE 2:
> So the `perl` environment **going boing** provided an additional test case for the previously mentioned `build.log` missing issue, that now seems fixed.

Out of curiosity what was the problem?

**Comment by xexyl** [comment]
Will be afk a bit .. will reply to the other things later and then hope to get working on the debug facility documentation. Might even be able to reply to some of the comments when afk as I'll have my phone - just going to get on the exercise bike.
