### ISSUE TITLE
Bug report: jstr_test.sh failure due to test/ subdirectory

### ISSUE THREAD

**Issue by xexyl** [ioccc-src/mkiocccentry#407]
NOTE: I have a fix for the main problem and I'll be committing it but I'm going to document everything anyway. I'll say what is fixed at the end.

## Describe the bug

There are a number problems actually depending on how it's invoked.

I am deferring it to the relevant output as it says it all.

## To Reproduce

0.  See below.

## Expected behaviour

If it cannot find the files needed it should fail. This has not been fixed.

But it should also not fail in the first place as the script should be able to find the script itself. See below for fix which I'll be committing in a bit. This HAS been fixed though just like some of the other scripts under `test/` if one runs it directly under `test` the script will fail probably because of the block:

```sh
elif [[ -f ../mkiocccentry.c ]]; then
    cd ..
    status="$?"
    if [[ $status -ne 0 ]]; then
        echo "$0: ERROR: cd .. exit code: $status" 1>&2
        exit 3
    fi
    TOPDIR="$PWD"
    if [[ $V_FLAG -ge 3 ]]; then
        echo "$0: debug[3]: assume TOPDIR is ..: $TOPDIR" 1>&2
    fi

```

which will change to the parent directory which means that `./jstr_test.sh` no longer is the right name.

## Relevant Output

For example try running it from the root directory. THIS HAS BEEN FIXED! I am only including it so you can see what is fixed in an upcoming commit.

```sh
test/jstr_test.sh -Z /Users/cody/code/xexyl-mkiocccentry
rm -f test/jstr_test.out test/jstr_test2.out
test/jstr_test.sh: about to run test #0
./jstrencode: Beginning jencchk test on code JSON encode/decode functions ...
./jstrencode: ... passed JSON encode/decode test
test/jstr_test.sh: test #0 passed
test/jstr_test.sh: about to run test #1
./jstrencode -v 0 -n < ./jstrencode | ./jstrdecode -v 0 -n > test/jstr_test.out
test/jstr_test.sh: test #1 passed
test/jstr_test.sh: about to run test #2
./jstrencode -v 0 -n < ./jstrdecode | ./jstrdecode -v 0 -n > test/jstr_test.out
test/jstr_test.sh: test #2 passed
test/jstr_test.sh: about to run test #3
cat $SRC_SET | ./jstrencode -v 0 -n | ./jstrdecode -v 0 -n > test/jstr_test.out
cat: jstr_test.sh: No such file or directory
cat: jstr_test.sh: No such file or directory
test/jstr_test.sh: test #3 passed
test/jstr_test.sh: all tests passed

PASSED: test/jstr_test.sh
```

Running it directly like `test/jstr_test.sh` also has the same problem that's since been fixed.

Also FIXED:

`ioccc_test.sh` was missing the `-Z` option which I added in the invocation and now works.

## NOT fixed invocations below

Try running from `test/` with or without the -Z option being `..`:

```sh
$ ./jstr_test.sh 
rm -f test/jstr_test.out test/jstr_test2.out
./jstr_test.sh: about to run test #0
./jstrencode: Beginning jencchk test on code JSON encode/decode functions ...
./jstrencode: ... passed JSON encode/decode test
./jstr_test.sh: test #0 passed
./jstr_test.sh: about to run test #1
./jstrencode -v 0 -n < ./jstrencode | ./jstrdecode -v 0 -n > test/jstr_test.out
./jstr_test.sh: test #1 passed
./jstr_test.sh: about to run test #2
./jstrencode -v 0 -n < ./jstrdecode | ./jstrdecode -v 0 -n > test/jstr_test.out
./jstr_test.sh: test #2 passed
./jstr_test.sh: about to run test #3
cat $SRC_SET | ./jstrencode -v 0 -n | ./jstrdecode -v 0 -n > test/jstr_test.out
cat: jstr_test.sh: No such file or directory
cat: jstr_test.sh: No such file or directory
./jstr_test.sh: test #3 passed
./jstr_test.sh: all tests passed
```

And of course if one uses `-Z .` it's another problem:

```sh
$ ./jstr_test.sh -Z .
./jstr_test.sh: ERROR: missing jstrencode tool: ./jstrencode
```

which makes sense. Running from test directly I guess is not a problem and other scripts have the same problem. BUT importantly, maybe, is that it always passes even if a mouse .. ehm, file :-) cannot be found for cat.

## bug report attachment

In this case it's not necessary especially as I have a fix for the first part and a bug report invocation (which has since been improved and not committed yet either .. plus some fixes with some scripts that made some of the output not correct which also have not been committed yet) would not help.

## Please provide the following information:

 - Did you attach the above requested bug report file?  [yes, no & why not]

No because I have a fix for part of it and the other part doesn't need any information about it. Also as above there are some pending fixes for the script and other scripts that makes some of the output not correct (though not related to `jstr_test.sh`). It's simply that the script does not work as expected in one way.

## The fix

The fix for the first part is simply changing the raw references of `jstr_test.sh` in the script to be `$0`. Expect a commit soon and if you're lucky you'll already have it by the time you're awake.

As for why it does not report an error if a file cannot be found I don't know if that's a problem especially after the fix is in. I hope to do that shortly and then take a break.

**Comment by xexyl** [comment]
See https://github.com/ioccc-src/mkiocccentry/pull/408/commits/02a9308b6ddf19f0844e3c2b7c7ca454c5d2405b for the fixes. There still remains the problem of it not reporting an error if a file cannot be found (the SRC_SET variable).

**Comment by xexyl** [comment]
Re assigning me:

I can certainly look at it though I'm not sure if it'll be today. Been awake too long. Going to get some food and then take it easy a bit. I might have some time and energy to look at it later on today but if not I'll see about it tomorrow.

**Comment by xexyl** [comment]
Committed. Afk now for a while.

**Comment by lcn2** [comment]
Based on [this tutorial](https://www.cyberciti.biz/faq/unix-linux-bash-find-out-the-exit-codes-of-all-piped-commands/) consider extending the fix we just committed to testing the exit status of both `jstrencode` and `jstrdecode` in that pipe.

**Comment by xexyl** [comment]
> Based on [this tutorial](https://www.cyberciti.biz/faq/unix-linux-bash-find-out-the-exit-codes-of-all-piped-commands/) consider extending the fix we just committed to testing the exit status of both `jstrencode` and `jstrdecode` in that pipe.

Did you push it ? Since I don't see it .. I just did what I think is a fix but it had to be done specially because (my immediate thought actually) if you try looping over the array it will lose its values after the next command. So you have to copy it first.

**Comment by xexyl** [comment]
Leaving for the day .. can commit tomorrow if you confirm that you did not make a fix. Enjoy the rest of your day!

**Comment by xexyl** [comment]
Hope you’re okay. I am sure it was just a day away from the repo (maybe you had your physical?) but just wanted to say I hope you’re okay either way!

I also hope you’re sleeping well!

**Comment by lcn2** [comment]
> Hope you’re okay. I am sure it was just a day away from the repo (maybe you had your physical?) but just wanted to say I hope you’re okay either way!
> 
> I also hope you’re sleeping well!

We are working on code to submit to another repo, not related to this repo.  We will be a tool that we might be able to use to transfer data from the submit server.

We received a request for the tool from one of our former students and have been working on the tool.

We will publish a note about this tool in issue #171 when the tool is done.

**Comment by xexyl** [comment]
> > Hope you’re okay. I am sure it was just a day away from the repo (maybe you had your physical?) but just wanted to say I hope you’re okay either way!
> > I also hope you’re sleeping well!
> 
> We are working on code to submit to another repo, not related to this repo. We will be a tool that we might be able to use to transfer data from the submit server.
> 
> We received a request for the tool from one of our former students and have been working on the tool.
> 
> We will publish a note about this tool in issue #171 when the tool is done.

Glad you're okay. I'm having some off days. I hope that that gets better soon. Last night was quite rough though so I'm not surprised today is an off day also. I'll probably not be at the laptop much longer.

A question though. You've used the term 'student' before. In what way do you mean student please? I can take some guesses but I'm not sure if you ever taught and of course that's what I first think of when I hear 'student'.

Hope it works out well .. no rush on getting back here. I'll be here. Good day!

**Comment by lcn2** [comment]
> > > Hope you’re okay. I am sure it was just a day away from the repo (maybe you had your physical?) but just wanted to say I hope you’re okay either way!
> 
> > > I also hope you’re sleeping well!
> 
> > 
> 
> > We are working on code to submit to another repo, not related to this repo. We will be a tool that we might be able to use to transfer data from the submit server.
> 
> > 
> 
> > We received a request for the tool from one of our former students and have been working on the tool.
> 
> > 
> 
> > We will publish a note about this tool in issue #171 when the tool is done.
> 
> 
> 
> Glad you're okay. I'm having some off days. I hope that that gets better soon. Last night was quite rough though so I'm not surprised today is an off day also. I'll probably not be at the laptop much longer.
> 
> 
> 
> A question though. You've used the term 'student' before. In what way do you mean student please? I can take some guesses but I'm not sure if you ever taught and of course that's what I first think of when I hear 'student'.
> 
> 
> 
> Hope it works out well .. no rush on getting back here. I'll be here. Good day!

We have thought classes.  We have had multiple research assistance students for year long classes.

**Comment by xexyl** [comment]
> We have thought classes. We have had multiple research assistance students for year long classes.

Something tells me that your classes would be REALLY interesting! What did you teach, please, if you have the time to say? I want to say again I really appreciate all your stories and experiences and so on! It's fascinating and a joy to be able to learn from you, learn about you and so on (and I hope and believe you feel the same way about me).

Anyway as far as this issue goes see commit https://github.com/ioccc-src/mkiocccentry/pull/410/commits/472083e5828a45f8494dce59ee16d5e3f5e77573.

**Comment by lcn2** [comment]
> > We have thought classes. We have had multiple research assistance students for year long classes.
> 
> Something tells me that your classes would be REALLY interesting! What did you teach, please, if you have the time to say? I want to say again I really appreciate all your stories and experiences and so on! It's fascinating and a joy to be able to learn from you, learn about you and so on (and I hope and believe you feel the same way about me).
> 
> Anyway as far as this issue goes see commit [472083e](https://github.com/ioccc-src/mkiocccentry/commit/472083e5828a45f8494dce59ee16d5e3f5e77573).

In general:

Physics
Mathematics
Computer Science
Astronomy

**Comment by xexyl** [comment]
> > > We have thought classes. We have had multiple research assistance students for year long classes.
> > 
> > 
> > Something tells me that your classes would be REALLY interesting! What did you teach, please, if you have the time to say? I want to say again I really appreciate all your stories and experiences and so on! It's fascinating and a joy to be able to learn from you, learn about you and so on (and I hope and believe you feel the same way about me).
> > Anyway as far as this issue goes see commit [472083e](https://github.com/ioccc-src/mkiocccentry/commit/472083e5828a45f8494dce59ee16d5e3f5e77573).
> 
> In general:
> 
> Physics Mathematics Computer Science Astronomy

All but physics sounds fascinating to me! Well I probably would do better at it now than when I was in school. I was quite unwell at the time and although I was for some classes wayyyy ahead for others I struggled. But it was the environment. I am not good at learning when in groups. It was especially bad in my youth. 

I have since surprised myself many times with what I am capable with in maths. For years I thought I was awful at it and I had little use for it. But then a really good friend of mine pointed out that boolean logic is maths! That’s very true. Since then (and that was a long time ago) I have done quite some good stuff with numbers. Probably have before that as well. 

One numbers thing I really enjoy is the birthday paradox. I am sure you are familiar with it. For me it’s a lot of fun and I enjoy telling people about it. They are quite surprised when I tell them how few people you need before the chance of sharing your birthday with at least one person is >= 50%! 

Astronomy is fascinating. I used to have a telescope but it’s not really useful here. Too much light pollution :( The fact I go to sleep so early doesn’t help matters either. But I have always loved space. Dinosaurs too and earthquakes and volcanoes and in general natural disasters. They’re fascinating!

Anyway I suspect that your classes would be very very interesting and actually very very fascinating! Thank you for answering. 

I will be awake a bit longer but I am done here for the night. Sleep well when you do and good night my friend!
