### ISSUE TITLE
Bug report: make test fails on RedHat Linux 7.9

### ISSUE THREAD

**Issue by lcn2** [ioccc-src/mkiocccentry#417]
## Describe the bug

On Linux (RH7.9) `make clobber all test` fails.

## To Reproduce

Steps to reproduce the behavior (adjust steps as needed):

0. make clobber all
1. make test

## Expected behavior

After `make clobber all`, the `make test` should pass and exit 0.

## Relevant Output

After a successful `make clobber all`, the `make test` fails:

```
$ make test
make[1]: Entering directory `/var/tmp/mkiocccentry/dbg'
make[1]: Leaving directory `/var/tmp/mkiocccentry/dbg'
make[1]: Entering directory `/var/tmp/mkiocccentry/soup'
make[1]: Leaving directory `/var/tmp/mkiocccentry/soup'
make -C test_ioccc test
make[1]: Entering directory `/var/tmp/mkiocccentry/test_ioccc'
cc  -I.. utf8_test.c -c
cc  -I.. utf8_test.o ../utf8_posix_map.o ../dbg/dbg.o ../util.o ../dyn_array.o -o utf8_test
cc  -I.. jnum_chk.c -c
cc  -I.. jnum_test.c -c
In file included from jnum_test.c:26:0:
../dbg/dbg.h:55:23: error: two or more data types in declaration specifiers
 typedef unsigned char bool;
                       ^
In file included from ../dyn_array.h:52:0,
                 from ../util.h:42,
                 from ../json_parse.h:26,
                 from jnum_test.c:33:
../dbg/dbg.h:55:1: warning: useless type name in empty declaration [enabled by default]
 typedef unsigned char bool;
 ^
In file included from jnum_test.c:26:0:
../util.h:53:23: error: two or more data types in declaration specifiers
 typedef unsigned char bool;
                       ^
In file included from ../json_parse.h:26:0,
                 from jnum_test.c:33:
../util.h:53:1: warning: useless type name in empty declaration [enabled by default]
 typedef unsigned char bool;
 ^
make[1]: *** [jnum_test.o] Error 1
make[1]: Leaving directory `/var/tmp/mkiocccentry/test_ioccc'
make: *** [test] Error 2
```

## bug report attachment

vvvvvvvvvvvvvvvvvvvvvvvvv --- Drag the file into the area below, please!

[bug-report.20221119.214019.txt](https://github.com/ioccc-src/mkiocccentry/files/10048954/bug-report.20221119.214019.txt)

^^^^^^^^^^^^^^^^^^^^^^^^^ --- Drag the file into the area above, please!

## Please provide the following information:

 - Did you attach the above requested bug report file?  Yes
 - What is the airspeed Velocity of an Unladen Swallow? X m/s

## Additional context

This bug does not show up under Debian (Raspbian GNU/Linux 10 (buster)), nor macOS (13.0.1).

**Comment by lcn2** [comment]
We thought this bug report might be a good test to see if the bug report attachment contained some useful info, @xexyl

**Comment by xexyl** [comment]
> 

About to boot up the laptop so I hope to look at it soon. Thank you for the report. 

Hopefully I can reproduce it so it’s easier to to test. 

And I hope you can get some sleep!

**Comment by xexyl** [comment]
My guess is it might fail under CentOS. I hope so. I still am waking up but I can’t sleep either. Anyway going to pull the laptop out of the laptop bag/whatever.

**Comment by xexyl** [comment]
> My guess is it might fail under CentOS. I hope so. I still am waking up but I can’t sleep either. Anyway going to pull the laptop out of the laptop bag/whatever.

Unfortunately it does NOT fail under CentOS. I'll try fedora though I doubt it'll fail there. If it doesn't I'll take a look at the error and see if I can figure it out.

**Comment by xexyl** [comment]
I think I have an idea of why it fails. I have no way of testing it but it seems like it might be it. I'll make a commit soon and hopefully it'll solve the problem. I'll explain the logic in the commit and then put a comment here too.

Hopefully it resolves the problem and you can close this.

**Comment by xexyl** [comment]
Looks like my suspicion was right .. by changing something in `util.h` I could duplicate it. I will make a commit soonish.

**Comment by xexyl** [comment]
Actually I'll explain the problem here first.

The problem is, as the error s how's, this line:

```c
typedef unsigned char bool;
```

But why? Of course `unsigned char` is already there and it seems that `bool` is being defined in some other header file as well. Thus the typedef is faulty because it's trying to define bool when it already is defined (not sure that's the right word). If one changes in `util.h`:

```diff
$ git diff util.h 
diff --git i/util.h w/util.h
index cbd414d..fafa155 100644
--- i/util.h
+++ w/util.h
@@ -43,11 +43,11 @@
 
 
 /*
  * standard truth :-)
  */
-#if defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 199901L)
+#if !defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 199901L)
```

under macOS you'll get:

```sh
cc -std=gnu11 -O0 -g -pedantic -Wall -Wextra -Werror -ferror-limit=0  mkiocccentry.c -c
In file included from mkiocccentry.c:90:
In file included from ./mkiocccentry.h:67:
./util.h:53:23: error: cannot combine with previous 'char' declaration specifier
typedef unsigned char bool;
                      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.0/include/stdbool.h:15:14: note: expanded from macro 'bool'
#define bool _Bool
             ^
In file included from mkiocccentry.c:90:
In file included from ./mkiocccentry.h:67:
./util.h:53:1: error: typedef requires a name [-Werror,-Wmissing-declarations]
typedef unsigned char bool;
^~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
make: *** [mkiocccentry.o] Error 1
```

However under linux you'll get:

```sh
make[1]: Entering directory `/home/xexyl/ioccc/xexyl-mkiocccentry/dbg'
make[1]: Leaving directory `/home/xexyl/ioccc/xexyl-mkiocccentry/dbg'
make[1]: Entering directory `/home/xexyl/ioccc/xexyl-mkiocccentry/soup'
make[1]: Leaving directory `/home/xexyl/ioccc/xexyl-mkiocccentry/soup'
cc -std=gnu11 -O0 -g -pedantic -Wall -Wextra -Werror  mkiocccentry.c -c
In file included from dbg/dbg.h:52:0,
                 from dyn_array.h:52,
                 from util.h:42,
                 from mkiocccentry.h:67,
                 from mkiocccentry.c:90:
util.h:53:23: error: two or more data types in declaration specifiers
 typedef unsigned char bool;
                       ^
In file included from mkiocccentry.h:67:0,
                 from mkiocccentry.c:90:
util.h:53:1: error: useless type name in empty declaration [-Werror]
 typedef unsigned char bool;
 ^
cc1: all warnings being treated as errors
make: *** [mkiocccentry.o] Error 1
```

So the question is which files use the code:

```c
#if defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 199901L)
/* have a C99 compiler - we should expect to have <stdbool.h> */
#include <stdbool.h>
#elif !defined(__cplusplus)
/* do not have a C99 compiler - fake a <stdbool.h> header file */
typedef unsigned char bool;
#undef true
#define true ((bool)(1))
#undef false
#define false ((bool)(0))
#endif
```

And that appears to be the following files:

```sh
$ grep -lr 'typedef unsigned char bool'
util.h
dbg/dbg.h
iocccsize.h
```

The `util.h` is correct. Normally `dbg.h` is okay but when it comes to some files they also include other files that have the same code.

So the solution is a guard to not do that more than once. I'll clean this up and then make a commit after some tests.

**Comment by xexyl** [comment]
The above causes a different problem .. looking at that too.

**Comment by xexyl** [comment]
It's fixed but I'm going to have a lie down first .. back later and when I'm back I'll make the commits (yes commits as unfortunately it involves a change in the debug repo too .. it also requires a change in `iocccsize.h` - hope that's okay).

Well it might not be required to modify _all_of those files but better safe than sorry.

**Comment by xexyl** [comment]
Should be fixed in commit https://github.com/ioccc-src/mkiocccentry/pull/418/commits/fb8203ac5de4c5e19a44a785f436236fae89bac3 and in the dbg repo https://github.com/lcn2/dbg/pull/14/commits/845cc981c6565b162ef6230996c68c11424e8f75.

I really am going to rest now!

**Comment by xexyl** [comment]
Oh before I go: it does indeed touch `iocccsize.h`. I'll let you decide how or if that's necessary to deal with in the other repo .. not sure but I think maybe not as it doesn't use util.h I guess? But anyway the problem should be resolved now.

After resting (assuming my body will let me) I'll see if I can work on moving `dyn_array` and/or `jparse` to separate directories.

**Comment by xexyl** [comment]
> We thought this bug report might be a good test to see if the bug report attachment contained some useful info, @xexyl

It most certainly did! Thank you for including it. It let me identify the problem and also figure out a way to duplicate it (albeit by forcing it).

**Comment by lcn2** [comment]
> > We thought this bug report might be a good test to see if the bug report attachment contained some useful info, @xexyl
> 
> 
> 
> It most certainly did! Thank you for including it. It let me identify the problem and also figure out a way to duplicate it (albeit by forcing it).

That is a very good sign that the bug report system is working well!

**Comment by xexyl** [comment]
> > > We thought this bug report might be a good test to see if the bug report attachment contained some useful info, @xexyl
> > 
> > 
> > It most certainly did! Thank you for including it. It let me identify the problem and also figure out a way to duplicate it (albeit by forcing it).
> 
> That is a very good sign that the bug report system is working well!

It is indeed! Now if I can figure out a good way to handle the moving jparse to a subdirectory. It's a problem with `bug_report.sh` - not just a simple matter of changing the path of the tool in the tools variable as the invocations later on cause a problem. It's proving to be another cat and mouse issue.

**Comment by lcn2** [comment]
With commit a45a878051c9d39309f0d9525a92563d4fa7c974 this code now works under Linux RHEL7.9!

**Comment by xexyl** [comment]
> With commit [a45a878](https://github.com/ioccc-src/mkiocccentry/commit/a45a878051c9d39309f0d9525a92563d4fa7c974) this code now works under Linux RHEL7.9!

Great! Thank you for confirming.

**Comment by xexyl** [comment]
Why reopen it ? What went wrong ?

**Comment by lcn2** [comment]
Well under macOS 13.0.1, after `make clobber all`:

```
$ make test
make test
make -C test_ioccc test
cc  -I.. utf8_test.c -c
make[1]: *** No rule to make target `../dyn_array.o', needed by `utf8_test'.  Stop.
make: *** [test] Error 2
zsh: exit 2     make test
```

**Comment by xexyl** [comment]
> Well under macOS 13.0.1, after `make clobber all`:
> 
> ```
> $ make test
> make test
> make -C test_ioccc test
> cc  -I.. utf8_test.c -c
> make[1]: *** No rule to make target `../dyn_array.o', needed by `utf8_test'.  Stop.
> make: *** [test] Error 2
> zsh: exit 2     make test
> ```

Strange. I'm not sure it's the same thing but I can look at it. I'm working on the jparse one and then I will have to take a break. It works fine under macOS but now under linux I have to take care of another problem. Maybe I can address this one soon.

**Comment by xexyl** [comment]
But what's really strange I don't have this problem. Even so it should be easy to fix.

**Comment by xexyl** [comment]
I want to curse at the CentOS developers right now ... the flag to disable a warning being triggered is not available under CentOS. Instead it's a different name. I think and hope it'll work to do both.

**Comment by xexyl** [comment]
> I want to curse at the CentOS developers right now ... the flag to disable a warning being triggered is not available under CentOS. Instead it's a different name. I think and hope it'll work to do both.

Fortunately it does work on both systems.

**Comment by lcn2** [comment]
> But what's really strange I don't have this problem. Even so it should be easy to fix.

Could it be related to the _*.o_ files hanging around after a `make clobber` as noted in [comment 1321209158](https://github.com/ioccc-src/mkiocccentry/issues/338#issuecomment-1321209158)?

**Comment by xexyl** [comment]
> > But what's really strange I don't have this problem. Even so it should be easy to fix.
> 
> Could it be related to the _*.o_ files hanging around after a `make clobber` as noted in [comment 1321209158](https://github.com/ioccc-src/mkiocccentry/issues/338#issuecomment-1321209158)?

I actually wondered about that. What happens if you do `rm -f *.o` ?

I did notice another problem with the make depend script but that's too much to say right now.

**Comment by xexyl** [comment]
Good news is that the jparse move is working now. I can make a commit soon. Then I hope to look at the above issue.

**Comment by xexyl** [comment]
Good news is that the jparse move is working now. I can make a commit soon. Then I hope to look at the above issue.

**Comment by xexyl** [comment]
Well here's some irony! After tarring up the changes I made under linux and then transferring it to the macOS system I got the same issue you reported.

**Comment by lcn2** [comment]
In the process of investigating the `dbg.md` being left behind, we re-cloned the repo on all platforms.

Now, unfortunately, after `make clobber all`:

```sh
$ make test
make -C test_ioccc test
cc  -I.. utf8_test.c -c
make[1]: *** No rule to make target `../dyn_array.o', needed by `utf8_test'.  Stop.
make: *** [test] Error 2
zsh: exit 2     make test
```

on macOS 13.0.1, Linux RHEL7.9, and Raspbian GNU/Linux 10 (buster).

**Comment by xexyl** [comment]
And now I see it locally I know exactly what happened. It's because the Makefile was not updated to refer to `../dyn_array/` as a directory.

**Comment by xexyl** [comment]
> In the process of investigating the `dbg.md` being left behind, we re-cloned the repo on all platforms.
> 
> Now, unfortunately, after `make clobber all`:
> 
> ```shell
> $ make test
> make -C test_ioccc test
> cc  -I.. utf8_test.c -c
> make[1]: *** No rule to make target `../dyn_array.o', needed by `utf8_test'.  Stop.
> make: *** [test] Error 2
> zsh: exit 2     make test
> ```
> 
> on macOS 13.0.1, Linux RHEL7.9, and Raspbian GNU/Linux 10 (buster).

Yes a fix will be there soon. I just have to figure out how to do this commit without causing a problem with the fact the other one is merged.

**Comment by lcn2** [comment]
> > In the process of investigating the `dbg.md` being left behind, we re-cloned the repo on all platforms.
> > Now, unfortunately, after `make clobber all`:
> > ```shell
> > $ make test
> > make -C test_ioccc test
> > cc  -I.. utf8_test.c -c
> > make[1]: *** No rule to make target `../dyn_array.o', needed by `utf8_test'.  Stop.
> > make: *** [test] Error 2
> > zsh: exit 2     make test
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > on macOS 13.0.1, Linux RHEL7.9, and Raspbian GNU/Linux 10 (buster).
> 
> Yes a fix will be there soon. I just have to figure out how to do this commit without causing a problem with the fact the other one is merged.

We need to do some yard work.  Will be back later in our afternoon.  Best wishes and thanks!

**Comment by xexyl** [comment]
> > > In the process of investigating the `dbg.md` being left behind, we re-cloned the repo on all platforms.
> > > Now, unfortunately, after `make clobber all`:
> > > ```shell
> > > $ make test
> > > make -C test_ioccc test
> > > cc  -I.. utf8_test.c -c
> > > make[1]: *** No rule to make target `../dyn_array.o', needed by `utf8_test'.  Stop.
> > > make: *** [test] Error 2
> > > zsh: exit 2     make test
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > on macOS 13.0.1, Linux RHEL7.9, and Raspbian GNU/Linux 10 (buster).
> > 
> > 
> > Yes a fix will be there soon. I just have to figure out how to do this commit without causing a problem with the fact the other one is merged.
> 
> We need to do some yard work. Will be back later in our afternoon. Best wishes and thanks!

Best wishes to you too! Stay safe (from the Sun)! Once I have the commit in I'll be doing something else for the rest of the day.

**Comment by xexyl** [comment]
I didn't say here for some reason. The commit in the open pull request also addresses this issue.

**Comment by lcn2** [comment]
We will have to complete issue #422 in order to properly fix this issue.  Therefore we will close this issue now.

**Comment by xexyl** [comment]
> We will have to complete issue #422 in order to properly fix this issue. Therefore we will close this issue now.

No worries.

And not sure where it was so I'll say it here. I agree that the `rm -f *.o` was kind of extreme (not really the word I'm looking for) but that's indeed why I was asking about doing it in the first place.
