### ISSUE TITLE
Turn off twitter, turn on Mastodon

### ISSUE THREAD

**Issue by lcn2** [ioccc-src/mkiocccentry#431]
Based on [comment 1331452956](https://github.com/ioccc-src/mkiocccentry/issues/171#issuecomment-1331452956), we need to disable use of Twitter handles and migrate to using Mastodon handles.

We need change asking for optional twitter handles and instead ask for optional Mastodon usernames.

NOTE: Full Mastodon usernames are of the form:

@username@server.foo

For example, the full IOCCC Mastodon usernames is:

**@ioccc@fosstodon.org**

**Comment by lcn2** [comment]
Help, @xexyl in doing this change would be appreciated.

**Comment by xexyl** [comment]
Ah, of course. The code has to be changed too. I'm not sure I have the right mindset to do that right now but if you don't have it done by tomorrow maybe I can tackle it.

If I had noticed the FOSS server I would have chosen that.

**Comment by xexyl** [comment]
> Help, @xexyl in doing this change would be appreciated.

Sure! I can look at it tomorrow.

**Comment by lcn2** [comment]
Interesting GitHub note: One cannot assign a task to a non-GitHub account holder until they have posted a comment to an issue.

**Comment by xexyl** [comment]
Thanks for assigning it to me. I'll look at it tomorrow. And the good thing is the mastodon server I chose actually just accepted me. I'm @xexyl@discuss.systems it seems.

**Comment by xexyl** [comment]
> Interesting GitHub note: One cannot assign a task to a non-GitHub account holder until they have posted a comment to an issue.

That is interesting yes. Thanks for sharing that.

**Comment by xexyl** [comment]
... I do like the look of your server better though.

To help me so I can look at this better. Obviously we have to change the regexp for the handle a bit (or I think so - have to look at it). Then we have to change the functions in `entry_util.{c,h}` and any references to twitter need to be changed to mastodon. Should it be Mastodon or mastodon?

Anything else comes to mind that I should look at? Ah yes. The one that might be problematic is updating all the test json files as well as the semantics files. 

Speaking of such should the variable in the json auth file be `mastodon` ? I guess so but want to come up with as many things as possible so I don't have anything delay me tomorrow.

**Comment by xexyl** [comment]
.. just created a new account (or set up to be created) on the same server you chose. I'm doing other things now but I hope that you'll be able to say enough here (what with your service issue) so that I can work on this tomorrow.

Good night my friend!

**Comment by xexyl** [comment]
Okay looking at the format of handles .. I wonder. Is any TLD acceptable? My guess is yes but should we have a limit on the number of characters? If so what's the new limit? I guess it has to be increased from before since twitter handles don't have a host attached to them.

Now going to do just take it easy a bit longer then try and sleep. If I don't hear anything back I'll at least start on it assuming that tonight goes okay (even if it doesn't I probably will be able to at least start on it).

**Comment by lcn2** [comment]
> To help me so I can look at this better. Obviously we have to change the regexp for the handle a bit (or I think so - have to look at it). Then we have to change the functions in entry_util.{c,h} and any references to twitter need to be changed to mastodon. Should it be Mastodon or mastodon?

We suggest that we use _mastodon_ in lower case for now.  We used _twitter_ for the bird, so perhaps the lower case name is OK?

For the JSON element, we recommend `"mastodon"`.  For functions we recommend the string _mastodon_, etc.

We don't know  if they call things like `@ioccc@fosstodon.org` a username or handle or ..., amongst other things.

**Comment by lcn2** [comment]
> .. just created a new account (or set up to be created) on the same server you chose. I'm doing other things now but I hope that you'll be able to say enough here (what with your service issue) so that I can work on this tomorrow.

They have real people review account requests, so it make take a day or two or three.

When you have your account, @xexyl let is know the username or handle or whatever they call it.

BTW: See also @LandonNoll@fosstodon.org ... nothing there yet as we were focused on the IOCCC side of things.

**Comment by xexyl** [comment]
> > To help me so I can look at this better. Obviously we have to change the regexp for the handle a bit (or I think so - have to look at it). Then we have to change the functions in entry_util.{c,h} and any references to twitter need to be changed to mastodon. Should it be Mastodon or mastodon?
> 
> We suggest that we use _mastodon_ in lower case for now. We used _twitter_ for the bird, so perhaps the lower case name is OK?
> 

I think so too. Maybe if referring to the name of the site it could be capitalised but it doesn't really need to be. Probably not important.

> For the JSON element, we recommend `"mastodon"`. For functions we recommend the string _mastodon_, etc.
> 

That's what I would have done yes.

> We don't know if they call things like `@ioccc@fosstodon.org` a username or handle or ..., amongst other things.

Well arguably these are just synonyms.

I left some other thoughts for discussion but I'll have to not reply further until tomorrow at least in this thread. Starting to get really tired so I'll have to go soon.

**Comment by xexyl** [comment]
> > .. just created a new account (or set up to be created) on the same server you chose. I'm doing other things now but I hope that you'll be able to say enough here (what with your service issue) so that I can work on this tomorrow.
> 
> They have real people review account requests, so it make take a day or two or three.
> 
> When you have your account, @xexyl let is know the username or handle or whatever they call it.
> 
> BTW: See also @[LandonNoll@fosstodon.org](mailto:LandonNoll@fosstodon.org) ... nothing there yet as we were focused on the IOCCC side of things.

Well I do have one but I'm trying to get on that server too. In the meantime the account that is made is @xexyl@discuss.systems. I hope to have an account on the same server as you have soon.

I guess this move also means a lot of work for you for the winner repo too. :( That's really a shame ... all because of that .. well you know what they say - if you can't say anything nice don't say anything at all.

**Comment by lcn2** [comment]
> Okay looking at the format of handles .. I wonder. Is any TLD acceptable? My guess is yes but should we have a limit on the number of characters? If so what's the new limit? I guess it has to be increased from before since twitter handles don't have a host attached to them.

I believe the form is

@username@server.do.main

We believe the username is case independent: so @IOCCC and @ioccc are equivalent.  Same with @LandonNoll, @landonnoll, @LandonNOLL, etc.  You should check that to be sure, @xexyl 

We don't know the limits on the username, nor allowed characters, nor first character, etc.

And while the server domain is a domain, we don't know if mastodon has a limit.  You should check that  as well.

**Comment by lcn2** [comment]
It is starting to snow, going home now .. where we don't yet have Internet service ..

**Comment by xexyl** [comment]
> > Okay looking at the format of handles .. I wonder. Is any TLD acceptable? My guess is yes but should we have a limit on the number of characters? If so what's the new limit? I guess it has to be increased from before since twitter handles don't have a host attached to them.
> 
> I believe the form is
> 
> @[username@server.do.main](mailto:username@server.do.main)
> 
> We believe the username is case independent: so @ioccc and @ioccc are equivalent. Same with @LandonNoll, @landonnoll, @LandonNOLL, etc. You should check that to be sure, @xexyl
> 
> We don't know the limits on the username, nor allowed characters, nor first character, etc.
> 
> And while the server domain is a domain, we don't know if mastodon has a limit. You should check that as well.

Will do.

Strangely the attempt to check the status of the new account fails. Maybe it's because the other server already has an account. Not sure if they sync up at some point. I was hoping to have the same one and then delete the first one.

**Comment by xexyl** [comment]
> It is starting to snow, going home now .. where we don't yet have Internet service ..

Be safe!

**Comment by lcn2** [comment]
> > It is starting to snow, going home now .. where we don't yet have Internet service ..
> 
> Be safe!

Thanks!

**Comment by xexyl** [comment]
> > > It is starting to snow, going home now .. where we don't yet have Internet service ..
> > 
> > 
> > Be safe!
> 
> Thanks!

Of course. I care about you a lot! Sleep tight!

**Comment by xexyl** [comment]
Got a lot done. I cheated but I got a lot done! :-)

Specifically:

```sh
find . -type f \( -name '*.c' -o -name '*.h' -o -name '*.json' -o -name '*.sh' \) -exec gsed -i 's/twitter/mastodon/g' '{}' \;
```

So now I just have to update the functions themselves as well as make sure the handles are correctly formed. That'll take more work. I'm going to sleep now. I hope to look at the details of handles tomorrow and then hopefully make changes in the code. Still didn't get an email from the other server so I'll try again tomorrow to see what is going on with that. Maybe it's just a delay but I noticed an issue as well on my end.

**Comment by xexyl** [comment]
I just set up my account and got the start of moving to the same server you're on. When that's approved I'lll move my account over via the UI. Thanks for following me. I am going to follow the IOCCC too of course.

I hope to work on this issue later on. I was planning on working on it once I booted up the laptop but I now am sleepy again and given the time I'm going to try resting again. Hope you're sleeping well and good luck with Internet service being restored!

**Comment by xexyl** [comment]
I just programmed what should be most of what's needed but I have to test it. Going to shut down laptop and rest now. Probably won't return to it for a while but I should at least have this part fixed later on today. I have to of course update all the json files which might take a bit more time but I'd think with `sed` I can do it relatively easily once I find all the patterns of the twitter handles.

**Comment by xexyl** [comment]
With commits https://github.com/ioccc-src/mkiocccentry/pull/432/commits/5c391c3de99fd1a7babd67d5b10dc61f0e11fa00 this issue should be entirely resolved. See also comment https://github.com/ioccc-src/mkiocccentry/pull/432#issuecomment-1332103685 as I forgot to note something in the log.

Bonus question in the commit:

> Trivia question: what is the difference between Twitter and the SpaceX
> Starship rockets SN3, SN4, SN7, SN8, SN9, SN10, SN11 and probably
> others? Musk hasn't successfully blown Twitter up yet.

Yes it's mean but I'm irritated at him very much and I'm easily amused (often dark, cynical, even sardonic).

**Comment by xexyl** [comment]
Glad you got a laugh out of the joke. I knew you would. Here’s something I did with ut. 

![618C2581-32C1-4631-B978-96654E5AC70D](https://user-images.githubusercontent.com/53008573/205022506-cfd233e4-c44f-4aae-ade8-5eaf0454913d.jpeg)

Very mean I know but …

Going to rest again. Hope you’re sleeping well!

**Comment by xexyl** [comment]
Oh and I meant to say that I am honoured that not only did you follow me on mastodon but you also made it so IOCCC account also followed me! I am honoured! Thank you. 

Well really going to try resting now. BCNU! :)

**Comment by xexyl** [comment]
Not important: I just wanted to say that I really hate that this issue arose and since Musk irritates you too... Well I don't totally hate it: the above [comment 1333507557](https://github.com/ioccc-src/mkiocccentry/issues/431#issuecomment-1333507557) is nice of course. But you know what I mean.

I just updated my website to not have tweets: instead screenshots. Time consuming and tedious. At least I added some commentary to the Enigma machine entry.

This change is due to the fact that he made it so people not logged in can look at tweets though I managed somehow to get a picture that I tweeted demonstrating the drawing mode of Snake.

It does remind me though of this fact. Twitter was, possibly due to the above change of requiring users to log in, DoSing itself. 

![Screenshot 2023-07-18 at 09 48 10](https://github.com/ioccc-src/mkiocccentry/assets/53008573/4969d87c-7e5f-4169-8e8a-761731749db9)

That is ineptitude for you courtesy of you know who.

**Comment by SirWumpus** [comment]
Now that Bluesky is open, https://bsky.social/about, is it worth creating an account there too?

**Comment by xexyl** [comment]
> Now that Bluesky is open, https://bsky.social/about, is it worth creating an account there too?

But why? If you mean the judges should also open an account that would mean they would have to post updates on both places and the website. And if you mean for the submitters to add that would require at least the following:

- updating many many json test files
- updating the mkiocccentry tool to ask for it
- updating the chkentry semantics tables and functions
- more testing for all of the above
- and there are other things too I'm sure: the above are just what popped into my head immediately

All of these would take more time away from the contest and what would it serve when there is already a place for updates? If someone wants to tell the judges that they're on this new site they can do that for their url or alt url. Anything else is just taking time away from the next contest and many want it soon.
