### ISSUE TITLE
Enhancement: consistency across files post code freeze but prior to public review

### ISSUE THREAD

**Issue by xexyl** [ioccc-src/mkiocccentry#458]
A long while back you asked me for help with this: going through all files for typos and other consistency things. I think it might be good to discuss some of the things though so I'm opening this issue (please assign it to me).

For right now I will mention three things but there are others.

## displaying default of options

In some files (scripts and binaries) we have text like:

```sh
$ ./bug_report.sh -h 2>&1|grep def:
    -D level		    set verbosity level for tests (def: 0)
    -t			    disable make actions (def: run make actions)
```

Should we have the `def: ` part? I'm not sure. I recall a long time ago seeing some tools just have in parentheses the default without specifying `default: ` or some variation. On the other hand it might be that we don't need to specify the default: perhaps the fact there's an option to enable said feature would indicate that the default is not this? Of course in some cases like paths it might be good to have the default though whether we need to have a text indicating the default or not is up to discussion I would think.

## man page formatting

I have mentioned something about this in one of the man page issues about whether we do the `\fB..\fP` or `.B` (bold for example). I noted how one can do the `.B` without having the punctuation being made bold/italic/whatever (only a problem for when it's the last part of a sentence). What is certain is that both forms exist so it should probably be the same across. I'm not sure which is ideal. Some say that the `.B` is better because it's easier for tools to parse but I don't know if this matters. What do you prefer Landon?

## the special file - you know what I refer to

Before we freeze things I'll go through this file and clean it up. Also if you want to add anything you can.

## other things ?

Other things can be discussed here later. Obviously we don't have to discuss typos. I'll fix those before we freeze things.

**Comment by lcn2** [comment]
> displaying default of options

In many cases, "(def: foo)" is a very compact way of explaining what happens when the option is not used. And thus it should be kept in the help section.

**Comment by lcn2** [comment]
> Some say that the .B is better because it's easier for tools to parse but I don't know if this matters. What do you prefer Landon?

We have used things like ".B", ".BR", etc. That's what we are used to seeing in man pages. 

There are times when a tricky formatting needs the "\fB...\fI", but that should be the exception, not the rule.

**Comment by lcn2** [comment]
See some of the unchecked items in the "Release 0.9.9 actions" section of issue #87. Multiple of those items fall under this issue.

**Comment by xexyl** [comment]
> > displaying default of options
> 
> In many cases, "(def: foo)" is a very compact way of explaining what happens when the option is not used. And thus it should be kept in the help section.
> 
> The use of "def:" inside parentheses is also important as there may be other things (a notice like this), that are in the line.

Sure. I think the issue is a lack of consistency with saying what the default is. Is this not an issue for you?

**Comment by xexyl** [comment]
> > Some say that the .B is better because it's easier for tools to parse but I don't know if this matters. What do you prefer Landon?
> 
> We have used things like ".B", ".BR", etc. That's what we are used to seeing in man pages.
> 
> There are times when a tricky formatting needs the "\fB...\fI", but that should be the exception, not the rule.

I've seen both - a lot. But when I go over all the man pages (they're not all ready for it - see the issue I opened yesterday that you closed but I don't think was finished including about the json semantics tables but also installation of man pages) I can do this.

**Comment by xexyl** [comment]
> See some of the unchecked items in the "Release 0.9.9 actions" section of issue #87. Multiple of those items fall under this issue.

Of course. But not all unless you added some I guess. This is easier for me to look at too as these are things I know that I must do. But of course there will be things in the other issue that I'll be doing too.

**Comment by lcn2** [comment]
> Sure. I think the issue is a lack of consistency with saying what the default is. Is this not an issue for you?

While some options (def: ...) might be obvious, adding missing defaults where reasonable would be a good thing to do.

**Comment by lcn2** [comment]
With commit 45e18efbb0a729a6ee2e1df9a2e83a76c45951f4

While not technically a consistency, jparse is now isolated from soup, test_ioccc and the top level mkiocccentry.   The _JSON parser_ now only uses/depends on dbg and dyn_alloc.

**Comment by lcn2** [comment]
Is there anything else that needs to be done for this enhancement, or is it ready to close?

**Comment by xexyl** [comment]
There's plenty that has to be done yes.

Man page formatting and also wording consistencies is a great example.

Fixing all typos and things like that. Wording consistencies across the repo also.

But I need to know that everything need not change before I go ahead and do these types of things.

**Comment by xexyl** [comment]
... that being said: I am working on some consistency in some Makefile rules across all Makefiles.

I'll have a pull request later on today. Probably all I'll do today too but then I don't really know what else to do right now. Soon I'll be away for a bit and I hope to finish this after I get back.

**Comment by xexyl** [comment]
Now as far as this issue goes in general.

Do we have a list of files that will not need to be changed? If so I can start going over those files and I can keep track of the files I have gone through so I don't repeat it. I think for the man pages I should wait until the other man page issue is resolved (json semantics tables description).

I guess that many files are 'done' though. The txzchk I don't imagine I'd need to change anything for example.

There are two ways to go about this issue that I can think of.

The first one is that I don't go through it as much as we originally thought: for instance if I see typos that's fine; if I see a consistency issue I fix it but otherwise don't worry about it.

The other one is I do go over it and fix typos and consistencies.

I think what I need to know is when you want these things ready by. I could probably dedicate at least an hour a day doing this and once everything is in a state where nothing needs to change I should probably be able to go through it fairly quickly. I think the man page consistency might be the slowest one actually - esp with formatting. Some days I would be able to give more than an hour to this. Of course some days there might be that I wouldn't be able to do much at all.

As far as what I prefer: I hate having typos and inconsistencies so I'd at least like to have a look through but if it also depends on how soon it has to be done after we're in a state where changes do not have to be made. 

Of course I could do a bit of both: go through them quicker than I might otherwise but then later on when things can happen not so quickly I could have a proper go. But there is a problem with that in that I would very possibly have to go through some of it more than once.

Just some thoughts to consider as far as how to proceed with this issue.

And now I really am going to do other things for the day.

**Comment by xexyl** [comment]
One issue I just discovered but not sure what to change it to.


In `soup/chk_sem_auth.c` there's a comment that says:

```c
 * and it was auto-generated by:
 *
 *      make chk_sem_auth.c
 *
```

but this file is manually edited, right? What should it be changed to? 

I thought there was another issue here but it's escaped my mind for now. I'd probably be watching something and thus unable to do anything here but it's raining which is a rare treat - so I'm listening to the rain. But I think I am tired enough where I should do something else anyway so this is it for now.

**Comment by lcn2** [comment]
> One issue I just discovered but not sure what to change it to.
> 
> In `soup/chk_sem_auth.c` there's a comment that says:
> 
> ```c
>  * and it was auto-generated by:
>  *
>  *      make chk_sem_auth.c
>  *
> ```
> 
> but this file is manually edited, right? What should it be changed to?
> 
> I thought there was another issue here but it's escaped my mind for now. I'd probably be watching something and thus unable to do anything here but it's raining which is a rare treat - so I'm listening to the rain. But I think I am tired enough where I should do something else anyway so this is it for now.

If you do:

```bash
$ cd soup
$ make clean_mkchk_sem
rm -f chk_sem_info.c chk_sem_info.h chk_sem_info.o
rm -f chk_sem_auth.c chk_sem_auth.h chk_sem_auth.o
```

And then:

```bash
$ make mkchk_sem
rm -f chk_sem_info.c
../jparse/jsemcgen.sh -N sem_info -P chk -j ../jparse/jsemtblgen -- \
	    ../test_ioccc/test_JSON/info.json/good/info.reference.json chk.info.head.c \
	    chk.info.ptch.c chk.info.tail.c chk_sem_info.c
rm -f chk_sem_info.h
../jparse/jsemcgen.sh -N sem_info -P chk -I -j ../jparse/jsemtblgen -- \
	    ../test_ioccc/test_JSON/info.json/good/info.reference.json chk.info.head.h \
	    chk.info.ptch.h chk.info.tail.h chk_sem_info.h
rm -f chk_sem_auth.c
../jparse/jsemcgen.sh -N sem_auth -P chk -j ../jparse/jsemtblgen -- \
	    ../test_ioccc/test_JSON/auth.json/good/auth.reference.json chk.auth.head.c \
	    chk.auth.ptch.c chk.auth.tail.c chk_sem_auth.c
rm -f chk_sem_auth.h
../jparse/jsemcgen.sh -N sem_auth -P chk -I -j ../jparse/jsemtblgen -- \
	    ../test_ioccc/test_JSON/auth.json/good/auth.reference.json chk.auth.head.h \
	    chk.auth.ptch.h chk.auth.tail.h chk_sem_auth.h
```

You will see how the files are generated by `jsemcgen.sh`.

So perhaps the comment should updated to say "auto-generated by: ... jsemcgen.sh"?

If so, editing `chk.info.head.c` and `chk.auth.head.c` and then `make clean_mkchk_sem mkchk_sem` should address that.

**Comment by lcn2** [comment]
> Do we have a list of files that will not need to be changed? 

The "not need to be changed" phase would be when we switch to version 1.0.0 .. where "not need" is more like "will really try to not edit" as we enter an effective "code freeze" in version 1.0.x (where the .x might be non-zero because issues are discovered by the public that need to be fixed).

**Comment by xexyl** [comment]
> > One issue I just discovered but not sure what to change it to.
> > In `soup/chk_sem_auth.c` there's a comment that says:
> > ```c
> >  * and it was auto-generated by:
> >  *
> >  *      make chk_sem_auth.c
> >  *
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but this file is manually edited, right? What should it be changed to?
> > I thought there was another issue here but it's escaped my mind for now. I'd probably be watching something and thus unable to do anything here but it's raining which is a rare treat - so I'm listening to the rain. But I think I am tired enough where I should do something else anyway so this is it for now.
> 
> If you do:
> 
> ```shell
> $ cd soup
> $ make clean_mkchk_sem
> rm -f chk_sem_info.c chk_sem_info.h chk_sem_info.o
> rm -f chk_sem_auth.c chk_sem_auth.h chk_sem_auth.o
> ```
> 
> And then:
> 
> ```shell
> $ make mkchk_sem
> rm -f chk_sem_info.c
> ../jparse/jsemcgen.sh -N sem_info -P chk -j ../jparse/jsemtblgen -- \
> 	    ../test_ioccc/test_JSON/info.json/good/info.reference.json chk.info.head.c \
> 	    chk.info.ptch.c chk.info.tail.c chk_sem_info.c
> rm -f chk_sem_info.h
> ../jparse/jsemcgen.sh -N sem_info -P chk -I -j ../jparse/jsemtblgen -- \
> 	    ../test_ioccc/test_JSON/info.json/good/info.reference.json chk.info.head.h \
> 	    chk.info.ptch.h chk.info.tail.h chk_sem_info.h
> rm -f chk_sem_auth.c
> ../jparse/jsemcgen.sh -N sem_auth -P chk -j ../jparse/jsemtblgen -- \
> 	    ../test_ioccc/test_JSON/auth.json/good/auth.reference.json chk.auth.head.c \
> 	    chk.auth.ptch.c chk.auth.tail.c chk_sem_auth.c
> rm -f chk_sem_auth.h
> ../jparse/jsemcgen.sh -N sem_auth -P chk -I -j ../jparse/jsemtblgen -- \
> 	    ../test_ioccc/test_JSON/auth.json/good/auth.reference.json chk.auth.head.h \
> 	    chk.auth.ptch.h chk.auth.tail.h chk_sem_auth.h
> ```
> 
> You will see how the files are generated by `jsemcgen.sh`.
> 
> So perhaps the comment should updated to say "auto-generated by: ... jsemcgen.sh"?
> 
> If so, editing `chk.info.head.c` and `chk.auth.head.c` and then `make clean_mkchk_sem mkchk_sem` should address that.

True. I did of course have to use that rule. I'll look at this tomorrow I hope.

**Comment by xexyl** [comment]
> > Do we have a list of files that will not need to be changed?
> 
> The "not need to be changed" phase would be when we switch to version 1.0.0 .. where "not need" is more like "will really try to not edit" as we enter an effective "code freeze" in version 1.0.x (where the .x might be non-zero because issues are discovered by the public that need to be fixed).

Okay. Well when we're ready for me to look at the files I will do it: whatever that means.

I guess (unrelated) you accidentally did the 'thumbs down' to the above comment I made?

**Comment by lcn2** [comment]
> I guess (unrelated) you accidentally did the 'thumbs down' to the above comment I made?

We are in a _clickly_ mood today 😁 ...

... actually we are in the process of trying to finish up some of our actions as we anticipate not being able to do much on reps until 2023 Jan 20 (due to having to prepare to give a class lecture on relativity to a high school pjysics: along the lines of a condensed version we received from Feynman many years ago) .. so soon we will start to slow down and then pause in our work in this repo.

**Comment by xexyl** [comment]
> > I guess (unrelated) you accidentally did the 'thumbs down' to the above comment I made?
> 
> We are in a _clickly_ mood today 😁 ...
> 
> ... actually we are in the process of trying to finish up some of our actions as we anticipate not being able to do much on reps until 2023 Jan 20 (due to having to prepare to give a class lecture on relativity to a high school pjysics: along the lines of a condensed version we received from Feynman many years ago) .. so soon we will start to slow down and then pause in our work in this repo.

No worries and best of luck with that!

**Comment by xexyl** [comment]
Question for you ... as you see I made a couple typo fixes in the readme file. But I also noticed you wrote:

> an mkiocccentry tool directory

Now this is interesting. One would say an M and thus an M K I ... but do you not read `mk` as make? I have always read it as make ioccc entry. Do you not? It's certainly up to debate whether it should be `an mkiocccentry` or `a mkiocccentry` but since I noticed it I figured I'd bring it up. I didn't change it so that we could discuss this.

And now I unfortunately do have to move my kitty as I need sleep :(

**Comment by xexyl** [comment]
> And now I unfortunately do have to move my kitty as I need sleep :(

I believe you like cats so here's a picture. Certainly I have a lot more adorable pictures but his face is not visible here so that makes sense.

![IMG_4424](https://user-images.githubusercontent.com/53008573/211442125-8fdb22f8-06c4-4197-9a8b-9f51ddba0321.jpeg)

**Comment by lcn2** [comment]
> Question for you ... as you see I made a couple typo fixes in the readme file. But I also noticed you wrote:
> 
> > an mkiocccentry tool directory
> 
> Now this is interesting. One would say an M and thus an M K I ... but do you not read `mk` as make? I have always read it as make ioccc entry. Do you not? It's certainly up to debate whether it should be `an mkiocccentry` or `a mkiocccentry` but since I noticed it I figured I'd bring it up. I didn't change it so that we could discuss this.

Yes, _mk_ is often pronounced as "make", so the name _mkiocccentry_ is produced "mk IOCCC entry".

Nevertheless  _mkiocccentry_ may be **mispronounced** as "make iocc centry" 🤓

> And now I unfortunately do have to move my kitty as I need sleep :(

🐈

**Comment by lcn2** [comment]
What else, if anything, needs to be done for this issue #458?

With the exception of this unchecked items left in issue #87 (and thus may be addressed under that issue), are we ready to close this issue?

**Comment by xexyl** [comment]
> > Question for you ... as you see I made a couple typo fixes in the readme file. But I also noticed you wrote:
> > > an mkiocccentry tool directory
> > 
> > 
> > Now this is interesting. One would say an M and thus an M K I ... but do you not read `mk` as make? I have always read it as make ioccc entry. Do you not? It's certainly up to debate whether it should be `an mkiocccentry` or `a mkiocccentry` but since I noticed it I figured I'd bring it up. I didn't change it so that we could discuss this.
> 
> Yes, _mk_ is often pronounced as "make", so the name _mkiocccentry_ is produced "mk IOCCC entry".
> 

Right.

> Nevertheless _mkiocccentry_ may be **mispronounced** as "make iocc centry" 🤓 (the choice of the name with this ability to mispronounce was deliberate).

Interesting thought .. though everyone participating in the contest knows it's IOCCC entry. But what is centry ? A deliberate misspelling of sentry ? Either way what's the joke ? 

I still think it would read more naturally as `a mkiocccentry` though. Are you against this because of said joke (I guess it's a joke)?


> 
> > And now I unfortunately do have to move my kitty as I need sleep :(
> 
> 🐈

:-)

**Comment by xexyl** [comment]
> What else, if anything, needs to be done for this issue #458?
> 
> With the exception of this unchecked items left in issue #87 (and thus may be addressed under that issue), are we ready to close this issue? You may wish to re-read the issue #87 checklist to be sure.
> 
> Perhaps if there are some matters still pending for the issue, we should instead add checkbox items to issue #87 instead and close this issue?

Well you might add in section `Code complete review: (once all above Release 0.9.9 actions done)` under `Review all documentation: update documentation as needed` something like:

> Have @xexyl go through all files to check for consistency problems and typos

?

Of course I would go through the documentation too at the same time.

Would that work? If so then you can let me know when you're ready for me to do that: when no other functional changes have to be made and preferably when no other changes at all have to be made.

**Comment by xexyl** [comment]
Replying to your updates ...

> What else that needs to be done for this enhancement?
> 

> ### UPDATE 0
> See also [comment 1373369176](https://github.com/ioccc-src/mkiocccentry/issues/87#issuecomment-1373369176).
> 

Of course. Read that the other day. Thank you.

> ### UPDATE 1
> We recommend you check the `README.md` as per commit [b45f653](https://github.com/ioccc-src/mkiocccentry/commit/b45f6535a7c95e1793b6354a94670461fe444d05)
> 
Yes it looks good though I imagine we'll have to update that part of it later on - even besides the fact not all the details are there.

> ### UPDATE 2
> There is that special file update you wanted to do.

Indeed. I'm hoping to do some of that today. Do you want to have fun with it too ?

**Comment by xexyl** [comment]
> > Do we have a list of files that will not need to be changed?
> 
> The "not need to be changed" phase would be when we switch to version 1.0.0 .. where "not need" is more like "will really try to not edit" as we enter an effective "code freeze" in version 1.0.x (where the .x might be non-zero because issues are discovered by the public that need to be fixed).
> 

Yes I should have named the issue more like '.... post code freeze prior to a public review'.

> ### UPDATE 0
> The updating of version numbers will likely cause a number of _test files_ and `version.h` (and friends) to update, and this will happen during the "Code complete review" phase as noted in issue #87

Of course. But I don't think that will matter here?

**Comment by xexyl** [comment]
> > One issue I just discovered but not sure what to change it to.
> > In `soup/chk_sem_auth.c` there's a comment that says:
> > ```c
> >  * and it was auto-generated by:
> >  *
> >  *      make chk_sem_auth.c
> >  *
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but this file is manually edited, right? What should it be changed to?
> > I thought there was another issue here but it's escaped my mind for now. I'd probably be watching something and thus unable to do anything here but it's raining which is a rare treat - so I'm listening to the rain. But I think I am tired enough where I should do something else anyway so this is it for now.
> 
> If you do:
> 
> ```shell
> $ cd soup
> $ make clean_mkchk_sem
> rm -f chk_sem_info.c chk_sem_info.h chk_sem_info.o
> rm -f chk_sem_auth.c chk_sem_auth.h chk_sem_auth.o
> ```
> 
> And then:
> 
> ```shell
> $ make mkchk_sem
> rm -f chk_sem_info.c
> ../jparse/jsemcgen.sh -N sem_info -P chk -j ../jparse/jsemtblgen -- \
> 	    ../test_ioccc/test_JSON/info.json/good/info.reference.json chk.info.head.c \
> 	    chk.info.ptch.c chk.info.tail.c chk_sem_info.c
> rm -f chk_sem_info.h
> ../jparse/jsemcgen.sh -N sem_info -P chk -I -j ../jparse/jsemtblgen -- \
> 	    ../test_ioccc/test_JSON/info.json/good/info.reference.json chk.info.head.h \
> 	    chk.info.ptch.h chk.info.tail.h chk_sem_info.h
> rm -f chk_sem_auth.c
> ../jparse/jsemcgen.sh -N sem_auth -P chk -j ../jparse/jsemtblgen -- \
> 	    ../test_ioccc/test_JSON/auth.json/good/auth.reference.json chk.auth.head.c \
> 	    chk.auth.ptch.c chk.auth.tail.c chk_sem_auth.c
> rm -f chk_sem_auth.h
> ../jparse/jsemcgen.sh -N sem_auth -P chk -I -j ../jparse/jsemtblgen -- \
> 	    ../test_ioccc/test_JSON/auth.json/good/auth.reference.json chk.auth.head.h \
> 	    chk.auth.ptch.h chk.auth.tail.h chk_sem_auth.h
> ```
> 
> You will see how the files are generated by `jsemcgen.sh`.
> 
> So perhaps the comment should updated to say "auto-generated by: ... jsemcgen.sh"?
> 
> If so, editing `chk.info.head.c` and `chk.auth.head.c` and then `make clean_mkchk_sem mkchk_sem` should address that.

This is done though not committed yet. I want to go through that special file first .. but right now I'm quite tired. I know I probably can't sleep but I might try resting a bit. I doubt I'll be able to do that even but either way I'll return to this in a while.

**Comment by xexyl** [comment]
> ### UPDATE 2
> There is that special file update you wanted to do.

Done.

**Comment by lcn2** [comment]
> But what is centry ?

100 years without u 🙂?
A sentry you can c 🙂?

Who knows 😬

**Comment by xexyl** [comment]
> > But what is centry ?
> 
> 100 years without u 🙂? A sentry you can c 🙂?
> 
> Who knows 😬

Well that's not what I expected. Does that mean it's up to interpretation (including it's a secret) or does it mean that you don't even know ?

**Comment by lcn2** [comment]
> Well you might add in section Code complete review: (once all above Release 0.9.9 actions done) under Review all documentation: update documentation as needed something like:
> 
> Have @xexyl go through all files to check for consistency problems and typos
> ?

Done. See issue #87.

**Comment by lcn2** [comment]
> Would that work? If so then you can let me know when you're ready for me to do that: when no other functional changes have to be made and preferably when no other changes at all have to be made.

Apart from issue #475, we are not planning to add anything new.  Maybe a bug fix, when a problem turns up, might be needed, but even that should be minimal. And if such things need to be done, we will do them via a new bug report being filed.

Now is a good time for you, @xexyl, to start on the new
unchecked items of issue #87 in the _Release 0.9.9 actions_ section.  We recommend you priority on things higher up on the list where reasonable. 

We need to focus on the relativity class we are teaching next week, so until the end of next week our activities in this repo will be reduced.

**Comment by lcn2** [comment]
> Well that's not what I expected. Does that mean it's up to interpretation (including it's a secret) or does it mean that you don't even know ?

It was an ambiguity we heard in our mind without respect to spelling, and decided maintain (as opposed to changing the spelling of _mkiocccentry_ or picking a different name).  So can truly say that the name means? 😬

Feel free to add this to a new _HISTORY_ section to the _mkiocccentry(1)_ msn page.

**Comment by xexyl** [comment]
> > Well that's not what I expected. Does that mean it's up to interpretation (including it's a secret) or does it mean that you don't even know ?
> 
> It was an ambiguity we heard in our mind without respect to spelling, and decided maintain (as opposed to changing the spelling of _mkiocccentry_ or picking a different name). So can truly say that the name means? 😬
> 
> Feel free to add this to a new _HISTORY_ section to the _mkiocccentry(1)_ msn page.

You mean the part about how it might be read as 'IOC centry' ?

But then I'm not really even sure what to say about it. That being said I was thinking earlier I could maybe modify the README a bit. But not today. Maybe I can do that tomorrow too.

Good luck with the other things you have to do!

**Comment by lcn2** [comment]
Given all the above, it sounds like we can close this issue?

**Comment by xexyl** [comment]
> Given all the above, it sounds like we can close this particular issue.

Well since it's referred to in the other issue I suppose so yes.
