### ISSUE TITLE
Enhancement: add separate dyn_array man pages

### ISSUE THREAD

**Issue by xexyl** [ioccc-src/mkiocccentry#459]
I noted in a comment earlier today that I haven't yet made separate man pages for the dyn_array facility. This might be less important for now but it'll be important for when you create a repo specifically.

I did write a man page for the whole thing (though there's certainly room for improvement). But how do you wish me to break these functions up?

```
       #include "dyn_array.h"

       #define dyn_array_value(array_p, type, index) (((type *)(((struct dyn_array *)(array_p))->data))[(index)])
       #define dyn_array_addr(array_p, type, index) (((type *)(((struct dyn_array *)(array_p))->data))+(index))
       #define dyn_array_tell(array_p) (((struct dyn_array *)(array_p))->count)
       #define dyn_array_beyond(array_p, type) (dyn_array_addr(array_p, type, dyn_array_tell(array_p)))
       #define dyn_array_alloced(array_p) (((struct dyn_array *)(array_p))->allocated)
       #define dyn_array_avail(array_p) (dyn_array_alloced(array_p) - dyn_array_tell(array_p))
       #define dyn_array_rewind(array_p) (dyn_array_seek((struct dyn_array *)(array_p), 0, SEEK_SET))

       extern struct dyn_array *dyn_array_create(size_t elm_size, intmax_t chunk, intmax_t start_elm_count, bool zeroize);
       extern bool dyn_array_append_value(struct dyn_array *array, void *value_to_add);
       extern bool dyn_array_append_set(struct dyn_array *array, void *array_to_add_p, intmax_t count_of_elements_to_add);
       extern bool dyn_array_concat_array(struct dyn_array *array, struct dyn_array *other);
       extern bool dyn_array_seek(struct dyn_array *array, off_t offset, int whence);
       extern void dyn_array_clear(struct dyn_array *array);

       extern void dyn_array_free(struct dyn_array *array);

```

My guess is that the append and concat should go together. If so what should be the function that the man page is of (and so what file to link to)?

I could take some other guesses but I'll let you decide as I want to go do other things now. Before I do go though there's one other thing I wonder - just thought of this.

Should we have a man page for `dbg.h` and `dyn_array.h` ?

**Comment by lcn2** [comment]
> Should we have a man page for dbg.h and dyn_array.h ?

Probably not a separate man page for the include files, just a mention in the main man page perhaps.

**Comment by lcn2** [comment]
With commit 90597f585a5b56f274e98fe31beb322354ab33d7 we are going to close this issue (for now).

On further reflection, splitting up the dyn_alloc(3) seemed to not be a important thing to do (for now).
We did make some minor improvements to the man page set, and fixed the .gitignore issue.

**Comment by xexyl** [comment]
> With commit [90597f5](https://github.com/ioccc-src/mkiocccentry/commit/90597f585a5b56f274e98fe31beb322354ab33d7) we are going to close this issue (for now).
> 
> On further reflection, splitting up the dyn_alloc(3) seemed to not be a important thing to do (for now). 

I was wondering about that. But will it be useful at some point?

> We did make some minor improvements to the man page set, and fixed the .gitignore issue.

That's good. But you also prematurely closed the man page issue about the json semantics tables as well as the make install of man pages: it doesn't install all dbg man pages.

Should I recreate the issue or issues or should I just make a comment in the closed issue or issues (not sure how many there are)?

**Comment by lcn2** [comment]
> With commit 90597f5 we are going to close this issue (for now).
> 
> On further reflection, splitting up the dyn_alloc(3) seemed to not be a important thing to do (for now).
> I was wondering about that. But will it be useful at some point?

It doesn't seem useful at the moment.

**Comment by xexyl** [comment]
> > With commit [90597f5](https://github.com/ioccc-src/mkiocccentry/commit/90597f585a5b56f274e98fe31beb322354ab33d7) we are going to close this issue (for now).
> > On further reflection, splitting up the dyn_alloc(3) seemed to not be a important thing to do (for now).
> > I was wondering about that. But will it be useful at some point?
> 
> It doesn't seem useful at the moment.

That's fine.

Expect a pull request soon with several fixes and enhancements. It might be all I do today .. not sure. It was a very difficult night and yesterday was also.

**Comment by lcn2** [comment]
> But you also prematurely closed the man page issue about the json semantics tables as well as the make install of man pages: it doesn't install all dbg man pages.
> 
> Should I recreate the issue or issues or should I just make a comment in the closed issue or issues (not sure how many there are)?

It sounds like two new issues should be raised if you think there are issues.

**Comment by xexyl** [comment]
> > But you also prematurely closed the man page issue about the json semantics tables as well as the make install of man pages: it doesn't install all dbg man pages.
> > Should I recreate the issue or issues or should I just make a comment in the closed issue or issues (not sure how many there are)?
> 
> It sounds like two new issues should be raised if you think there are issues.

Or I could find them and you could re-open them I guess. I'll see if I can do that in a bit.
