### ISSUE TITLE
Enhancement: manage and reduce the verbosity of Makefiles

### ISSUE THREAD

**Issue by lcn2** [ioccc-src/mkiocccentry#461]
Reduce the verbosity of Makefiles, by default.  Use and/or add Makefile variables to allow one to "turn on debugging".

**Comment by lcn2** [comment]
See commit ae19a4fd84b18a334fbbccac05b47337dd587b31

Added Q_V_OPTION to Makefiles.  This value is 0 when Q is @ other 1.
This value may be used to control if one uses -v 0 or -v 1.

Fixed the build_man to change "${V} @echo" to  "${V} @echo".

Changed `make depend` to be silent by default.  To restore
the previous "more verbose" move, try:

```sh
make depend Q= V=@
```

Recall, ${Q} controls if make will echo an action command. For example:

```make
some_rule:
        ${Q} rm -f filename
```

The make command will NOT echo the rm command when Q=@.  The command
will be performed in this case, just not echoed to stdout.  By default: Q=@.

Recall, ${V} control if an echo message will be sent.  For example:

```make
some_rule:
        ${V} echo
        ${V} echo some message
        ${V} echo
```

The echo will not happen when V=@: By default, V=@:.

The ${V} is used in front of commands to prevent their being echoed by default.
The ${Q} is used in front of echo messages to prevent them from printing.

To restore command echoing, set ${Q} to empty: Q=
To restore debugging echos, set $(V) as: V=@

For the rules: jparse.tab.c jparse.tab.h jparse.tab.c jparse.tab.h
the ${Q_V_OPTION} to control if -v 0 or -v 1 is used when running
`run_bison.sh` or `run_flex.sh`.

Fixed `run_bison.sh` to only echo statements and use cp -v when
the -v level is >= 1.  Previously there were messages and cp -v
output that occurred no matter what.

Fixed `run_flex.sh` to only echo statements and use cp -v when
the -v level is >= 1.  Previously there were messages and cp -v
output that occurred no matter what.

TODO: Consider if the changes to `make depend` should be applied
      to some other make actions.

TODO: When bug_report.sh run, be sure that full debugging of
      Makefiles is enabled.

**Comment by lcn2** [comment]
We are not sure if a completely silent `make depend` by default is the best thing.  It might be OK because:

NOTE: If `make depend` **DOES** change a Makefile, then messages that "Makefile dependencies updated" and "Previous version may be found in: Makefile.orig" will STILL be printed.  If `make depend` does nothing, then nothing is printed.

**Comment by lcn2** [comment]
To reduce the verbosity of `make clobber` we added commit 36d9342d3e059c3aa118440598cef568db1140f1.

Removed prep_clean and prep_clobber Makefile rules

The prep_clean and prep_clobber Makefile rules are no longer needed.
The were added a while ago when the Makefile system was not very good.
Now that they are no longer needed, the rules have been removed.

**Comment by lcn2** [comment]
Should the changes discussed in [comment 1370794652l](urhttps://github.com/ioccc-src/mkiocccentry/issues/461#issuecomment-1370794652l) be applied `make clean` and `make clobber`?

Perhaps not: we are not sure.

Given the above change, `make clean` is not very verbose.

The `make clobber` is a bit more verbose because the `make clean` is also performed.

We are not sure.

**Comment by lcn2** [comment]
With commit 7659a144ab77a00f43278f4c323dbde980cf13bb

reduce make test verbosity due to the Makefiles

The Makefile verbosity of `make test` has been greatly reduced.

Changed `make test` to be silent by default.  To restore
the previous "more test" move, try:

```sh
make test Q= V=@
```
To further reduce the `make test` verbosity, the test rule
no longer depends on all.  In some cases the test rule tests if
the critical tool is executable.  If it is not, it tries to make it
after which if the tool is still not executable, exits with an
error message.  This is NOT done for all Makefiles, nor for
all things made by make all.

The idea of `make test` is to test the current condition.
The above makes are there to be slightly helpful AND
print nothing if the critical tool already exists.

To proper test the entire tree:

```sh
make clobber all test
```

**Comment by xexyl** [comment]
Please assign this to me too if you like.

**Comment by xexyl** [comment]
> Reduce the verbosity of Makefiles, by default. Use and/or add Makefile variables to allow one to "turn on debugging".

As far as this goes there is one that I find troublesome while we're working out problems (and I discovered another one yesterday): namely the option `--no-print-director` because unfortunately it quiets `-w` even when explicitly enabled. This was very useful. I know one can do:

```sh
$ make MAKE_CD_Q= -w
```

but this is more problematic when we're running it from a script (directly). But it seems like maybe you resolved this problem I am thinking of - or else it's because it was silenced.

That's another possible concern: maybe we should not silence as many things until we're sure that all rules have no problems? I don't know.

**Comment by lcn2** [comment]
> > Reduce the verbosity of Makefiles, by default. Use and/or add Makefile variables to allow one to "turn on debugging".
> 
> 
> 
> As far as this goes there is one that I find troublesome while we're working out problems (and I discovered another one yesterday): namely the option `--no-print-director` because unfortunately it quiets `-w` even when explicitly enabled. This was very useful. I know one can do:
> 
> 
> 
> ```sh
> 
> $ make MAKE_CD_Q= -w
> 
> ```
> 
> 
> 
> but this is more problematic when we're running it from a script (directly). But it seems like maybe you resolved this problem I am thinking of - or else it's because it was silenced.
> 
> 
> 
> That's another possible concern: maybe we should not silence as many things until we're sure that all rules have no problems? I don't know. 

Probably the `bug_report.sh`, when it invoking make commands, should in addition to doing `Q= V=@` it should also probably do `MAKE_CD_Q=` as well.

**Comment by xexyl** [comment]
> > > Reduce the verbosity of Makefiles, by default. Use and/or add Makefile variables to allow one to "turn on debugging".
> > 
> > 
> > As far as this goes there is one that I find troublesome while we're working out problems (and I discovered another one yesterday): namely the option `--no-print-director` because unfortunately it quiets `-w` even when explicitly enabled. This was very useful. I know one can do:
> > ```shell
> > $ make MAKE_CD_Q= -w
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but this is more problematic when we're running it from a script (directly). But it seems like maybe you resolved this problem I am thinking of - or else it's because it was silenced.
> > That's another possible concern: maybe we should not silence as many things until we're sure that all rules have no problems? I don't know.
> 
> Probably the `bug_report.sh`, when it invoking make commands, should in addition to doing `Q= V=@` it should also probably do `MAKE_CD_Q=` as well.

That's a good idea.

**Comment by xexyl** [comment]
> Should the changes discussed in comment 1370794652l be applied `make clean` and `make clobber`? We are inclined to not silence `make clean` and `make clobber`. We are included to leave them as they are now.
> 
> Given the above change, `make clean` is not very verbose.
> 
> The `make clobber` is a bit more verbose because the `make clean` is also performed as part of the rule.

I'm not sure if it should be silent or not. It might make it less to look at when we're doing work on the repo which could be a good thing. And if we silence some of the compiling (if we do) why not clobber? The compiling might be more useful to see than the clobber I would think?

**Comment by xexyl** [comment]
> See commit [ae19a4f](https://github.com/ioccc-src/mkiocccentry/commit/ae19a4fd84b18a334fbbccac05b47337dd587b31)
> 

These changes I might have more general thoughts on (and/or questions) but for another time.
 
> TODO: Consider if the changes to `make depend` should be applied to some other make actions.

I think for some actions it probably should but nothing comes to mind just yet.
> 
> TODO: When bug_report.sh run, be sure that full debugging of Makefiles is enabled.

That's done and committed - 5b62287cd05be4f732736f4f36751845acc21191 - with an option to change the make flags in the case it's needed.

**Comment by xexyl** [comment]
> Is a silent `make depend` by default a good thing? It might be OK because:
> 
> NOTE: If `make depend` **DOES** change a Makefile, then messages that "Makefile dependencies updated" and "Previous version may be found in: Makefile.orig" will STILL be printed. If `make depend` does nothing, then nothing is printed.

It might be good if it says a general `make depend starting` and `make depend finished` or something like that? I'm not sure. But I think that having it for each directory might be overdoing it. I'm not sure of having it print anything at all is also overdoing it though. It might be. 

It might be okay and it'd make it less clutter for us. I'd say we can keep it to be silent for now given that it does tell you that changes were made. If it's ever a problem we could always make it say something anyway.

**Comment by xexyl** [comment]
> With commit [227cd90](https://github.com/ioccc-src/mkiocccentry/commit/227cd90c907f7cc6585ac0ab6f91477a4830901e)
> 
> fix make clobber
> 
> The make clobber rules in Makefiles now performs legacy_clobber (which is silent by default) which in turn performs legacy_clean (which is also silent by default).
> 
> As before, the clobber rules in Makefiles now performs clean.

Is it supposed to be silent now then? Because I don't see that.

As far as whether it should be - I don't think it's a problem to make it silent. Besides if it's cleaning the files up maybe it should be silent! :)

**Comment by xexyl** [comment]
I thought of another rule that might want to be silent or quieter. I want to go do other things and probably won't get to it today - and maybe it's better we discuss it first though I guess you might agree with this - but the rule is shellcheck. Because do we really need to see this?

```sh
$ make shellcheck 

mkiocccentry: make shellcheck starting

make --no-print-directory -C dbg shellcheck

dbg: make shellcheck starting

dbg: nothing to do

dbg: make shellcheck complete
make --no-print-directory -C dyn_array shellcheck

dyn_array: make shellcheck starting

dyn_array: nothing to do

dyn_array: make shellcheck complete
make --no-print-directory -C jparse shellcheck

jparse: make shellcheck starting

[...]
```

I think not. I also see there's a problem there - `dyn_array: nothing to do.` and the same with `dbg`.

But I'll be doing other things now. I'd be happy to fix this one if you like though I might have to look at how you do it because if you do it based on the variables it would be different how I would do it - remove the text entirely. But perhaps doing it via control variables is better.

**Comment by xexyl** [comment]
> I thought of another rule that might want to be silent or quieter. I want to go do other things and probably won't get to it today - and maybe it's better we discuss it first though I guess you might agree with this - but the rule is shellcheck. Because do we really need to see this?
> 
> ```shell
> $ make shellcheck 
> 
> mkiocccentry: make shellcheck starting
> 
> make --no-print-directory -C dbg shellcheck
> 
> dbg: make shellcheck starting
> 
> dbg: nothing to do
> 
> dbg: make shellcheck complete
> make --no-print-directory -C dyn_array shellcheck
> 
> dyn_array: make shellcheck starting
> 
> dyn_array: nothing to do
> 
> dyn_array: make shellcheck complete
> make --no-print-directory -C jparse shellcheck
> 
> jparse: make shellcheck starting
> 
> [...]
> ```
> 
> I think not. I also see there's a problem there - `dyn_array: nothing to do.` and the same with `dbg`.
> 
> But I'll be doing other things now. I'd be happy to fix this one if you like though I might have to look at how you do it because if you do it based on the variables it would be different how I would do it - remove the text entirely. But perhaps doing it via control variables is better.

Actually as a general rule (I can help it but I don't want to) do we need to see lines like:

> make --no-print-directory -C dbg shellcheck

?

I think probably not?

**Comment by xexyl** [comment]
Oh I should say `make prep` is now quieter with commit 282413f4e4381e8d0142a1e6973442e58e1c5f3e.

However I raised a concern about one of the thoughts you had suggested at the issue about improving prep.sh (comment: https://github.com/ioccc-src/mkiocccentry/issues/448#issuecomment-1371157738 and issue https://github.com/ioccc-src/mkiocccentry/issues/448). I made the change as suggested but due to make verbosity I have not committed it as it causes messed up output.

**Comment by lcn2** [comment]
> > Should the changes discussed in comment 1370794652l be applied `make clean` and `make clobber`? We are inclined to not silence `make clean` and `make clobber`. We are included to leave them as they are now.
> 
> > 
> 
> > Given the above change, `make clean` is not very verbose.
> 
> > 
> 
> > The `make clobber` is a bit more verbose because the `make clean` is also performed as part of the rule.
> 
> 
> 
> I'm not sure if it should be silent or not. It might make it less to look at when we're doing work on the repo which could be a good thing. And if we silence some of the compiling (if we do) why not clobber? The compiling might be more useful to see than the clobber I would think?

We think that silencing for the sake of being quiet is not, by itself, useful. 

When compiling you want to see things compile and to not sit is silence wondering what is happening, or worse see an error message where you have nil context. 

The `make clean` and `make clobber` often do something: remove previously compiled/build stuff. Seeing that happen, and it happens fast, seems OK. 

The `legacy_clean` and `legacy_clobber`, on the other hand, should do something once/one time never to do that again. They represent a one time cleanup from some actions that have changed/moved, unlikely to happen again.  New repo uses will never have such files, which is why we will clean out those removals as they were only useful one time to us. So making these legacy removals silent seems OK.

**Comment by lcn2** [comment]
> It might be good if it says a general make depend starting and make depend finished or something like that? I'm not sure.

Do you want each Makefile to indicate (via an echo) a start and end of such a rule?

We could introduce a variant of $Q that would pertain to such "starting" and "ending" echos in such a way that the symbol in front of the "starting" & "ending" echos would default to "@".

**Comment by lcn2** [comment]
> Is it supposed to be silent now then? Because I don't see that.

No, it isn't. 

Only the legacy stuff is silent.

**Comment by xexyl** [comment]
> > > Should the changes discussed in comment 1370794652l be applied `make clean` and `make clobber`? We are inclined to not silence `make clean` and `make clobber`. We are included to leave them as they are now.
> > 
> > 
> > > 
> > 
> > 
> > > Given the above change, `make clean` is not very verbose.
> > 
> > 
> > > 
> > 
> > 
> > > The `make clobber` is a bit more verbose because the `make clean` is also performed as part of the rule.
> > 
> > 
> > I'm not sure if it should be silent or not. It might make it less to look at when we're doing work on the repo which could be a good thing. And if we silence some of the compiling (if we do) why not clobber? The compiling might be more useful to see than the clobber I would think?
> 
> We think that silencing for the sake of being quiet is not, by itself, useful.
> 
> When compiling you want to see things compile and to not sit is silence wondering what is happening, or worse see an error message where you have nil context.
> 

Yes I agree. That’s what I was getting at. I think that that should be seen. See below. 

> The `make clean` and `make clobber` often do something: remove previously compiled/build stuff. Seeing that happen, and it happens fast, seems OK.
> 

True. What I was saying is that _if_ make clobber was to be silent that might be okay but make all should not be. 

> The `legacy_clean` and `legacy_clobber`, on the other hand, should do something once/one time never to do that again. They represent a one time cleanup from some actions that have changed/moved, unlikely to happen again. New repo uses will never have such files, which is why we will clean out those removals as they were only useful one time to us. So making these legacy removals silent seems OK.

That’s true of course.

**Comment by xexyl** [comment]
> > Is it supposed to be silent now then? Because I don't see that.
> 
> No, it isn't.
> 
> Only the legacy stuff is silent.

Thank you for clarifying.

**Comment by xexyl** [comment]
> > It might be good if it says a general make depend starting and make depend finished or something like that? I'm not sure.
> 
> Do you want each Makefile to indicate (via an echo) a start and end of such a rule?
> 
> We could introduce a variant of $Q that would pertain to such "starting" and "ending" echos in such a way that the symbol in front of the "starting" & "ending" echos would default to "@".

Well I was more thinking if we want information for it we could have a single starting and ending line: so that the user knows make depend is going to (and did) happen.

But of course if they do make depend in a subdirectory it'll be silent so maybe not. It's probably not necessary. As we've discussed the Makefiles are very verbose and besides that most users won't need to run make depend: that's for us and anyone else who works on the repo. Once a code freeze happens it'll be even less likely there will be any need for it.

So perhaps we can ignore this idea: keep it quiet and instead make more things quiet?

**Comment by lcn2** [comment]
With commit 63042d79f397203ca23f6c6508b6c02939ca928e we have completed our tuning of Makefile verbosity!

Of course, suggestions and corrections welcome.

**Comment by xexyl** [comment]
> With commit [63042d7](https://github.com/ioccc-src/mkiocccentry/commit/63042d79f397203ca23f6c6508b6c02939ca928e) we have completed our tuning of Makefile verbosity!
> 
> Of course, suggestions and corrections welcome.

I'll do this in a bit ... first trying to finish some fixes for some commits you made and then I have to leave for a bit. I might have to leave before I finish hat. I'll then address the picky repo and also this and anything else I've not yet addressed.

I'm fearing I might not be able to finish the fixes before I have to leave but I will return to it when I'm back for sure - no question about that.
