### ISSUE TITLE
On -a answers always overwriting answers

### ISSUE THREAD

**Issue by xexyl** [ioccc-src/mkiocccentry#47]
I think this is a mistake for the following reasons:

- It no longer reminds the user how to use the answers file.
- And maybe more importantly it means that a simple typo will overwrite the answers. This has happened to me more than once and although it's only test mode it could be annoying when the contest is running.

I suppose this is up to discussion but I believe the answers file should not be overwritten for these reasons.

Is there a reason you made it so it always overwrites the answers file?

**Comment by xexyl** [comment]
I had an idea to compromise if there's a good reason to have it always overwrite the answers file:

The tool could warn that it's about to overwrite the file and prompt them if they want to proceed or if they want to instead use the input option.

Another possibility (maybe this is a good idea anyway, I don't know - it just popped into my head though it's probably unnecessary) is a helper script that you can run instead of the tool directly. I'm not sure what this would look like and I also don't know if it's even necessary (it probably is not) but since it occurred to me I figured I'd bring it up.

**Comment by lcn2** [comment]
You make good points, @xexyl.  The 'overwrite the file and prompt them' would work.   And possibly the `mkiocccentry-test.sh` might (or might not) need updating, depending on how this is done.

A pull request would be appreciated.

**Comment by xexyl** [comment]
I'm not sure if I'll have time for this today but if not I should be able to tomorrow. Well, technically I have the time but I'm in the middle of something and although it's not important I'd like to finish it and after that I have to leave for the day. 

As for how it might be done I would think it would simply use the `yes_or_no()` function and if they confirm it'll overwrite it else it'll give them a message how to use it (which would be how it used to be). Another possibility is that there's a force option to overwrite the answers file so for example only overwrite the answers file IF the user also specifies a force option (what letter that would be I don't know but I suppose `-f`).

This is assuming there's a good reason to have it ever overwrite it in the first place. What was the thinking behind this? I'm sure there's a good reason for it but the reasons I gave are why I didn't have it overwrite it.

I also had a thought on another option that could be added which might be good for the test modes: an option to ignore all warnings (the warnings would still be noted in the .info.json file of course). I bring this up because this might be the right time to do it if modifying the script. Something tells me it wouldn't be desirable to have test mode automatically ignore (as in not display) warnings but maybe there's a use for the option in some situations?

**Comment by xexyl** [comment]
Okay I quickly programmed this but it does mean that the answers file has to be opened earlier in the code (or the test if it exists and not proceeding can go earlier instead) because otherwise it prompts for the ID and entry number first and then it will exit if you don't want to overwrite it which seems not the right order.

But this will work fine if there's a reason to overwrite the answers file. I'll leave this open for your reply and work on this tomorrow based on your reaction. If you don't have any reply I'll just clean it up and do a pull request.

I might be able to reply again today but if so probably via email on the phone. Cheers.

**Comment by lcn2** [comment]
Are we ready to close this issue, @xexyl ?

**Comment by xexyl** [comment]
﻿
Sure.
