### ISSUE TITLE
Enhancement: improve jsemcgen(8), jsemtblgen(8), and all_sem_ref(8) man pages

### ISSUE THREAD

**Issue by lcn2** [ioccc-src/mkiocccentry#475]
According to [comment 1374872796](https://github.com/ioccc-src/mkiocccentry/issues/455#issuecomment-1374872796), the following man pages need improvement:

- jsemcgen(8)
- jsemtblgen(8)
- all_sem_ref(8)

The description and in particular, discussion related to the semantics tables needs to be added or improved.

**Comment by lcn2** [comment]
Feel free to comment / suggest changes to the description of this issue #475.

**Comment by xexyl** [comment]
> Feel free to comment / suggest changes to the description of this issue #475.

Well it just needs to not refer to the IOCCC but make it more general for json semantics tables. But how I'm not entirely sure.

I was hoping that doing the `alt_url` yesterday would give me a clearer idea but if it does it's not there yet. I do know you made a comment that might be helpful in another issue but so far I'm not sure I know enough about the semantics tables to change it.

I mean I know it allows for a callback which can check the field including min, max and other things but the finer details I do not really know. I've seen the scripts in action but there are a lot of arguments and I've been focused on the other things.

A simple explanation would be helpful. I say simple meaning that I know you're preparing for some other things so if it's easier to write less but make it still useful feel free. If it's not (as often the case) and you have the time to write a bit more then please do so.

But that's what the issue is about: it refers to IOCCC but it's not just IOCCC and when I make jparse a new repo it'll have to not refer to IOCCC (well it can say it in the NOTES or a HISTORY section but not the DESCRIPTION section).

**Comment by xexyl** [comment]
With commit b41cdd25f0f4f4d3a1086699d5d43c23cc93397c (see below) this has been drastically improved which I hope will help you out a lot. 


    Improve JSON semantics tables man pages - #475
    
    In jsemtblgen.8 and jsemcgen.8 all references in the description to the
    IOCCC have been removed. As well references to IOCCC specific tools
    (e.g. in SEE ALSO) have been removed.
    
    A new symlink jsemcgen.sh.8 pointing to jsemcgen.8 has been added to the
    repo and this is also installed via make install. There is an issue that
    this will result in checknr (via check_man) rule to run on both files
    even though one is only a symlink. Perhaps this should be improved but
    it works for now.
    
    Because all_sem_ref.sh is IOCCC specific the references to the IOCCC
    have not been removed. In this file we need only an example use.
    
    The issue #475 is not yet complete as these man pages still need at
    least one example each (except for jsemtblgen as one should use jsemcgen
    instead and this is noted in the man page) but the description is, I
    believe, much better. Even though these tools are not specific to the
    IOCCC the examples could still be IOCCC specific as it's a working
    example.


If this all checks out then the only thing needed is an example. I don't have that in me right now to figure out but hopefully this will make it easier for you - esp as you're quite busy right now (okay well I mean you're probably sleeping right now but you know what I mean :-) ).

**Comment by lcn2** [comment]
We are working on this issue, but first we need of fix an issue in `jsemtblgen`.

**Comment by xexyl** [comment]
> We are working on this issue, but first we need of fix an issue in `jsemtblgen`. Not quite a bug, more like a mis-feature that when addressed will make the `jsemtblgen` more flexible.
> 
> ### UPDATE 0
> The issue has been addressed in commit [650d7c8](https://github.com/ioccc-src/mkiocccentry/commit/650d7c889f24d0290406cfab03043ac52d0b7f1d)
> 
> Now back to the man page (and the changes that are needed with that commit) ...

Thanks. I did indeed see that commit though I didn't look at anything but the log.

**Comment by lcn2** [comment]
More progress with commit 129fda3e3bae41a88360f9260a5e23c3614ebf0f

**Comment by xexyl** [comment]
> More progress with commit [129fda3](https://github.com/ioccc-src/mkiocccentry/commit/129fda3e3bae41a88360f9260a5e23c3614ebf0f)

Great!

**Comment by lcn2** [comment]
Having finished our work on tools such as `prep.sh` and `bug_report.sh` and Notice: counts, we return to working on this issue .. tomorrow.

**Comment by xexyl** [comment]
> Having finished our work on tools such as `prep.sh` and `bug_report.sh` and Notice: counts, we return to working on this issue .. tomorrow.

Sleep well my friend!

I am just waking up. Well been awake a bit but unable to do anything yet either: not rest and not do anything else. A very frustrating situation.

**Comment by lcn2** [comment]
With commit 20306e0cedb53085d23df1bf9a312a7275d5badb this issue has been resolved.

Edits and improvements to the man pages are welcome.

NOTE: When the _jparse repo_ is formed, an standalone example can be added, perhaps based on
the `jparse/test_jparse/test_JSON/good/party.json` file.

**Comment by xexyl** [comment]
> With commit [20306e0](https://github.com/ioccc-src/mkiocccentry/commit/20306e0cedb53085d23df1bf9a312a7275d5badb) this issue has been resolved.
> 

Thank you!

> Edits and improvements to the man pages are welcome.

I'll take a look .. working on the FAQ file now though it'll only be at this time two questions as it's all I can think of right now.

> 
> NOTE: When the _jparse repo_ is formed, an standalone example can be added, perhaps based on the `jparse/test_jparse/test_JSON/good/party.json` file.

Yes and a mini chkentry.c as you suggested. Good idea.

**Comment by xexyl** [comment]
Please see fbe5026ed1b568b13c44f502b7fcb7e24e9f670f for some fixes / adjustments.

**Comment by lcn2** [comment]
> Please see fbe5026ed1b568b13c44f502b7fcb7e24e9f670f for some fixes / adjustments.

Thank you 🙏 @xexyl

**Comment by xexyl** [comment]
> > Please see [fbe5026](https://github.com/ioccc-src/mkiocccentry/commit/fbe5026ed1b568b13c44f502b7fcb7e24e9f670f) for some fixes / adjustments.
> 
> Thank you 🙏 @xexyl

Sure. Hope you had a nice sleep!

I'm almost done looking at the scripts for error message problems. I'm not going through it as carefully as the C files possibly but still fixed a number of issues.

When I'm done with the last one I'll commit. After that I will look at documentation but I will not be able to continue much longer as my zoom meeting is in an hour.

I will maybe be able to continue for a bit after that but I might just end the day in that way.

**Comment by lcn2** [comment]
> Sure. Hope you had a nice sleep!

Yes, thank you .. and likewise.

**Comment by xexyl** [comment]
> > Sure. Hope you had a nice sleep!
> 
> Yes, thank you .. and likewise.

Glad you had a good sleep ... no I'm afraid I did not. The last few nights have been truly dreadful and it does not help my dogs have needed to go out and then I can't get back to sleep.

Thank you though.

**Comment by lcn2** [comment]
> > > Sure. Hope you had a nice sleep!
> > 
> > 
> > Yes, thank you .. and likewise.
> 
> Glad you had a good sleep ... no I'm afraid I did not. The last few nights have been truly dreadful and it does not help my dogs have needed to go out and then I can't get back to sleep.
> 
> Thank you though.

Hoping for better sleep for you in the near future.

**Comment by xexyl** [comment]
> > > > Sure. Hope you had a nice sleep!
> > > 
> > > 
> > > Yes, thank you .. and likewise.
> > 
> > 
> > Glad you had a good sleep ... no I'm afraid I did not. The last few nights have been truly dreadful and it does not help my dogs have needed to go out and then I can't get back to sleep.
> > Thank you though.
> 
> Hoping for better sleep for you in the near future.

Thank you. 

It’s actually interesting timing. 

I might have discovered one of the causes of the poor sleep including vivid dreams which have always affected me badly (even when they aren’t bad dreams). 

But since there’s a chance that I will be sleepy in the day I am holding off on it until after my birthday. But if everything goes okay I might actually have better sleep. 

Time will tell. 

I hope you have a great night and I will check out what you end up doing tonight when I get up tomorrow morning. 

Good night!
