### ISSUE TITLE
Question: Should the mkiocccentry tool help the user by deleting the temporary directory used to form the tarball ?

### ISSUE THREAD

**Issue by xexyl** [ioccc-src/mkiocccentry#49]
It seems like it might be a nice feature to add since it's possible for many that they update their entry (entries). They could do it manually and they would have to if the tool failed but I think this might make the tool just a bit easier to use, removing the burden from the user.

I'm happy to do this as it would be useful to me and probably others but if this is not desirable I'd rather not take the time to do this. What are the judges thoughts here?

**Comment by xexyl** [comment]
I can think of one possible reason to not: if they want to extract the tarball into another directory and then do a diff on the two to make sure it formed okay. But besides this I cannot think of a reason to not do this.

Curious as to what the judges think (or anyone else for that matter).

**Comment by lcn2** [comment]
We think people might want to look into and test their entry, after `mkiocccentry` has formed the tarball and before they upload it to the submit server.  This is why the directory was left behind.

The `mkiocccentry` does indicate that the user can run the `rm -rf` command if and when they choose.  Cleanup would require executing the `rm` command, find a path for it, etc.  We didn't want to alarm users by asking for a path to `rm(1)` on the command line of `mkiocccentry`.

Portably the answer to the question for #49 is no.

**Comment by xexyl** [comment]
Yes I thought of these very thoughts and indeed looking for the path to rm could alarm the user. 

I know you cite how to remove the directory but I felt since it’s halfway there it might be considered completing it. But like we both said the user might want to inspect it and anytime you talk about deletion it can indeed alarm users. 

Admittedly this feature would sometimes be useful to me but I can very well see myself extracting the tarball to verify that it was created properly. Though I also have a submission directory that has just the files to add (ad I have other files in my development directories that shouldn’t be submitted) I still probably will check that the tarball was created properly. 

This does make me think though: perhaps there could be another tool that does this for the user? I am not sure how it would work but maybe it’s something to think about?

Well I am going to sleep now. Maybe I can sleep on it. I don’t know about you but I suspect that you (I have a friend who has done this too) have woken up and suddenly you have a solution to a programming problem (or maybe any kind of problem). I have done this many times!

I doubt this will happen but it’s possible and some of the thoughts I have had about those checker tools have come up as I was waking up!

Any thoughts on a tool that helps the user verify that the tarball was created properly? That is how it might function and what kind of checks it could do. Is it even something worth considering? Personally I think it’s worth considering but as far as how it might work I would have to think about it. 

Have a great night mate! Will address the answers file being overwritten tomorrow most likely in the morning. Maybe I can look at some other things too and possibly the tarball checker tool. 

Cheers.

**Comment by xexyl** [comment]
Oh there might be one way to go about this. It just popped into my head. I will say it and then go to sleep. 

It could be an option to clean up the directory. But then again it could possibly alarm other users that don’t want it. 

I think that the way you implemented it is probably the only good way to do it. Still though I am very interested in your thoughts about creating a tool that verifies that the tarball was created properly. 

Another possible way to do it is simply provide the user a way to do it? Though if it was automated it probably would be better if enough thought was put into it. If you have thoughts on this I am definitely open to it. 

If you think it’s a good idea maybe you could open an issue with thoughts on how it might work and then we can discuss it there. I leave the path to that up to you - just let me know please if you move it to another place. 

Really going now. Cheers.

**Comment by lcn2** [comment]
Closing this issue as recent events have overtaken topic.

Feel free to open a new related issue if you think it is needed.

Thanks for raising this issue @xexyl

**Comment by xexyl** [comment]
I don't think it's needed no. I had thought of the points you brought up and it's reason to not have this implemented.

I still think it might be a good idea to have a tool that helps the user verify that the tarball was created properly. But then thinking on it maybe the tarball checker tool should do this as well by an option?
