### ISSUE TITLE
2503 is not the first prime after 2048

### ISSUE THREAD

**Issue by carlini** [ioccc-src/mkiocccentry#510]
This comment in iocccsize.c is incorrect: 2503 is not the first prime after 2048.

https://github.com/ioccc-src/mkiocccentry/blob/4ab609c3529292d9ab1fc1cda23d0b1c8a8f4b17/iocccsize.c#L37-L38

Now, 2053 on the other hand *is* the first prime after 2048 and 2053 was the rule in 2019. The new rules haven't been published, but either (a) this is a bug and the correct size should have been 2053, or (b) the IOCCC organizers have decided to be extremely generous and give participants another 500 bytes to work with, in which case the comment should be updated.

**Comment by lcn2** [comment]
The comment was not updated after we changed the size of 2503. We plan to update the comment accordingly. 🤓

Thanks for point this out: appreciated 👍

**Comment by xexyl** [comment]
The size was increased. 

But 2053 is the first prime after 2048:


```sh
$ primes 2048 2054
2053
```

Anyway the size was increased last year sometime.

I hope this reads okay .. have my distance glasses on. Going back to not be at the computer.

**Comment by lcn2** [comment]
### UPDATE 0

FYI: 2053 is largest known prime that can be expressed as the sum of three different 3-decimal digit zeroless palindromic primes: 2503 = 787 + 797 + 919 🤓

**Comment by xexyl** [comment]
> ### UPDATE 0
> FYI: 2053 is largest prime that can be expressed as the sum of three different 3-decimal digit zeroless palindromic primes: 2503 = 787 + 797 + 919 🤓

Very fun. Also this is fun for both of us since we both love space though maybe we'll both be unable to see it then :( 

> + Stargazers will get a rare triple planetary treat in November 2053, when Mercury, Mars, and Jupiter all lie within a circle of less than one degree in diameter. Recreational maths circles will no less be celebrating the fact that 2053# - 1 is a primorial prime.

From the [wondrous Prime Curios!](https://primes.utm.edu/curios/) which we've talked about before.

Thanks for that titbit too!

I have other thing I can say about palindromes (as you'd expect from me) but for another time maybe.

**Comment by carlini** [comment]
Thanks for the clarification! (And also, @lcn2 thank you so much for running the IOCCC. There's nothing else like it and it's just so much fun.)

**Comment by lcn2** [comment]
> Thanks for the clarification! (And also, @lcn2 thank you so much for running the IOCCC. There's nothing else like it and it's just so much fun.)

You are most welcome, @carlini   See commit fbc4a4e898f945a898dcc32c82999c6173a1938f

BTW: We are planning to invite a public review of this repo prior to the _IOCCCMOCK_ a dry run
of the IOCCC with the this toolset, submit server (under development), and the updated web site.

We appreciated your assistance!
