### ISSUE TITLE
Bug report: jparse column on invalid token is incorrect

### ISSUE THREAD

**Issue by xexyl** [ioccc-src/mkiocccentry#595]
## Describe the bug

When an invalid token is found in the json parser the line number shown is correct in the error message but the column is not unless it's actually at column 1.

## To Reproduce

Steps to reproduce the behaviour (adjust steps as needed):

0. Create an invalid json file (or use stdin) and run the json parser on it.
1. Observe the error message and compare to what it should be.

See the relevant output section for details.

## Expected behaviour

The column in this case should be 13, not 1. The line is correct.

## Relevant Output

```sh
$ ./jparse -
{"test":false,
"foo":"bar"},
syntax error node type JTYPE_OBJECT in file - at line 2 column 1: <,>
ERROR[1]: ./jparse: invalid JSON
```

Notice that it thinks the offending `,` is at column 1 even though it's actually at column 13!

## bug report attachment

To save time and because it's not relevant I'm not doing this. All the relevant output is above and the `bug_report.sh` will not show anything wrong here. I know because I wrote it (well that and it doesn't detect expected output just that bad json files are invalid .. maybe it should like my `txzchk_test.sh` script ?) :-)

## Please provide the following information:

 - Did you attach the above requested bug report file?  [yes, no & why not]
As above no for the above noted reason: to save time (I have a lot of other things to do with this repo!) and because it's not going to help in this case.

 - What is the airspeed Velocity of an Unladen Swallow? [n/a, :-), X m/s, unknown, etc.]

42.

## Additional context

Please add any other context about the problem here.

Feel free to use [markdown](https://www.markdownguide.org/getting-started/) in your issue report.

## Thank you, sorry (tm Canada :-) ), next steps

> We are sorry (tm Canada :-)) that you seem to have encountered an problem or issue that prompted
you to file this issue.  We **DO** appreciate your taking the time to inform us.

> **Please be patent!**  We work as volunteers and have a number of other pressing matters.
While we are often **very busy** we **WILL** look at your issue.

No problem: it's my fault anyway! :-) :-) :-)

Please assign it to me and I'll look at it in the coming days: trying to fit it in with the `jprint` tool that I'm also working on plus other things unrelated to this and the other repo.

**Comment by xexyl** [comment]
I _might_ have made progress but I'm not sure. I got it to show column 9 now.

```sh
$ ./jparse bar.json
syntax error node type JTYPE_OBJECT in file bar.json at line 2 column 9: <,>
ERROR[1]: ./jparse: invalid JSON
```

The change is:

```diff
diff --git i/jparse/jparse.l w/jparse/jparse.l
index 88d4bce7d8f05eab7ef96e45d18a49a335be1704..39a80246856b9cb5aff14c7dda0dde35d29a86cf 100644
--- i/jparse/jparse.l
+++ w/jparse/jparse.l
@@ -55,11 +55,11 @@ static YY_BUFFER_STATE bs;
 #define YY_USER_ACTION \
                        yylloc->filename = yyextra != NULL ? yyextra->filename:""; \
                        yylloc->first_line = yylloc->last_line = yylineno; \
                        yylloc->first_column = jparse_get_column(yyscanner); \
                        yylloc->last_column = jparse_get_column(yyscanner)+jparse_get_leng(yyscanner)-1; \
-                   jparse_set_column(jparse_get_leng(yyscanner), yyscanner);
+                 jparse_set_column(yylloc->last_column, yyscanner);
 %}
 
```

but what's strange is I swear yesterday in the error function I used `last_column` and it still reported 1.

I'm going to try and rest now. I'll do more in this repo later on .. certainly reply to the rest of the comments in the jprint issue but maybe more here too.

**Comment by xexyl** [comment]
I've fixed it! I'll do a commit now. Once the pull request is merged I'll close this as complete.

I felt like this should be fixed before I continue with jprint.

**Comment by xexyl** [comment]
> Fixed in commit [7a844a1](https://github.com/ioccc-src/mkiocccentry/commit/7a844a1852a9498de3b7ff27732b2831c43c2958).
> 
> Once you merge it I'll close this as resolved.
> 
> I can now look at jprint again without being bothered about this.

Improved slightly in https://github.com/ioccc-src/mkiocccentry/pull/601/commits/1f61338683be59b3d68c0b4d1bc3ccf5eee62a71. Use pointer access instead of array indexing.

Maybe not important but it's more beautiful in my eyes and I believe it might be more efficient though perhaps not with optimiser. Locations apparently do affect performance though but obviously it's a good idea to have them.

**Comment by lcn2** [comment]
We recommend the test code be added to verify that this bug is fixed and to avoid regression later on.

**Comment by xexyl** [comment]
> We recommend the test code be added to verify that this bug is fixed and to avoid regression later on.

Sounds good even though I'm certain it's fine. But then what if it isn't?

So the question is what did you have in mind? Some script that verifies the correct output? That's all I can think of and it would be like txzchk_test.sh. Doing this would take a bit of time but maybe it's worth it to do it first before continuing with `jprint` - or perhaps work on them both as I feel up to one or the other?

**Comment by lcn2** [comment]
> > We recommend the test code be added to verify that this bug is fixed and to avoid regression later on.
> 
> 
> 
> Sounds good even though I'm certain it's fine. But then what if it isn't?
> 
> 
> 
> So the question is what did you have in mind? Some script that verifies the correct output? That's all I can think of and it would be like txzchk_test.sh. Doing this would take a bit of time but maybe it's worth it to do it first before continuing with `jprint` - or perhaps work on them both as I feel up to one or the other?

A script like `txzchk_test.sh` is probably what is needed.

**Comment by xexyl** [comment]
> > > We recommend the test code be added to verify that this bug is fixed and to avoid regression later on.
> > 
> > 
> > Sounds good even though I'm certain it's fine. But then what if it isn't?
> > So the question is what did you have in mind? Some script that verifies the correct output? That's all I can think of and it would be like txzchk_test.sh. Doing this would take a bit of time but maybe it's worth it to do it first before continuing with `jprint` - or perhaps work on them both as I feel up to one or the other?
> 
> A script like `txzchk_test.sh` is probably what is needed.

Thanks .. I'd guess it could be an update to the jparse test script ? Anyway please remind me if I don't get to this! I have to leave for now and probably the day. I made great progress with jprint as you'll see.

**Comment by xexyl** [comment]
Should this be done before more work is done on jprint btw ?

Anyway have to leave now. Good day!

**Comment by lcn2** [comment]
> Should this be done before more work is done on jprint btw ?
> 
> 
> 
> Anyway have to leave now. Good day!

Before the bug issue is closed, yes.

**Comment by xexyl** [comment]
> > Should this be done before more work is done on jprint btw ?
> > Anyway have to leave now. Good day!
> 
> Before the bug report is closed, yes.

Have one more moment.

Before the bug is closed yes but before more work is done on jprint? I can maybe look at this tomorrow if you would rather I do that over the jprint work. Might even be a nice break from jprint too and a way to clear my head moving forwards. But if jprint is more important ...

Leaving now. I might be able to reply to some things later on but I wouldn't count on it until tomorrow. Hope you have a great day!

**Comment by xexyl** [comment]
One possible issue that might be very hard to fix or it might be easy to fix: `\t`. Check this out:

```sh
$ jparse auth.invalid-array-and-fields-0.json 
syntax error in file auth.invalid-array-and-fields-0.json at line 14 column 2: <:>
in parse_json(): JSON debug[1]: invalid JSON
Warning: jparse: JSON parse tree is NULL
ERROR[1]: jparse: invalid JSON
```

but opening the file in vim you see that the column is supposed to be 9, not 2 but there are actually only two characters: a tab and a space.

Do you know if a `\t` is always 8 characters? If so I can make it so that if a tab is seen it'll increment it by 8. I'll look at the standard draft later on after a rest ... hopefully it'll be that simple as I think it might be.

**Comment by xexyl** [comment]
With commit https://github.com/ioccc-src/mkiocccentry/pull/615/commits/2fefe79655573f0f9be0b5facbd6a48f8fdeda2e the functionality is added! Instructions on adding new files is in the man page, the git log and a new README.md file.

Only one file is added for now but it's simple to add more. It involves a new subdirectory to simplify things greatly.

Something that occurred to me is it might exit on error but if not maybe it should. The reason is that each time (and the txzchk_test.sh script has this same flaw but there's not much that can be done here) the jparse is invoked in the new function the same temporary stderr file is overwritten (of course). So one would have to fix it one at a time though without the new option `-k` the file won't be kept.

Please feel free to add files to be tested .. I can do that another time. Right now I have to go afk for a while and when I'm back I don't know what I'll do. I hope I can look at jprint's `-Y` option and then maybe look at the actual functionality of the tool but the latter one is I guess not that likely. We shall see!

Let me know when you consider this issue resolved and I will close it!

For now I will bid you well! Back later. Good day!

**Comment by xexyl** [comment]
Ran into a problem with the `-s` option of the test script and the exact error files. Unfortunately unless I can fix it very quickly I will probably have to do it tomorrow. Sorry. :(

**Comment by xexyl** [comment]
I got it working but it's kind of a kludge maybe and I have to leave very soon. I should be able to make it okay tomorrow - if not later today.

**Comment by xexyl** [comment]
I'm actually not sure if it's a good idea to have this test unless it's in a different script that the test suite calls. But it might work. I figured out how to deal with the subdirectory name problem but it seems to cause another problem.

Unfortunately I must leave now and I probably won't be able to work on this until tomorrow. At that point I can worry about whether this is feasible. Frustratingly this will bother me until it's resolved but I can't help that.

**Comment by xexyl** [comment]
I've fixed it if I'm not very much mistaken. Running make prep and if all is good I'll commit. I had to make a modification to the changed script so that it is only run with the `-L` option which only happens in the `make test` under `jparse`. It can't run from under `test_ioccc/` but since `make test` is run in `jparse` it's okay to do it this way.

**Comment by xexyl** [comment]
It worked! I'll open the other pull request again and then make a new one. Then I'll be done for the day.

**Comment by xexyl** [comment]
Commit https://github.com/ioccc-src/mkiocccentry/pull/617/commits/547b42acb3a60301635b04738455293461ec3b1b should resolve the problem. Please read the log for details on it as I have other things I'd like to do now. But basically it is only run under `jparse/` or `jparse/test_jparse` - not the `test_ioccc` directory. But this is okay as the latter doesn't need to run that part. The option to enable it is `-L`.

Will do more tomorrow.

**Comment by lcn2** [comment]
> Commit [547b42a](https://github.com/ioccc-src/mkiocccentry/commit/547b42acb3a60301635b04738455293461ec3b1b) should resolve the problem. Please read the log for details on it as I have other things I'd like to do now. But basically it is only run under `jparse/` or `jparse/test_jparse` - not the `test_ioccc` directory. But this is okay as the latter doesn't need to run that part. The option to enable it is `-L`.

We presume that:

```
First one must generate the error files from the directory
jparse/test_jparse like so:

    for i in test_JSON/./bad_loc/*.json; do ../jparse -- "$i" 2>"$i.err" ; done

Once this is done you must test it. You should be able to run make test
from the top level directory or from either the jparse or
jparse/test_jparse subdirectories. If everything goes okay you can then
add the new files including the error files like:

    git add ./jparse/test_jparse/test_JSON/bad_loc/*.json
    git add ./jparse/test_jparse/test_JSON/bad_loc/*.err

Then commit, push and make a pull request.
```

will be done as part of the final pull request that will resolve issue #595

**Comment by xexyl** [comment]
> > Commit [547b42a](https://github.com/ioccc-src/mkiocccentry/commit/547b42acb3a60301635b04738455293461ec3b1b) should resolve the problem. Please read the log for details on it as I have other things I'd like to do now. But basically it is only run under `jparse/` or `jparse/test_jparse` - not the `test_ioccc` directory. But this is okay as the latter doesn't need to run that part. The option to enable it is `-L`.
> 
> 
> 
> We presume that:
> 
> 
> 
> ```
> 
> First one must generate the error files from the directory
> 
> jparse/test_jparse like so:
> 
> 
> 
>     for i in test_JSON/./bad_loc/*.json; do ../jparse -- "$i" 2>"$i.err" ; done
> 
> 
> 
> Once this is done you must test it. You should be able to run make test
> 
> from the top level directory or from either the jparse or
> 
> jparse/test_jparse subdirectories. If everything goes okay you can then
> 
> add the new files including the error files like:
> 
> 
> 
>     git add ./jparse/test_jparse/test_JSON/bad_loc/*.json
> 
>     git add ./jparse/test_jparse/test_JSON/bad_loc/*.err
> 
> 
> 
> Then commit, push and make a pull request.
> 
> ```
> 
> 
> 
> will be done as part of the final pull request that will resolve issue #595 **OR** are you asking us to do something else?

Yes it did. Only one test file exists right now but we can add more later. I just wanted the functionality in. 

But it should be good. 

Let me know if you think of anything else. If you think it could be closed I will do that too. 

But now I am going to get some sleep. 

Good night!

**Comment by lcn2** [comment]
After updating with the latest pull requests and doing a:

```sh
make prep
```

The tests fail with:

```
make_action 31 test ERROR exit code 2
One or more tests failed:

	make_action 31: make -f ./Makefile test: non-zero exit code: 2

One or more tests failed.

See test_ioccc/test_ioccc.log for more details.

make prep: ERROR: ./test_ioccc/prep.sh exit code: 31

make prep: see build.log for details
make: *** [prep] Error 31
zsh: exit 2     make prepmake_action 31 test ERROR exit code 2
One or more tests failed:

	make_action 31: make -f ./Makefile test: non-zero exit code: 2

One or more tests failed.

See test_ioccc/test_ioccc.log for more details.

make prep: ERROR: ./test_ioccc/prep.sh exit code: 31

make prep: see build.log for details
make: *** [prep] Error 31
zsh: exit 2     make prep
```

And in particular:

```
jparse: make test starting

make --no-print-directory -C test_jparse test

test_jparse: make test starting

./jparse_test.sh -j ../jparse -d test_JSON -s . ./json_teststr.txt
./jparse_test.sh: in run_location_err_test: jparse_err_file not found for test that must fail: test_JSON/./bad_loc/backspace-comma.json.err
test_jparse: ERROR: jparse_test.sh failed, error code: 41
make[3]: *** [test] Error 41
make[2]: *** [test] Error 2
make[1]: *** [test] Error 2
ERROR exit code 2
One or more tests failed:

        make_action 31: make -f ./Makefile test: non-zero exit code: 2

One or more tests failed.

See test_ioccc/test_ioccc.log for more details.
```

**IMPORTANT ADDITIONAL NOTE**: There is no `test_ioccc/test_ioccc.log` file.

Attached is a bug report that was run after the `make prep`.

[bug-report.20230613.182030.txt](https://github.com/ioccc-src/mkiocccentry/files/11740627/bug-report.20230613.182030.txt)

**Comment by lcn2** [comment]
With pull request #617 this bug is resolved.  Thanks @xexyl 

However the "See test_ioccc/test_ioccc.log for more details." message written to the end of `build.log` was incorrect when the `test_jparse` failed.  With commit f2fb6e35b6a5a4d5b94c82f599a2659351e829c2, that message is only written when the `test_ioccc/test_ioccc.log` exists.

**Comment by xexyl** [comment]
> With pull request #617 this bug is resolved. Thanks @xexyl
> 
> However the "See test_ioccc/test_ioccc.log for more details." message written to the end of `build.log` was incorrect when the `test_jparse` failed. With commit [f2fb6e3](https://github.com/ioccc-src/mkiocccentry/commit/f2fb6e35b6a5a4d5b94c82f599a2659351e829c2), that message is only written when the `test_ioccc/test_ioccc.log` exists.

Thanks for taking care of that message! Hope you're sleeping well.

The next step is to add more files and also point out in the man page and README.md file that one should visually inspect the error messages first to make sure the column and line are both correct as far as where the error is!

**Comment by xexyl** [comment]
> ## UPDATE 0
> We saw there were more pull requites we had not yet processed. After merging pull request #617 the above "_make_action 31 test ERROR exit code 2_" went away.
> 
> Nevertheless, if you somehow force that error to occur, the `build.log` will end with:
> 
> ```
> See test_ioccc/test_ioccc.log for more details.
> ```
> 
> However is no `test_ioccc/test_ioccc.log` file.

Yup. I forgot to do a git add: ironically since I wrote about it in the log except that I think that part was accidentally left out of the log. It was in the README.md and the man page though.

Glad that you saw the other pull request that did resolve it. It required more than just adding the err file though as you no doubt noticed.

I'll check the other threads soon I hope .. then will try and sleep a bit more: can't sleep now but still not awake enough to do much.

**Comment by xexyl** [comment]
With commit https://github.com/ioccc-src/mkiocccentry/pull/618/commits/08ad2b065aba0d9e7a32a95f2fceb0bf97fdf857 this issue is now completely resolved.

Sorry you were awake enough to react to the above. I managed to get more sleep. Now that this issue is resolved I will look at addressing jprint. Not sure if that will be right now or in a bit but I should be able to address it today. I feel good about these fixes though!

**Comment by xexyl** [comment]
It seems that mixing tabs and spaces, as might be expected, causes invalid calculations. Check this invalid json file out. The `^ 16` is only there to show the what column it is so you can compare the error message.

```json
	       	
	       ^16 
```

Running `jprint` on it after the `^16` has been removed:

```sh
$ ./jprint test.json 
debug[0]: maximum depth to traverse: 256 (default)
syntax error in file test.json at line 2 column 15: empty text
ERROR[5]: jprint: test.json invalid JSON
```

I'm unsure if it's only for empty text or not but I suspect not. Even so in some cases it gets it right. The same file with another column added with just `{` and a space:

```sh
$ ./jprint test.json 
debug[0]: maximum depth to traverse: 256 (default)
syntax error in file test.json at line 2 column 17: empty text
ERROR[5]: jprint: test.json invalid JSON
```

Column 17 is where the `{` is.

Maybe this is not something worth trying to fix? I mean tabs and spaces being mixed is a problem that's really difficult to fix possibly more so if the tabs are configured to not be 8.

**Comment by xexyl** [comment]
Continuing the above comment...

Doing:

```sh
printf "\t\t  " > test2.json
```

and saving it to make sure it has an EOF:


```sh
$ ./jprint test2.json 
debug[0]: maximum depth to traverse: 256 (default)
syntax error in file test2.json at line 1 column 17: empty text
ERROR[5]: jprint: test2.json invalid JSON
```

The last character is at column 18 though. Unless that's another character that I'm not thinking of? Perhaps we nee the special EOF rule? I don't know the details of that one though and I'm not sure it's going to help.

**Comment by xexyl** [comment]
.. another one that might or might not be correct in error message:

```sh
 cat test2.json 
		  {
```

The `{` is at column 19. The error is:

```sh
$ ./jprint test2.json 
debug[0]: maximum depth to traverse: 256 (default)
syntax error in file test2.json at line 1 column 18: empty text
ERROR[5]: jprint: test2.json invalid JSON
```

But never mind the off by one column. Is it really empty text? It might be because nothing comes after the `{` but it would be better if it was more descriptive. That might or might not be possible though or at least if it is it might not be easy enough to worry about it?

**Comment by lcn2** [comment]
> .. another one that might or might not be correct in error message:
> 
> 
> 
> ```sh
> 
>  cat test2.json 
> 
> 		  {
> 
> ```
> 
> 
> 
> The `{` is at column 19. The error is:
> 
> 
> 
> ```sh
> 
> $ ./jprint test2.json 
> 
> debug[0]: maximum depth to traverse: 256 (default)
> 
> syntax error in file test2.json at line 1 column 18: empty text
> 
> ERROR[5]: jprint: test2.json invalid JSON
> 
> ```
> 
> 
> 
> But never mind the off by one column. Is it really empty text? It might be because nothing comes after the `{` but it would be better if it was more descriptive. That might or might not be possible though or at least if it is it might not be easy enough to worry about it?

Can you describe this effect enough to document it in the JSON parser man page in the BUGS section?  Doing that might be good enough instead of trying to fix it.

**Comment by xexyl** [comment]
> > .. another one that might or might not be correct in error message:
> > ```shell
> >  cat test2.json 
> > 
> > 		  {
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The `{` is at column 19. The error is:
> > ```shell
> > $ ./jprint test2.json 
> > 
> > debug[0]: maximum depth to traverse: 256 (default)
> > 
> > syntax error in file test2.json at line 1 column 18: empty text
> > 
> > ERROR[5]: jprint: test2.json invalid JSON
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But never mind the off by one column. Is it really empty text? It might be because nothing comes after the `{` but it would be better if it was more descriptive. That might or might not be possible though or at least if it is it might not be easy enough to worry about it?
> 
> Can you describe this effect enough to document it in the JSON parser man page in the BUGS section? Doing that might be good enough instead of trying to fix it.

It might indeed. Can you maybe put it on the todo list in the jprint issue? I know it's not not strictly the right location :-) but right now I cannot do it but don't want to forget.

Alternatively if possible you could reopen this issue?

I'm going to do other things now ... will do more tomorrow I'm sure. Possibly do other things here today too but that's not certain.

**Comment by xexyl** [comment]
Seems I already took care of the problem ... under BUGS:

> Although error reporting does have locations it is only line numbers and columns.  Additionally the column can be misleading because of characters that take up more than one column but are counted as just one (tabs for example).
