### ISSUE TITLE
Enhancement: add GitHub issue templates for easier reporting bugs / feature requests

### ISSUE THREAD

**Issue by xexyl** [ioccc-src/mkiocccentry#596]
**Is your feature request related to a problem? Please describe.**

Not as such: it's more like it would help make reporting issues much easier and clearer which sounds like a good idea. I've brought it up before but with your (Landon's) holiday and our other things we've been working on it was forgotten until I opened issue 595 - [Bug report: jparse column on invalid token is incorrect](https://github.com/ioccc-src/mkiocccentry/issues/595).

# Describe the solution you'd like

We should add issue templates. See the link in the additional context section.

# Describe alternatives you've considered

What I am suggesting: issue templates.

# Additional context

Information is at https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository.

What it would look like is in the following image, taken from the link above:

![GitHub issue template look](https://docs.github.com/assets/cb-80507/mw-1440/images/help/repository/sample-issue-form.webp)

BTW: the template we have here should if nothing else have not `**` for sections but headers either at level 1 or 2.

**Comment by xexyl** [comment]
In order to do this I'll have to play with the repo I made so that I don't mess anything up here. What priority is this though? I'd guess this is kind of low priority at this point? What do you prefer?

.. going to try taking a nap now .. back later.

**Comment by lcn2** [comment]
> I'd guess this is kind of low priority at this point?

Yes.

**Comment by xexyl** [comment]
> > I'd guess this is kind of low priority at this point?
> 
> Yes.

Of course.

I came here to write that I've not forgotten it but as expected it is low priority so I haven't even looked at it. Not that I'm particularly eager to do so: it has a config format I'm unfamiliar with. I already made (several days before I opened this issue) a test repo so I can test it (I'll make it the same questions etc. as we have here for both bugs and feature requests) so that a commit here doesn't cause a problem. But first jprint probably has to be done .. unless I have motivation for this and not that though I don't see that happening I must say.

I still have some fixes at the other repo to make that were introduced with the addition of the wondrous (and I truly mean that: thank you so much again for putting me at the top of the honours list! .. though I'm not surprised I'm still touched and it means a great deal to me) thanks file.

As well there I am not finished with the README.md files and I'm afraid I'll have to go over them all again even besides the one I haven't finished but the ones I have to go back on shouldn't take long. I also want to address any other known bugs that affect usability and then I would say that I'm good there. At least that's what I think at this point in time.

Going to try and look at jprint now ...

**Comment by lcn2** [comment]
We believe we have addressed all of the current questions that still need answering at this time. If we've missed something or something else needs to be clarified, please ask again.

**Comment by lcn2** [comment]
We believe this has been completed and so will close this issue.  If we are in error, please advise.

**Comment by xexyl** [comment]
> We believe this has been completed and so will close this issue.  If we are in error, please advise.

It certainly is. Not even sure why it was left open. Maybe both of us went to other things here. Thanks.
