### ISSUE TITLE
Bug report: jparse fails to correctly parse certain exp numbers

### ISSUE THREAD

**Issue by lcn2** [ioccc-src/mkiocccentry#750]
## Describe the bug

A **clear** and **concise** description of what the bug is.

## To Reproduce

Steps to reproduce the behavior (adjust steps as needed):

0. cd parse
1. ./jparse -v 0 -J 0 -- test_jparse/test_JSON/good/two-e0.json

## Expected behavior

The jparse tool should exit 0 with the message:

```
valid JSON
```

## Relevant Output

```
Warning: jparse_lex: at line 1 column 2: invalid token: 0x65 = <e>
syntax error node type JTYPE_NUMBER in file test_jparse/test_JSON/good/two-e0.json at line 1 column 2: <e>
ERROR[1]: ./jparse: invalid JSON
```

## bug report attachment

We request that you **PLEASE** run the command:

```sh
./bug_report.sh
```

and attach the bug report file that `./bug_report.sh` generated.
The bug report file will be a filename in the same directory with a
filename of the form: `bug-report.YYYYMMDD.HHMMSS.txt` and it will tell you the
name as well.

vvvvvvvvvvvvvvvvvvvvvvvvv --- Drag the file into the area below, please!

[bug-report.20230712.174127.txt](https://github.com/ioccc-src/mkiocccentry/files/12034303/bug-report.20230712.174127.txt)

^^^^^^^^^^^^^^^^^^^^^^^^^ --- Drag the file into the area above, please!

## Please provide the following information:

 - Did you attach the above requested bug report file?  yes
 - What is the airspeed Velocity of an Unladen Swallow? n/a

## Additional context

The so-called JSON spec allows for JSON numbers of the form:

[1-9][0-9]*[eE]...

For example, 2e0 is valid JSON.

**Comment by lcn2** [comment]
WIth commit bc8a8ea58780f2c8a77a49e5c43ef0e572bc943e we added files that trigger the bug.

**Comment by xexyl** [comment]
Thanks. I will look at it tomorrow. Really have to go now. 

But I don't know that file. Is it a file that's not supposed to be there that is causing the problem? That's what it seems like. Maybe it got there by accident on your end? 

Last time I ran the test suite it didn't have a problem and that file doesn't look familiar. 

Just a thought. If not I will look tomorrow. Good night!

**Comment by lcn2** [comment]
> Thanks. I will look at it tomorrow. Really have to go now.
> 
> But I don't know that file. Is it a file that's not supposed to be there that is causing the problem? That's what it seems like. Maybe it got there by accident on your end?
> 
> Last time I ran the test suite it didn't have a problem and that file doesn't look familiar.
> 
> Just a thought. If not I will look tomorrow. Good night!

We discovered the bug, added files that trigger it in commit bc8a8ea58780f2c8a77a49e5c43ef0e572bc943e.

We plan to use those files as examples in the spec file.

**Comment by xexyl** [comment]
> > Thanks. I will look at it tomorrow. Really have to go now.
> 
> > 
> 
> > But I don't know that file. Is it a file that's not supposed to be there that is causing the problem? That's what it seems like. Maybe it got there by accident on your end?
> 
> > 
> 
> > Last time I ran the test suite it didn't have a problem and that file doesn't look familiar.
> 
> > 
> 
> > Just a thought. If not I will look tomorrow. Good night!
> 
> 
> 
> We discovered the bug, added files that trigger it in commit bc8a8ea58780f2c8a77a49e5c43ef0e572bc943e.
> 
> 
> 
> We plan to use those files as examples in the spec file.

Sounds good. 

Well more from me tomorrow. Have a great night!

**Comment by xexyl** [comment]
I hope to look at this soon. Without having the computer out it sounds like a regexp:pattern matching problem but I wonder if it has always been there or not. 

I hope it is not too difficult to find the source of the problem.

**Comment by xexyl** [comment]
... it appears to be the regexp though: that did not seem to be it and commenting out a warning message where my first thought was and it did not show up which means that it's indeed there. What is wrong with:

```flex
JSON_NUMBER             ({JSON_INTEGER}|{JSON_INTEGER}{JSON_FRACTION}|{JSON_INTEGER}{JSON_FRACTION}{JSON_EXPONENT})
```

... ?

... because it seems like that's the problem ...

**Comment by xexyl** [comment]
> ... it appears to be the regexp though: that did not seem to be it and commenting out a warning message where my first thought was and it did not show up which means that it's indeed there. What is wrong with:
> 
> ```lex
> JSON_INTEGER            -?([1-9][0-9]*|0)
> JSON_FRACTION           "."[0-9]+
> JSON_EXPONENT           [Ee][-+]?[0-9]+
> JSON_NUMBER             ({JSON_INTEGER}|{JSON_INTEGER}{JSON_FRACTION}|{JSON_INTEGER}{JSON_FRACTION}{JSON_EXPONENT})
> ```
> 
> ... ?
> 
> ... because it seems like that's the problem ...

Yup: it definitely is that. Changing the pattern of `JSON_NUMBER` to be the actual string `1e0` and it works fine!

So it's a regexp issue ... but it looks fine. I'll take a break and come back to it .. or maybe take a break. I do have other things I'd like to do but maybe I can look at the spec document.

**Comment by xexyl** [comment]
> > ... it appears to be the regexp though: that did not seem to be it and commenting out a warning message where my first thought was and it did not show up which means that it's indeed there. What is wrong with:
> > ```lex
> > JSON_INTEGER            -?([1-9][0-9]*|0)
> > JSON_FRACTION           "."[0-9]+
> > JSON_EXPONENT           [Ee][-+]?[0-9]+
> > JSON_NUMBER             ({JSON_INTEGER}|{JSON_INTEGER}{JSON_FRACTION}|{JSON_INTEGER}{JSON_FRACTION}{JSON_EXPONENT})
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ... ?
> > ... because it seems like that's the problem ...
> 
> Yup: it definitely is that. Changing the pattern of `JSON_NUMBER` to be the actual string `1e0` and it works fine!
> 
> So it's a regexp issue ... but it looks fine. I'll take a break and come back to it .. or maybe take a break. I do have other things I'd like to do but maybe I can look at the spec document.

Note that it's only exponent that's the problem: fractions work fine.

**Comment by xexyl** [comment]
I've located the problem! Stay tuned ...

**Comment by xexyl** [comment]
... fixed! Will make a commit very soon.

**Comment by xexyl** [comment]
> ... fixed! Will make a commit very soon.

However I see that the googolplex file still fails so I have to figure out that one ...

**Comment by xexyl** [comment]
> > ... fixed! Will make a commit very soon.
> 
> However I see that the googolplex file still fails so I have to figure out that one ...

It must be because it's too big? That's what I first thought and now I am sure of it:

```sh
$ ./jparse test_jparse/test_JSON/good/googolplex.json 
Warning: json_conv_number: JSON number as floating point or e-notation number failed: <1e10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000>
ERROR[170]: parse_json_number: couldn't convert number string: <1e10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000>
```

I'll move the file to another file and indicate that although valid JSON it's too big. Or maybe I'll just remove it and we can decide what to do about it later.

**Comment by xexyl** [comment]
Running `make prep` ... will do a commit and pull request if all good ...

**Comment by xexyl** [comment]
... another part of make test fails ... checking it out.

**Comment by xexyl** [comment]
> ... another part of make test fails ... checking it out.

Looks like it was a file that was in a bad/ directory that should be in good/ ... but this makes me wonder if the googolplex file should be in another directory: valid json but not possible to parse. Not sure if we have that in a test directory or not.

**Comment by xexyl** [comment]
If I'm not very much mistaken commit https://github.com/ioccc-src/mkiocccentry/pull/751/commits/010c7b07c86ad7ea6b72d2180b1481e51e63f7c4 fixes this bug.
