### ISSUE TITLE
Define exit codes for the tools

### ISSUE THREAD

**Issue by xexyl** [ioccc-src/mkiocccentry#76]
Based on the point you made from the recent commit maybe it's a good idea to discuss exit codes for all the tools. Obviously non-zero is one or more issues but what should they be?

I have some ideas but right now I'm too tired to really put them to words.

Maybe opening an issue a discussion can be had about it. After that the tools can be updated as well as the man pages.

I'll add my thoughts later on - I think it won't be until tomorrow.

**Comment by lcn2** [comment]
See our [general remarks on exit codes](https://github.com/ioccc-src/mkiocccentry/pull/75#issuecomment-1039722930),

As far as documenting, sometimes what is useful is to document a few select exit codes in the usage message / man page:

```sh
curds [-h] [-v level} [-x] foo ...

    -h             print usage message and exit
    -v level    enable debug messages
     ...
    foo           something

Exit codec:

    0 - all is well
    1 - usage error
    2 - foo is missing
    >2 - internal or fatal error
```

NOT all exit code should be documented, nor is ti useful to document every possible exit point.  Only those few exit codes that might be meaningful to a user, and then only a few, need be documented.  And a general (all other values >= x) catch all can be used to deal with everything else.

There are currently 321 possible exit points in the `mkiocccentry` repo.  Those exit codes are NOT compatible across different versions.  Only a few critical and externally useful exit codes need be documented.  And if a need arises to change such a documented exit code, then almost always the code AND the documentation for those few select exit codes should be updated.

**Comment by xexyl** [comment]
> See our [general remarks on exit codes](https://github.com/ioccc-src/mkiocccentry/pull/75#issuecomment-1039722930),
> 

Just replied there. It was helpful indeed though I'm still not sure what I should change the exit codes _to_.

> As far as documenting, sometimes what is useful is to document a few select exit codes in the usage message / man page:

That makes sense yes. I still have to update the man pages to refer to just non-zero for error, 0 for success (as I had changed it yesterday).

> 
> ```shell
> curds [-h] [-v level} [-x] foo ...
> 
>     -h             print usage message and exit
>     -v level    enable debug messages
>      ...
>     foo           something
> 
> Exit codec:
> 
>     0 - all is well
>     1 - usage error
>     2 - the foo file was not found or was not readable
>     >=3 - some internal or fatal error
> ```
> 
> NOT all exit code should be documented, nor is ti useful to document every possible exit point. Only those few exit codes that might be meaningful to a user, and then only a few, need be documented. And a general (all other values >= x) catch all can be used to deal with everything else.

Right. As long as the error code is printed the user can report it and it doesn't have to be documented. 

> 
> There are currently 321 possible exit points in the `mkiocccentry` repo. Those exit codes are NOT compatible across different versions. Only a few critical and externally useful exit codes need be documented. And if a need arises to change such a documented exit code, then almost always the code AND the documentation for those few select exit codes should be updated.

Yep. Thanks for the information. Now it's just a matter of coming up with the different error codes. Does all this mean that the different tools should have unique error codes? I see for example that in `mkiocccentry.c` there is an error code `1` but it does not exist in `txzchk` (I might have added that but I know you've changed the error codes). 

Should I worry about these calls? I guess I should not and I should only focus on the final `exit()` function. But in that case I'm still not sure what I should do for the tools since it seems that doing `exit(total_issues != 0)` is not ideal. Please advise and I'll be happy to do it.

**Comment by lcn2** [comment]
> > NOT all exit code should be documented, nor is ti useful to document every possible exit point. Only those few exit codes that might be meaningful to a user, and then only a few, need be documented. And a general (all other values >= x) catch all can be used to deal with everything else.
> 
> Right. As long as the error code is printed the user can report it and it doesn't have to be documented.

Yes.  Only a few specific exit codes, if any, might need to be documented in, say, the man page.  Perhaps even less so in the help / usage message.  Utility functions such as `txzchk`, and `fnamchk` that have an _exit 0 if OK_ mode of operation, for example, might simply need:

```sh
Exit codes:

    0 - check successful
    >=0 - one or more checks failed or internal error
```

**Comment by lcn2** [comment]
> > There are currently 321 possible exit points in the `mkiocccentry` repo. Those exit codes are NOT compatible across different versions. Only a few critical and externally useful exit codes need be documented. And if a need arises to change such a documented exit code, then almost always the code AND the documentation for those few select exit codes should be updated.
> 
> Yep. Thanks for the information. Now it's just a matter of coming up with the different error codes. Does all this mean that the different tools should have unique error codes? I see for example that in `mkiocccentry.c` there is an error code `1` but it does not exist in `txzchk` (I might have added that but I know you've changed the error codes).
> 
> Should I worry about these calls? I guess I should not and I should only focus on the final `exit()` function. But in that case I'm still not sure what I should do for the tools since it seems that doing `exit(total_issues != 0)` is not ideal. Please advise and I'll be happy to do it.

We don't need unique error codes across the entire repo as there are not enough codes to go around.  :-)  On the other hand making everything `exit(1)` is not helpful when someone (to you) reports _program exited status 1_.

Spreading around the codes in a file is helpful to the developer when a test exits with a numeric code, or a user reports a problem and provides a code.

**Comment by xexyl** [comment]
> > > There are currently 321 possible exit points in the `mkiocccentry` repo. Those exit codes are NOT compatible across different versions. Only a few critical and externally useful exit codes need be documented. And if a need arises to change such a documented exit code, then almost always the code AND the documentation for those few select exit codes should be updated.
> > 
> > 
> > Yep. Thanks for the information. Now it's just a matter of coming up with the different error codes. Does all this mean that the different tools should have unique error codes? I see for example that in `mkiocccentry.c` there is an error code `1` but it does not exist in `txzchk` (I might have added that but I know you've changed the error codes).
> > Should I worry about these calls? I guess I should not and I should only focus on the final `exit()` function. But in that case I'm still not sure what I should do for the tools since it seems that doing `exit(total_issues != 0)` is not ideal. Please advise and I'll be happy to do it.
> 
> We don't need unique error codes across the entire repo as there are not enough codes to go around. :-) 

Fair enough. So should these individual tools use magic numbers then?

On the other hand making everything `exit(1)` is not helpful when someone (to you) reports _program exited status 1_.

Definitely agree 

> 
> Spreading around the codes in a file is helpful to the developer when a test exits with a numeric code, or a user reports a problem and provides a code.

Agreed.

**Comment by xexyl** [comment]
> > > NOT all exit code should be documented, nor is ti useful to document every possible exit point. Only those few exit codes that might be meaningful to a user, and then only a few, need be documented. And a general (all other values >= x) catch all can be used to deal with everything else.
> > 
> > 
> > Right. As long as the error code is printed the user can report it and it doesn't have to be documented.
> 
> Yes. Only a few specific exit codes, if any, might need to be documented in, say, the man page. Perhaps even less so in the help / usage message. Utility functions such as `txzchk`, and `fnamchk` that have an _exit 0 if OK_ mode of operation, for example, might simply need:

Yes. 

> 
> ```shell
> Exit codes:
> 
>     0 - check successful
>     >0 - one or more checks failed or internal error
> ```

I believe I did that in the man pages update of today. I don’t think it’s necessary to have it in the help message but of you think otherwise I will be happy to add it to `txzchk` - the other two have it.

**Comment by lcn2** [comment]
> Fair enough. So should these individual tools use magic numbers then?

Yes.

We should probably create a repo for `seqcexit` as that tool makes this job trivial:

```sh
seqcexit dbg.c jauthchk.c jinfochk.c fnamchk.c mkiocccentry.c txzchk.c util.c json.c jstrencode.c jstrdecode.c
```

**Comment by xexyl** [comment]
> > Fair enough. So should these individual tools use magic numbers then?
> 
> Yes.
> 
> We should probably create a repo for `seqcexit` as that tool makes this job trivial:
> 
> ```shell
> seqcexit dbg.c jauthchk.c jinfochk.c fnamchk.c mkiocccentry.c txzchk.c util.c json.c jstrencode.c jstrdecode.c
> ```

Sure. I would like to see that tool.

**Comment by xexyl** [comment]
And I think we might have had some crossover messages (maybe that’s not the right word but it’s all I can think of) so I will end it at that. 

More tomorrow. I guess if you make the tool available this issue can be closed but I will let you decide.

**Comment by lcn2** [comment]
See the [seqcexit](https://github.com/lcn2/seqcexit) repo for the `seqcexit` tool.

**Comment by lcn2** [comment]
Are we finished this this issue #76?

**Comment by xexyl** [comment]
Yes. That’s fine. Closing it.

**Comment by xexyl** [comment]
> See the [seqcexit](https://github.com/lcn2/seqcexit) repo for the `seqcexit` tool.

I got a 404. Would you please fix this when you get a chance? Also it occurred to me that if it was in the `mkiocccentry` repo (I don't know how much code is in there and maybe it'd be adding unnecessary code/files/data to the `mkiocccentry` repo) that there could be commit hooks which run the tools on all the files (maybe via the Makefile? I don't know much about git hooks but I recall seeing years ago git commit hooks/scripts that do certain things on commit and I know the way you used to have it done - when Simon took care of this stuff - there was a script that was run, too, that emailed the list of winners).

Just a thought and maybe it'd only taint this repo. Either way when you fix the link I'll clone the repo and make sure to install it and use it from now on (if you think you'd like that and if it'd be helpful to you). Just let me know.

**Comment by lcn2** [comment]
Sirry @xexyl the [seqcexit repo](https://github.com/lcn2/seqcexit) was marked private by mistake.

**Comment by xexyl** [comment]
> Sirry @xexyl the [seqcexit repo](https://github.com/lcn2/seqcexit) was marked private by mistake.

It’s quite all right. 

I am still trying to recover from exhaustion but I hope that tomorrow will be better. If so expect an update! 

I am going to sleep now. Have a good rest of your day and sleep well when you do!
