### ISSUE TITLE
Bug report: txzchk -q prints diagnostic messages

### ISSUE THREAD

**Issue by lcn2** [ioccc-src/mkiocccentry#864]
## Describe the bug

The command:

```sh
txzchk -q submit.12345678-1234-4321-abcd-1234567890ab-0.1715843229.txz
```

outputs what looks like a tar listing.

## To Reproduce

Steps to reproduce the behavior (adjust steps as needed):

0. form a compressed tarball submit file
1. txzchk  -q submit...stuff....txz

## Expected behavior

The `txzchk` command with given `-q` should **NOT** print tar listing.
Moreover, when given a valid compressed tarball submit file with `-q`,
the command should just exit 0.

## Relevant Output

```
$  txzchk -q submit.12345678-1234-4321-abcd-1234567890ab-0.1715843229.txz
drwxr-xr-x  0 501    20          0 May 16 11:44 12345678-1234-4321-abcd-1234567890ab-0/
-rw-r--r--  0 501    20       1856 May 16 00:07 12345678-1234-4321-abcd-1234567890ab-0/Makefile
-rw-r--r--  0 501    20          4 May 16 00:07 12345678-1234-4321-abcd-1234567890ab-0/extra2
-rw-r--r--  0 501    20       1185 May 16 11:44 12345678-1234-4321-abcd-1234567890ab-0/.auth.json
-rw-r--r--  0 501    20         61 May 16 00:07 12345678-1234-4321-abcd-1234567890ab-0/prog.c
-rw-r--r--  0 501    20       3829 May 16 00:07 12345678-1234-4321-abcd-1234567890ab-0/remarks.md
-rw-r--r--  0 501    20       1543 May 16 11:44 12345678-1234-4321-abcd-1234567890ab-0/.info.json
-rw-r--r--  0 501    20          4 May 16 00:07 12345678-1234-4321-abcd-1234567890ab-0/extra1
```

BTW: The `txzchk` did correctly exit 0.

## bug report attachment

We request that you **PLEASE** run the command:

```sh
./bug_report.sh
```

and attach the bug report file that `./bug_report.sh` generated.
The bug report file will be a filename in the same directory with a
filename of the form: `bug-report.YYYYMMDD.HHMMSS.txt` and it will tell you the
name as well.

vvvvvvvvvvvvvvvvvvvvvvvvv --- Drag the file into the area below, please!

[bug-report.20240516.122521.txt](https://github.com/ioccc-src/mkiocccentry/files/15339935/bug-report.20240516.122521.txt)

^^^^^^^^^^^^^^^^^^^^^^^^^ --- Drag the file into the area above, please!

## Please provide the following information:

 - Did you attach the above requested bug report file?  yes
 - What is the airspeed Velocity of an Unladen Swallow? n/a

## Additional context

🤓

**Comment by lcn2** [comment]
This is a show stopper for the submit server, @xexyl

**Comment by xexyl** [comment]
> This is a show stopper for the submit server, @xexyl

This is by necessity for the txzchk test suite. I can change the option letter or I can do something else but it's necessary for the test suite.

Let me know what you prefer.

**Comment by xexyl** [comment]
> > This is a show stopper for the submit server, @xexyl
> 
> This is by necessity for the txzchk test suite. I can change the option letter or I can do something else but it's necessary for the test suite.
> 
> Let me know what you prefer.

Perhaps a different option would work? Especially as the help suggests it won't show anything.

But then again it mighta also be because it uses `tar(1)` with the options in order to parse the tarball. What I can say is that the test suite uses the option `-q`.

**Comment by xexyl** [comment]
Hmm .. I just tried this:

```sh
$ txzchk -q -T -E txt test_ioccc/test_txzchk/good/submit.test-0.1922598666.txt
$ 
```

No output.

**Comment by xexyl** [comment]
Can you please upload the tarball so I can try it out? Since as above I get no output when trying it out on a text based one. Not sure why you got output.

**Comment by xexyl** [comment]
> Can you please upload the tarball so I can try it out? Since as above I get no output when trying it out on a text based one. Not sure why you got output.
> 
> ## UPDATE 0
> Ah .. looking at the code it's because I had to use `-T`. Without that option it does run `tar` itself. Can you think of a way to do that without showing the output?

I have an idea but I need a valid tarball for the contest to test it.

**Comment by xexyl** [comment]
Okay I fixed it .. I think. So tests show. I'll do a quick update and then back to other things.

**Comment by xexyl** [comment]
See if commit https://github.com/ioccc-src/mkiocccentry/pull/865/commits/b20a877875f6cd9a813f298c02207ad41a032e6f does what you need. It appears to but maybe I missed something?

Off again.

**Comment by xexyl** [comment]
> See if commit [b20a877](https://github.com/ioccc-src/mkiocccentry/commit/b20a877875f6cd9a813f298c02207ad41a032e6f) does what you need. It appears to but maybe I missed something?
> 
> Off again.

Just updated version quickly and did `make test`. All seems okay. Still didn't run `mkiocccentry` itself but probably it's fine as it wouldn't use `-q` on `txzchk` I think. If it does I'll have to change that some I guess.

**Comment by xexyl** [comment]
.. and I must leave for the day. If more work has to be done here please let me know what and I'll look at it tomorrow.

**Comment by xexyl** [comment]
> All fixed 👍 thank you @xexyl 

Thank you for letting me know. Fortunately it was just an oversight on my part. 

I noticed that there are some missing debug messages there too but I was in the middle of something else and wanted it to be fixed so I didn't worry about that. 

It's questionable whether it would be beneficial to have them there. 

I am about to go to bed but hopefully tomorrow I can look at the manifest. 

I still would like to know what the commit from yesterday I guess it was looks to you. I haven't even had a chance yet myself. 

Hope you have a great night.
