### ISSUE TITLE
[Bug] duplicate keys in .editorconfig

### ISSUE THREAD

**Issue by SirWumpus** [ioccc-src/mkiocccentry#880]
### Is there an existing issue for this?

- [X] I have searched for existing issues and did not find anything like it

### Describe the bug

When opening a TextPad workspace for the `mkiocccentry` with several files, the editor complains about a duplicate key in the `.editorconfig`.  

The duplicate key is:
```
13: insert_final_newline = true
```

![editorconfig_dups](https://github.com/ioccc-src/mkiocccentry/assets/7441729/1855b0a6-eaf4-49b0-9a16-1ccb1dea9287)

### What you expect

`Silence! I kill you.`

### Environment

```markdown
- OS:
- Device:
- Compiler:
```

**Comment by lcn2** [comment]
We presume that pull request #881 has addressed this bug. 

Thanks for reporting it @SirWumpus
