### ISSUE TITLE
typos in cp/ls check error messages

### ISSUE THREAD

**Issue by ilyakurdyukov** [ioccc-src/mkiocccentry#9]
```
"    mkiocccentry -t cp ...",
"    mkiocccentry -t cp ...",
"    mkiocccentry -c ls ...",
"    mkiocccentry -t ls ...",
"    mkiocccentry -t ls ...",
```
Should be:
```
"    mkiocccentry -c cp ...",
"    mkiocccentry -c cp ...",
"    mkiocccentry -l ls ...",
"    mkiocccentry -l ls ...",
"    mkiocccentry -l ls ...",
```

**Comment by lcn2** [comment]
Thank you @ilyakurdyukov,  there were in general a number of issues related to the tar, cp and ls utilities, including the issue you identified.

Version 0.26 2022-01-17 fixed your issue as well as a number of related issues.

Thank you again for your feedback, it is APPRECIATED!
