### ISSUE TITLE
[Bug] jfmt does not format JSON well

### ISSUE THREAD

**Issue by lcn2** [ioccc-src/mkiocccentry#928]
### Is there an existing issue for this?

- [X] I have searched for existing issues and did not find anything like this

### Describe the bug

The command following command does not format the JSON file:

```sh
jfmt -I tab test_ioccc/test_JSON/auth.json/good/auth.min-whitespace.json
```

Even though `-I tab` used.  The same problem occurs with:

```sh
jfmt -I tab -F simple test_ioccc/test_JSON/auth.json/good/auth.min-whitespace.json
```

### What you expect

We expect that the `jfmt(1)` tool would format the JSON file.

Consider the output from the [JSONPath.sh tool](https://github.com/lcn2/JSONPath.sh):

```sh
JSONPath.sh -S -A -T -j -f test_ioccc/test_JSON/auth.json/good/auth.min-whitespace.json
```

We would expect that the following `jfmt(1)` tool  output would be identical to the above `JSONPath.sh` tool.

```sh
jfmt -I tab -F simple test_ioccc/test_JSON/auth.json/good/auth.min-whitespace.json
```

### Environment

```markdown
- OS: macOS 14.6.1
- Device: MacBook Pro M1
- Compiler: n/a
```

### bug_report.sh output

n/a

### Anything else?

We recommend that you install the [JSONPath.sh tool](https://github.com/lcn2/JSONPath.sh) as the interface for this tool serves as a good model for later tools (such as `jval(1)` and `jmanval(1)`) as well this `jfmt(1)` tool.

For now, please install the [JSONPath.sh tool](https://github.com/lcn2/JSONPath.sh) tool.  We will address the later tools (such as `jval(1)` and `jmanval(1)`)  much later.

FYI: For that other repo, the `bin/jfmt-wrapper.sh` was written to temporary use the [JSONPath.sh tool](https://github.com/lcn2/JSONPath.sh) tool with the hope that eventually it will use the `jfmt(1)` tool.  Also the `bin/jprint-wrapper.sh` is also witten to use the same JSONPath.sh tool](https://github.com/lcn2/JSONPath.sh) tool with the hope that eventually it will also use the `jfmt(1)` tool

**Comment by xexyl** [comment]
It doesn't format it well but that's because it's incomplete and will be heavily modified and almost entirely rewritten. 

And of course the priority is over at the other repo. 

Maybe this is better for the issue that is about those tools? Just a thought. 

That being said it looks like here are some useful things to look at when it's time (maybe all the more reason to be over there). 
Back tomorrow.

**Comment by xexyl** [comment]
As for commit 8acd9b0f3e29f5bacb812910d1459cba95875901 this is unfortunate as it was for developmental purposes. Now it requires remembering to do a `-J` option :( which when working on these tools again will be a pain.

**Comment by xexyl** [comment]
As for assigning this to me. That's fine as it was my task to work on this tool. But the priority is something else. The other repo is more important at this time, right? Yet I was going to wait on these tools (which is issue #523) being developed and tested before making jparse another repo .. though perhaps that is not strictly necessary.

Anyway: priority please? I have other things I need to do now but I hope I can look at this more tomorrow and maybe work on the other repo a bit too. I have a comment over there to make but then have to do other things and it's extremely unlikely I'll be able to do anything else here until tomorrow.

**Comment by xexyl** [comment]
Oh I will install that tool of course .. will look at it shortly (I hope but if not then I should be able to tomorrow or the next day).

**Comment by lcn2** [comment]
When we attempted to try to use the code in an even limited, we found issues.   We even, for a bit, forgot that the code was still "in development".  This code has been part of the code base for over a year and has been there for releases.

We considered not filing the issue, but instead thought that calling attention to the [JSONPath.sh tool](https://github.com/lcn2/JSONPath.sh) was useful.  The [JSONPath.sh tool](https://github.com/lcn2/JSONPath.sh) command line model seems useful to consider, especially the patterns for things like `jval(1)` and `jnamval(1)`, and `jfmt(1)`.

As you state in [GH-issuecomment-2278613143](https://github.com/ioccc-src/mkiocccentry/issues/928#issuecomment-2278613143):

> "it's incomplete and will be heavily modified and almost entirely rewritten"

Nevertheless, what is there to prevent others, especially when the testing phase of IOCCC (before IOCCC28) starts after that other repo's "**Great Fork Merge**", when we invite the larger public to test the code in this repo, from filing bug reports against it?  And when IOCCC28 starts, even more attention will be paid to this code?

Perhaps the real problem is that the `jval(1)` and `jnamval(1)`, and `jfmt(1)` code is sitting in the master branch of this [mkiocccentry repo](https://github.com/ioccc-src/mkiocccentry) in an undone state?  We invite people to give feedback (and we believe they will when the events of the previous paragraph happen), so how are they to know?

## QUESTION

For now, why don't we remove `jval(1)` and `jnamval(1)`, and `jfmt(1)` code from the repo of this code base for now, especially since "_and will be heavily modified and almost entirely rewritten_"?

You could keep that code, before commit 8acd9b0f3e29f5bacb812910d1459cba95875901, in your [jparse repo](https://github.com/xexyl/jparse) if you wish.  Or not if you think it is more likely to be "_almost entirely rewritten_" (especially if the [JSONPath.sh tool](https://github.com/lcn2/JSONPath.sh) command line model is used in part).

We then would issue another release of this [mkiocccentry repo](https://github.com/ioccc-src/mkiocccentry) without such code, removing the temptation for the public to try it and report bugs on it.

We would be happy to do such a clean out of this [mkiocccentry repo](https://github.com/ioccc-src/mkiocccentry) and then closed this issue.

What, @xexyl, do you think about that?

**Comment by xexyl** [comment]
Good points. Yes I think that would be better. Making a copy now.

That being said would you please copy the OP of this issue into the other issue? That way we can discuss these things later.

Thanks! I have one other thing to do in the other repo and then I will be doing other things and won't return for the day (at least not to do things).

**Comment by xexyl** [comment]
Oh don't forget the README files that are for these tools! And any man pages.

**Comment by lcn2** [comment]
We will do the clean out, post the commits, first.

We then review the result, ask for feedback and edits, before closing this issue and before making a new release.

**Comment by xexyl** [comment]
Thanks! I'll take a look at it tomorrow but please remind me if I don't get to it!

**Comment by lcn2** [comment]
> That being said would you please copy the OP of this issue into the other issue? That way we can discuss these things later.

If we understood your request correctly, we have created [GH-issuecomment-2282218741](https://github.com/ioccc-src/mkiocccentry/issues/723#issuecomment-2282218741).  We hope this helps.

**Comment by lcn2** [comment]
With commit 624fbb02309d26bdac636373233f7f4c7a12ee67 we remove jfmt, jval, jnamval

We remove jfmt, jval, and jnamval from the code base until they are ready
to be tested so that the general public and/or IOCCC submitters do not
become confused by these "not ready" tools and file bug reports on them.

In [GH-issuecomment-2282221142](https://github.com/ioccc-src/mkiocccentry/issues/523#issuecomment-2282221142)
a model based on the [JSONPath.sh](issuecomment-2282221142) command line
be considered for jfmt, jval, jnamval.

In
[GH-issuecomment-2278613143](https://github.com/ioccc-src/mkiocccentry/issues/928#issuecomment-2278613143)
it has been stated that jfmt, jval, jnamval are "_incomplete and will
be heavily modified and almost entirely rewritten_".  In light of the
the [JSONPath.sh](issuecomment-2282221142) command line model, the
"_entirely rewritten_" is much more likely.

Therefore we remove nearly all references to jfmt, jval, and jnamval.

We have **NOT** removed every reference to jfmt, jval, and jnamval:

- The `CHANGES.md` file will continue to contain historical references
to jfmt, jval, and jnamval.

- The `make uninstall` will continue to remove any installed binary and
man page related to jfmt, jval, and jnamval.

- The `jparse/.gitignore` file ignores the jfmt, jval, and jnamval binary
files to make it easier for future developers to work on those tools.

- The _JSON_UTIL_MATCH_TYPE_ types are left in `jparse/json_util.h`
as they related to types of JSON elements that could be matched later on.

- The `struct json_util_number_range` and `struct json_util_number`
files to make it easier for future developers to work on those tools.

- The `json_util_parse_number_range()` function in `jparse/json_util.c`
is left because it may be useful for future tools need to compare numbers.

- The `json_util_number_in_range` function in `jparse/json_util.c`
is left because it may be useful for future tools need to compare numbers.

- The `json_util_parse_st_level_option()` function in `jparse/json_util.c`
is left because it may be useful for future tools need to focus on parse
tree levels.

Performed `make release` to test the above under macOS.

**Comment by xexyl** [comment]
Thanks for keeping those functions and macros I put in, in! I would have wiped those out probably without thinking about it.

Can this issue be closed as prematurely opened? And yes I agree with that the tools will be almost entirely rewritten.

I know you wrote the json semantics concept .. have to check that but have other things I need to take care of too. I should at least be able to read it today but if not then certainly tomorrow.

**Comment by xexyl** [comment]
As far as evaluating whether or not you got everything removed I would guess you did. It is hard to be 100% certain as this was done a long time back and before I got sick but I think we're probably good. If we see anything we can always fix it, right?

**Comment by SirWumpus** [comment]
In the case of `jfmt` I assume is a JSON pretty printer.  Could not some C beautifier tool like `indent(1)` be used?  eg. `indent -br some.json` to handle indenting braces.

IMO not sure if making JSON pretty is worth the effort.

Another suggestion would be to put it out to the IOCCC28 contestants (lacking in original ideas and imagination) to submit a JSON formatter entry; maybe the other tools too. 😈  Save us having to do the work 😁

**Comment by xexyl** [comment]
> In the case of `jfmt` I assume is a JSON pretty printer.  Could not some C beautifier tool like `indent(1)` be used?  eg. `indent -br some.json` to handle indenting braces.
> 
> 
> 
> IMO not sure if making JSON pretty is worth the effort.
> 
> 
> 
> Another suggestion would be to put it out to the IOCCC28 contestants (lacking in original ideas and imagination) to submit a JSON formatter entry; maybe the other tools too. 😈  Save us having to do the work 😁
> 
> 
> 
> ## Update
> 
> Contest condition: it shouldn't be their only entry if they do.  I could just see 1000 versions `jfmt` pop into existence.

It does **MUCH MORE** than that. It's also part of a suite of tools. 

And we don't want it obfuscated. It's meant to be part of jparse and there are specific reasons it is my task. 

Landon of course will contribute to it and down the road others might too but not at first. 

Also the development of this tool has no connection to the contest and it won't delay it either. I will be working on it after the next one. 

Unless by some chance I don't submit to the contest. Even so it won't be a delay.

**Comment by lcn2** [comment]
Closing this issue as "not planned" given that `jfmt` was removed for now.
