### ISSUE TITLE
Enhancement: Improve templates so that extra lines or long lines work better

### ISSUE THREAD

**Issue by lcn2** [ioccc-src/mkiocccentry#994]
### Is there an existing issue for this?

- [X] I have searched for existing issues and did not find anything like this

### Describe the enhancement

The problem is that due to the markdown if someone adds extra lines it is all messed up. Even if they do not add extra lines if the lines are long, because it's markdown, and in particular code blocks, it makes the lines extra long instead of wrapping.

### Relevant images, screenshots or other files

line 1
line B
line 2+1
line 2^2
line e
line 1+2+3
line out

### Relevant links

[This is a very lone line that is intended to see of the extra wordage will cause the formatting to be missed up, for certain values of messed and up as noted in the above description where is states "Even if they do not add extra lines if the lines are long"](#)

```c
static char *very_very_very_long_line_of_source_code = "Now the above description also states `"particular code blocks\", well this here is such a long code block that might do something to mess up the formatting, but we are not sure."
```

### Anything else?

A test repo that I used to figure out the issue templates (including the bug template) can be used to figure this out.

Is this just a **feature** of issues that cannot be fixed in a template?

This is **NOT** a priority.

**Comment by lcn2** [comment]
We note that the above does **NOT** look messed up.

Is this still an issue?

**Comment by xexyl** [comment]
> ## QUESTION
> 
> 
> 
> We note that the above does **NOT** look messed up.
> 
> 
> 
> Is this still an issue?

It was in environment field. I believe I fixed it with a recent commit. 

So I guess not? 

I will reply to your other comments tomorrow. 

Hope you get some good sleep and continue to get better!

Good night!
